package org.apache.xml.serializer.utils;

import java.util.ListResourceBundle;

public class SerializerMessages_tr extends ListResourceBundle {
   public Object[][] getContents() {
      Object[][] contents = new Object[][]{{"ER_SERIALIZER_NOT_CONTENTHANDLER", "Diziselleştirici sınıfı ''{0}'' org.xml.sax.ContentHandler işlevini uygulamıyor."}, {"ER_RESOURCE_COULD_NOT_FIND", "Kaynak [ {0} ] bulunamadı.\n {1}"}, {"ER_RESOURCE_COULD_NOT_LOAD", "Kaynak [ {0} ] yükleyemedi: {1} \n {2} \n {3}"}, {"ER_BUFFER_SIZE_LESSTHAN_ZERO", "Arabellek büyüklüğü <=0"}, {"ER_INVALID_UTF16_SURROGATE", "UTF-16 yerine kullanılan değer geçersiz: {0} ?"}, {"ER_OIERROR", "GÇ hatası"}, {"ER_ILLEGAL_ATTRIBUTE_POSITION", "Alt düğümlerden sonra ya da bir öğe üretilmeden önce {0} özniteliği eklenemez. Öznitelik yoksayılacak."}, {"ER_NAMESPACE_PREFIX", "''{0}'' önekine ilişkin ad alanı bildirilmedi."}, {"ER_STRAY_NAMESPACE", "''{0}''=''{1}'' ad alanı bildirimi öğenin dışında."}, {"ER_COULD_NOT_LOAD_RESOURCE", "''{0}'' yüklenemedi (CLASSPATH değişkeninizi inceleyin), yalnızca varsayılanlar kullanılıyor"}, {"ER_COULD_NOT_LOAD_METHOD_PROPERTY", "''{1}'' çıkış yöntemi için ''{0}'' özellik dosyası yüklenemedi (CLASSPATH değişkenini inceleyin)"}, {"ER_INVALID_PORT", "Kapı numarası geçersiz"}, {"ER_PORT_WHEN_HOST_NULL", "Anasistem boş değerliyken kapı tanımlanamaz"}, {"ER_HOST_ADDRESS_NOT_WELLFORMED", "Anasistem doğru biçimli bir adres değil"}, {"ER_SCHEME_NOT_CONFORMANT", "Şema uyumlu değil."}, {"ER_SCHEME_FROM_NULL_STRING", "Boş değerli dizgiden şema tanımlanamaz"}, {"ER_PATH_CONTAINS_INVALID_ESCAPE_SEQUENCE", "Yol geçersiz kaçış dizisi içeriyor"}, {"ER_PATH_INVALID_CHAR", "Yol geçersiz karakter içeriyor: {0}"}, {"ER_FRAG_INVALID_CHAR", "Parça geçersiz karakter içeriyor"}, {"ER_FRAG_WHEN_PATH_NULL", "Yol boş değerliyken parça tanımlanamaz"}, {"ER_FRAG_FOR_GENERIC_URI", "Parça yalnızca soysal URI için tanımlanabilir"}, {"ER_NO_SCHEME_IN_URI", "URI içinde şema bulunamadı: {0}"}, {"ER_CANNOT_INIT_URI_EMPTY_PARMS", "Boş değiştirgelerle URI kullanıma hazırlanamaz"}, {"ER_NO_FRAGMENT_STRING_IN_PATH", "Parça hem yolda, hem de parçada belirtilemez"}, {"ER_NO_QUERY_STRING_IN_PATH", "Yol ve sorgu dizgisinde sorgu dizgisi belirtilemez"}, {"ER_NO_PORT_IF_NO_HOST", "Anasistem belirtilmediyse kapı belirtilemez"}, {"ER_NO_USERINFO_IF_NO_HOST", "Anasistem belirtilmediyse kullanıcı bilgisi belirtilemez"}, {"ER_SCHEME_REQUIRED", "Şema gerekli!"}};
      return contents;
   }
}
