package org.apache.xml.serializer.utils;

import java.util.ListResourceBundle;

public class SerializerMessages_pt_BR extends ListResourceBundle {
   public Object[][] getContents() {
      Object[][] contents = new Object[][]{{"ER_SERIALIZER_NOT_CONTENTHANDLER", "A classe de serializador ''{0}'' não implementa org.xml.sax.ContentHandler."}, {"ER_RESOURCE_COULD_NOT_FIND", "O recurso [ {0} ] não pôde ser encontrado.\n {1}"}, {"ER_RESOURCE_COULD_NOT_LOAD", "O recurso [ {0} ] não pôde carregar: {1} \n {2} \n {3}"}, {"ER_BUFFER_SIZE_LESSTHAN_ZERO", "Tamanho do buffer <=0"}, {"ER_INVALID_UTF16_SURROGATE", "Detectado substituto UTF-16 inválido: {0} ?"}, {"ER_OIERROR", "Erro de E/S"}, {"ER_ILLEGAL_ATTRIBUTE_POSITION", "Impossível incluir atributo {0} depois de nós filhos ou antes da geração de um elemento. O atributo será ignorado."}, {"ER_NAMESPACE_PREFIX", "Namespace para prefixo ''{0}'' não foi declarado. "}, {"ER_STRAY_NAMESPACE", "Declaração de namespace ''{0}''=''{1}'' fora do elemento. "}, {"ER_COULD_NOT_LOAD_RESOURCE", "Não foi possível carregar ''{0}'' (verifique CLASSPATH), utilizando agora somente os padrões"}, {"ER_COULD_NOT_LOAD_METHOD_PROPERTY", "Não foi possível carregar o arquivo de propriedade ''{0}'' para o método de saída ''{1}'' (verifique CLASSPATH)"}, {"ER_INVALID_PORT", "Número de porta inválido"}, {"ER_PORT_WHEN_HOST_NULL", "A porta não pode ser definida quando o host é nulo"}, {"ER_HOST_ADDRESS_NOT_WELLFORMED", "O host não é um endereço formado corretamente"}, {"ER_SCHEME_NOT_CONFORMANT", "O esquema não está em conformidade."}, {"ER_SCHEME_FROM_NULL_STRING", "Impossível definir esquema a partir da cadeia nula"}, {"ER_PATH_CONTAINS_INVALID_ESCAPE_SEQUENCE", "O caminho contém seqüência de escape inválida"}, {"ER_PATH_INVALID_CHAR", "O caminho contém caractere inválido: {0}"}, {"ER_FRAG_INVALID_CHAR", "O fragmento contém caractere inválido"}, {"ER_FRAG_WHEN_PATH_NULL", "O fragmento não pode ser definido quando o caminho é nulo"}, {"ER_FRAG_FOR_GENERIC_URI", "O fragmento só pode ser definido para um URI genérico"}, {"ER_NO_SCHEME_IN_URI", "Nenhum esquema encontrado no URI: {0}"}, {"ER_CANNOT_INIT_URI_EMPTY_PARMS", "Impossível inicializar URI com parâmetros vazios"}, {"ER_NO_FRAGMENT_STRING_IN_PATH", "O fragmento não pode ser especificado no caminho e fragmento"}, {"ER_NO_QUERY_STRING_IN_PATH", "A cadeia de consulta não pode ser especificada na cadeia de consulta e caminho"}, {"ER_NO_PORT_IF_NO_HOST", "Port não pode ser especificado se host não for especificado"}, {"ER_NO_USERINFO_IF_NO_HOST", "Userinfo não pode ser especificado se host não for especificado"}, {"ER_SCHEME_REQUIRED", "O esquema é obrigatório!"}};
      return contents;
   }
}
