package org.apache.xml.serializer.utils;

import java.util.ListResourceBundle;

public class SerializerMessages_pl extends ListResourceBundle {
   public Object[][] getContents() {
      Object[][] contents = new Object[][]{{"ER_SERIALIZER_NOT_CONTENTHANDLER", "Klasa szeregująca ''{0}'' nie implementuje procedury obsługi org.xml.sax.ContentHandler."}, {"ER_RESOURCE_COULD_NOT_FIND", "Nie można znaleźć zasobu [ {0} ].\n {1}"}, {"ER_RESOURCE_COULD_NOT_LOAD", "Zasób [ {0} ] nie mógł załadować: {1} \n {2} \n {3}"}, {"ER_BUFFER_SIZE_LESSTHAN_ZERO", "Wielkość bufora <=0"}, {"ER_INVALID_UTF16_SURROGATE", "Wykryto niepoprawny surogat UTF-16: {0} ?"}, {"ER_OIERROR", "Błąd we/wy"}, {"ER_ILLEGAL_ATTRIBUTE_POSITION", "Nie można dodać atrybutu {0} po węzłach potomnych ani przed wyprodukowaniem elementu.  Atrybut zostanie zignorowany."}, {"ER_NAMESPACE_PREFIX", "Nie zadeklarowano przestrzeni nazw dla przedrostka ''{0}''."}, {"ER_STRAY_NAMESPACE", "Deklaracja przestrzeni nazw ''{0}''=''{1}'' poza elementem."}, {"ER_COULD_NOT_LOAD_RESOURCE", "Nie można załadować ''{0}'' (sprawdź CLASSPATH), używane są teraz wartości domyślne"}, {"ER_COULD_NOT_LOAD_METHOD_PROPERTY", "Nie można załadować pliku właściwości ''{0}'' dla metody wyjściowej ''{1}'' (sprawdź CLASSPATH)"}, {"ER_INVALID_PORT", "Niepoprawny numer portu"}, {"ER_PORT_WHEN_HOST_NULL", "Nie można ustawić portu, kiedy host jest pusty"}, {"ER_HOST_ADDRESS_NOT_WELLFORMED", "Host nie jest poprawnie skonstruowanym adresem"}, {"ER_SCHEME_NOT_CONFORMANT", "Schemat nie jest zgodny."}, {"ER_SCHEME_FROM_NULL_STRING", "Nie można ustawić schematu z pustego ciągu znaków"}, {"ER_PATH_CONTAINS_INVALID_ESCAPE_SEQUENCE", "Ścieżka zawiera niepoprawną sekwencję o zmienionym znaczeniu"}, {"ER_PATH_INVALID_CHAR", "Ścieżka zawiera niepoprawny znak {0}"}, {"ER_FRAG_INVALID_CHAR", "Fragment zawiera niepoprawny znak"}, {"ER_FRAG_WHEN_PATH_NULL", "Nie można ustawić fragmentu, kiedy ścieżka jest pusta"}, {"ER_FRAG_FOR_GENERIC_URI", "Fragment można ustawić tylko dla ogólnego URI"}, {"ER_NO_SCHEME_IN_URI", "Nie znaleziono schematu w URI {0}"}, {"ER_CANNOT_INIT_URI_EMPTY_PARMS", "Nie można zainicjować URI z pustymi parametrami"}, {"ER_NO_FRAGMENT_STRING_IN_PATH", "Nie można podać fragmentu jednocześnie w ścieżce i fragmencie"}, {"ER_NO_QUERY_STRING_IN_PATH", "Tekstu zapytania nie można podać w tekście ścieżki i zapytania"}, {"ER_NO_PORT_IF_NO_HOST", "Nie można podać portu, jeśli nie podano hosta"}, {"ER_NO_USERINFO_IF_NO_HOST", "Nie można podać informacji o użytkowniku, jeśli nie podano hosta"}, {"ER_SCHEME_REQUIRED", "Schemat jest wymagany!"}};
      return contents;
   }
}
