package org.apache.batik.util;

public interface XMLConstants {
   String XML_NAMESPACE_URI = "http://www.w3.org/XML/1998/namespace";
   String XMLNS_NAMESPACE_URI = "http://www.w3.org/2000/xmlns/";
   String XLINK_NAMESPACE_URI = "http://www.w3.org/1999/xlink";
   String XML_EVENTS_NAMESPACE_URI = "http://www.w3.org/2001/xml-events";
   String XML_PREFIX = "xml";
   String XMLNS_PREFIX = "xmlns";
   String XLINK_PREFIX = "xlink";
   String XML_BASE_ATTRIBUTE = "base";
   String XML_ID_ATTRIBUTE = "id";
   String XML_LANG_ATTRIBUTE = "lang";
   String XML_SPACE_ATTRIBUTE = "space";
   String XML_BASE_QNAME = "xml:base";
   String XML_ID_QNAME = "xml:id";
   String XML_LANG_QNAME = "xml:lang";
   String XML_SPACE_QNAME = "xml:space";
   String XML_DEFAULT_VALUE = "default";
   String XML_PRESERVE_VALUE = "preserve";
   String XML_EVENTS_EVENT_ATTRIBUTE = "event";
   String XLINK_HREF_ATTRIBUTE = "href";
   String XLINK_HREF_QNAME = "xlink:href";
   String XML_TAB = "    ";
   String XML_OPEN_TAG_END_CHILDREN = " >";
   String XML_OPEN_TAG_END_NO_CHILDREN = " />";
   String XML_OPEN_TAG_START = "<";
   String XML_CLOSE_TAG_START = "</";
   String XML_CLOSE_TAG_END = ">";
   String XML_SPACE = " ";
   String XML_EQUAL_SIGN = "=";
   String XML_EQUAL_QUOT = "=\"";
   String XML_DOUBLE_QUOTE = "\"";
   char XML_CHAR_QUOT = '"';
   char XML_CHAR_LT = '<';
   char XML_CHAR_GT = '>';
   char XML_CHAR_APOS = '\'';
   char XML_CHAR_AMP = '&';
   String XML_ENTITY_QUOT = "&quot;";
   String XML_ENTITY_LT = "&lt;";
   String XML_ENTITY_GT = "&gt;";
   String XML_ENTITY_APOS = "&apos;";
   String XML_ENTITY_AMP = "&amp;";
   String XML_CHAR_REF_PREFIX = "&#x";
   String XML_CHAR_REF_SUFFIX = ";";
   String XML_CDATA_END = "]]>";
   String XML_DOUBLE_DASH = "--";
   String XML_PROCESSING_INSTRUCTION_END = "?>";
   String XML_VERSION_10 = "1.0";
   String XML_VERSION_11 = "1.1";
}
