package org.apache.batik.dom.svg;

public interface SVGPathSegConstants {
   String PATHSEG_ARC_ABS_LETTER = "A";
   String PATHSEG_ARC_REL_LETTER = "a";
   String PATHSEG_CLOSEPATH_LETTER = "z";
   String PATHSEG_CURVETO_CUBIC_ABS_LETTER = "C";
   String PATHSEG_CURVETO_CUBIC_REL_LETTER = "c";
   String PATHSEG_CURVETO_CUBIC_SMOOTH_ABS_LETTER = "S";
   String PATHSEG_CURVETO_CUBIC_SMOOTH_REL_LETTER = "s";
   String PATHSEG_CURVETO_QUADRATIC_ABS_LETTER = "Q";
   String PATHSEG_CURVETO_QUADRATIC_REL_LETTER = "q";
   String PATHSEG_CURVETO_QUADRATIC_SMOOTH_ABS_LETTER = "T";
   String PATHSEG_CURVETO_QUADRATIC_SMOOTH_REL_LETTER = "t";
   String PATHSEG_LINETO_ABS_LETTER = "L";
   String PATHSEG_LINETO_HORIZONTAL_ABS_LETTER = "H";
   String PATHSEG_LINETO_HORIZONTAL_REL_LETTER = "h";
   String PATHSEG_LINETO_REL_LETTER = "l";
   String PATHSEG_LINETO_VERTICAL_ABS_LETTER = "V";
   String PATHSEG_LINETO_VERTICAL_REL_LETTER = "v";
   String PATHSEG_MOVETO_ABS_LETTER = "M";
   String PATHSEG_MOVETO_REL_LETTER = "m";
   String[] PATHSEG_LETTERS = new String[]{null, "z", "M", "m", "L", "l", "C", "c", "Q", "q", "A", "a", "H", "h", "V", "v", "S", "s", "T", "t"};
}
