package org.apache.xalan.res;

import java.util.ListResourceBundle;
import java.util.Locale;
import java.util.MissingResourceException;
import java.util.ResourceBundle;

public class XSLTErrorResources_tr extends ListResourceBundle {
   public static final int MAX_CODE = 201;
   public static final int MAX_WARNING = 29;
   public static final int MAX_OTHERS = 55;
   public static final int MAX_MESSAGES = 231;
   public static final String ER_NO_CURLYBRACE = "ER_NO_CURLYBRACE";
   public static final String ER_ILLEGAL_ATTRIBUTE = "ER_ILLEGAL_ATTRIBUTE";
   public static final String ER_NULL_SOURCENODE_APPLYIMPORTS = "ER_NULL_SOURCENODE_APPLYIMPORTS";
   public static final String ER_CANNOT_ADD = "ER_CANNOT_ADD";
   public static final String ER_NULL_SOURCENODE_HANDLEAPPLYTEMPLATES = "ER_NULL_SOURCENODE_HANDLEAPPLYTEMPLATES";
   public static final String ER_NO_NAME_ATTRIB = "ER_NO_NAME_ATTRIB";
   public static final String ER_TEMPLATE_NOT_FOUND = "ER_TEMPLATE_NOT_FOUND";
   public static final String ER_CANT_RESOLVE_NAME_AVT = "ER_CANT_RESOLVE_NAME_AVT";
   public static final String ER_REQUIRES_ATTRIB = "ER_REQUIRES_ATTRIB";
   public static final String ER_MUST_HAVE_TEST_ATTRIB = "ER_MUST_HAVE_TEST_ATTRIB";
   public static final String ER_BAD_VAL_ON_LEVEL_ATTRIB = "ER_BAD_VAL_ON_LEVEL_ATTRIB";
   public static final String ER_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML = "ER_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML";
   public static final String ER_PROCESSINGINSTRUCTION_NOTVALID_NCNAME = "ER_PROCESSINGINSTRUCTION_NOTVALID_NCNAME";
   public static final String ER_NEED_MATCH_ATTRIB = "ER_NEED_MATCH_ATTRIB";
   public static final String ER_NEED_NAME_OR_MATCH_ATTRIB = "ER_NEED_NAME_OR_MATCH_ATTRIB";
   public static final String ER_CANT_RESOLVE_NSPREFIX = "ER_CANT_RESOLVE_NSPREFIX";
   public static final String ER_ILLEGAL_VALUE = "ER_ILLEGAL_VALUE";
   public static final String ER_NO_OWNERDOC = "ER_NO_OWNERDOC";
   public static final String ER_ELEMTEMPLATEELEM_ERR = "ER_ELEMTEMPLATEELEM_ERR";
   public static final String ER_NULL_CHILD = "ER_NULL_CHILD";
   public static final String ER_NEED_SELECT_ATTRIB = "ER_NEED_SELECT_ATTRIB";
   public static final String ER_NEED_TEST_ATTRIB = "ER_NEED_TEST_ATTRIB";
   public static final String ER_NEED_NAME_ATTRIB = "ER_NEED_NAME_ATTRIB";
   public static final String ER_NO_CONTEXT_OWNERDOC = "ER_NO_CONTEXT_OWNERDOC";
   public static final String ER_COULD_NOT_CREATE_XML_PROC_LIAISON = "ER_COULD_NOT_CREATE_XML_PROC_LIAISON";
   public static final String ER_PROCESS_NOT_SUCCESSFUL = "ER_PROCESS_NOT_SUCCESSFUL";
   public static final String ER_NOT_SUCCESSFUL = "ER_NOT_SUCCESSFUL";
   public static final String ER_ENCODING_NOT_SUPPORTED = "ER_ENCODING_NOT_SUPPORTED";
   public static final String ER_COULD_NOT_CREATE_TRACELISTENER = "ER_COULD_NOT_CREATE_TRACELISTENER";
   public static final String ER_KEY_REQUIRES_NAME_ATTRIB = "ER_KEY_REQUIRES_NAME_ATTRIB";
   public static final String ER_KEY_REQUIRES_MATCH_ATTRIB = "ER_KEY_REQUIRES_MATCH_ATTRIB";
   public static final String ER_KEY_REQUIRES_USE_ATTRIB = "ER_KEY_REQUIRES_USE_ATTRIB";
   public static final String ER_REQUIRES_ELEMENTS_ATTRIB = "ER_REQUIRES_ELEMENTS_ATTRIB";
   public static final String ER_MISSING_PREFIX_ATTRIB = "ER_MISSING_PREFIX_ATTRIB";
   public static final String ER_BAD_STYLESHEET_URL = "ER_BAD_STYLESHEET_URL";
   public static final String ER_FILE_NOT_FOUND = "ER_FILE_NOT_FOUND";
   public static final String ER_IOEXCEPTION = "ER_IOEXCEPTION";
   public static final String ER_NO_HREF_ATTRIB = "ER_NO_HREF_ATTRIB";
   public static final String ER_STYLESHEET_INCLUDES_ITSELF = "ER_STYLESHEET_INCLUDES_ITSELF";
   public static final String ER_PROCESSINCLUDE_ERROR = "ER_PROCESSINCLUDE_ERROR";
   public static final String ER_MISSING_LANG_ATTRIB = "ER_MISSING_LANG_ATTRIB";
   public static final String ER_MISSING_CONTAINER_ELEMENT_COMPONENT = "ER_MISSING_CONTAINER_ELEMENT_COMPONENT";
   public static final String ER_CAN_ONLY_OUTPUT_TO_ELEMENT = "ER_CAN_ONLY_OUTPUT_TO_ELEMENT";
   public static final String ER_PROCESS_ERROR = "ER_PROCESS_ERROR";
   public static final String ER_UNIMPLNODE_ERROR = "ER_UNIMPLNODE_ERROR";
   public static final String ER_NO_SELECT_EXPRESSION = "ER_NO_SELECT_EXPRESSION";
   public static final String ER_CANNOT_SERIALIZE_XSLPROCESSOR = "ER_CANNOT_SERIALIZE_XSLPROCESSOR";
   public static final String ER_NO_INPUT_STYLESHEET = "ER_NO_INPUT_STYLESHEET";
   public static final String ER_FAILED_PROCESS_STYLESHEET = "ER_FAILED_PROCESS_STYLESHEET";
   public static final String ER_COULDNT_PARSE_DOC = "ER_COULDNT_PARSE_DOC";
   public static final String ER_COULDNT_FIND_FRAGMENT = "ER_COULDNT_FIND_FRAGMENT";
   public static final String ER_NODE_NOT_ELEMENT = "ER_NODE_NOT_ELEMENT";
   public static final String ER_FOREACH_NEED_MATCH_OR_NAME_ATTRIB = "ER_FOREACH_NEED_MATCH_OR_NAME_ATTRIB";
   public static final String ER_TEMPLATES_NEED_MATCH_OR_NAME_ATTRIB = "ER_TEMPLATES_NEED_MATCH_OR_NAME_ATTRIB";
   public static final String ER_NO_CLONE_OF_DOCUMENT_FRAG = "ER_NO_CLONE_OF_DOCUMENT_FRAG";
   public static final String ER_CANT_CREATE_ITEM = "ER_CANT_CREATE_ITEM";
   public static final String ER_XMLSPACE_ILLEGAL_VALUE = "ER_XMLSPACE_ILLEGAL_VALUE";
   public static final String ER_NO_XSLKEY_DECLARATION = "ER_NO_XSLKEY_DECLARATION";
   public static final String ER_CANT_CREATE_URL = "ER_CANT_CREATE_URL";
   public static final String ER_XSLFUNCTIONS_UNSUPPORTED = "ER_XSLFUNCTIONS_UNSUPPORTED";
   public static final String ER_PROCESSOR_ERROR = "ER_PROCESSOR_ERROR";
   public static final String ER_NOT_ALLOWED_INSIDE_STYLESHEET = "ER_NOT_ALLOWED_INSIDE_STYLESHEET";
   public static final String ER_RESULTNS_NOT_SUPPORTED = "ER_RESULTNS_NOT_SUPPORTED";
   public static final String ER_DEFAULTSPACE_NOT_SUPPORTED = "ER_DEFAULTSPACE_NOT_SUPPORTED";
   public static final String ER_INDENTRESULT_NOT_SUPPORTED = "ER_INDENTRESULT_NOT_SUPPORTED";
   public static final String ER_ILLEGAL_ATTRIB = "ER_ILLEGAL_ATTRIB";
   public static final String ER_UNKNOWN_XSL_ELEM = "ER_UNKNOWN_XSL_ELEM";
   public static final String ER_BAD_XSLSORT_USE = "ER_BAD_XSLSORT_USE";
   public static final String ER_MISPLACED_XSLWHEN = "ER_MISPLACED_XSLWHEN";
   public static final String ER_XSLWHEN_NOT_PARENTED_BY_XSLCHOOSE = "ER_XSLWHEN_NOT_PARENTED_BY_XSLCHOOSE";
   public static final String ER_MISPLACED_XSLOTHERWISE = "ER_MISPLACED_XSLOTHERWISE";
   public static final String ER_XSLOTHERWISE_NOT_PARENTED_BY_XSLCHOOSE = "ER_XSLOTHERWISE_NOT_PARENTED_BY_XSLCHOOSE";
   public static final String ER_NOT_ALLOWED_INSIDE_TEMPLATE = "ER_NOT_ALLOWED_INSIDE_TEMPLATE";
   public static final String ER_UNKNOWN_EXT_NS_PREFIX = "ER_UNKNOWN_EXT_NS_PREFIX";
   public static final String ER_IMPORTS_AS_FIRST_ELEM = "ER_IMPORTS_AS_FIRST_ELEM";
   public static final String ER_IMPORTING_ITSELF = "ER_IMPORTING_ITSELF";
   public static final String ER_XMLSPACE_ILLEGAL_VAL = "ER_XMLSPACE_ILLEGAL_VAL";
   public static final String ER_PROCESSSTYLESHEET_NOT_SUCCESSFUL = "ER_PROCESSSTYLESHEET_NOT_SUCCESSFUL";
   public static final String ER_SAX_EXCEPTION = "ER_SAX_EXCEPTION";
   public static final String ER_XSLT_ERROR = "ER_XSLT_ERROR";
   public static final String ER_CURRENCY_SIGN_ILLEGAL = "ER_CURRENCY_SIGN_ILLEGAL";
   public static final String ER_DOCUMENT_FUNCTION_INVALID_IN_STYLESHEET_DOM = "ER_DOCUMENT_FUNCTION_INVALID_IN_STYLESHEET_DOM";
   public static final String ER_CANT_RESOLVE_PREFIX_OF_NON_PREFIX_RESOLVER = "ER_CANT_RESOLVE_PREFIX_OF_NON_PREFIX_RESOLVER";
   public static final String ER_REDIRECT_COULDNT_GET_FILENAME = "ER_REDIRECT_COULDNT_GET_FILENAME";
   public static final String ER_CANNOT_BUILD_FORMATTERLISTENER_IN_REDIRECT = "ER_CANNOT_BUILD_FORMATTERLISTENER_IN_REDIRECT";
   public static final String ER_INVALID_PREFIX_IN_EXCLUDERESULTPREFIX = "ER_INVALID_PREFIX_IN_EXCLUDERESULTPREFIX";
   public static final String ER_MISSING_NS_URI = "ER_MISSING_NS_URI";
   public static final String ER_MISSING_ARG_FOR_OPTION = "ER_MISSING_ARG_FOR_OPTION";
   public static final String ER_INVALID_OPTION = "ER_INVALID_OPTION";
   public static final String ER_MALFORMED_FORMAT_STRING = "ER_MALFORMED_FORMAT_STRING";
   public static final String ER_STYLESHEET_REQUIRES_VERSION_ATTRIB = "ER_STYLESHEET_REQUIRES_VERSION_ATTRIB";
   public static final String ER_ILLEGAL_ATTRIBUTE_VALUE = "ER_ILLEGAL_ATTRIBUTE_VALUE";
   public static final String ER_CHOOSE_REQUIRES_WHEN = "ER_CHOOSE_REQUIRES_WHEN";
   public static final String ER_NO_APPLY_IMPORT_IN_FOR_EACH = "ER_NO_APPLY_IMPORT_IN_FOR_EACH";
   public static final String ER_CANT_USE_DTM_FOR_OUTPUT = "ER_CANT_USE_DTM_FOR_OUTPUT";
   public static final String ER_CANT_USE_DTM_FOR_INPUT = "ER_CANT_USE_DTM_FOR_INPUT";
   public static final String ER_CALL_TO_EXT_FAILED = "ER_CALL_TO_EXT_FAILED";
   public static final String ER_PREFIX_MUST_RESOLVE = "ER_PREFIX_MUST_RESOLVE";
   public static final String ER_INVALID_UTF16_SURROGATE = "ER_INVALID_UTF16_SURROGATE";
   public static final String ER_XSLATTRSET_USED_ITSELF = "ER_XSLATTRSET_USED_ITSELF";
   public static final String ER_CANNOT_MIX_XERCESDOM = "ER_CANNOT_MIX_XERCESDOM";
   public static final String ER_TOO_MANY_LISTENERS = "ER_TOO_MANY_LISTENERS";
   public static final String ER_IN_ELEMTEMPLATEELEM_READOBJECT = "ER_IN_ELEMTEMPLATEELEM_READOBJECT";
   public static final String ER_DUPLICATE_NAMED_TEMPLATE = "ER_DUPLICATE_NAMED_TEMPLATE";
   public static final String ER_INVALID_KEY_CALL = "ER_INVALID_KEY_CALL";
   public static final String ER_REFERENCING_ITSELF = "ER_REFERENCING_ITSELF";
   public static final String ER_ILLEGAL_DOMSOURCE_INPUT = "ER_ILLEGAL_DOMSOURCE_INPUT";
   public static final String ER_CLASS_NOT_FOUND_FOR_OPTION = "ER_CLASS_NOT_FOUND_FOR_OPTION";
   public static final String ER_REQUIRED_ELEM_NOT_FOUND = "ER_REQUIRED_ELEM_NOT_FOUND";
   public static final String ER_INPUT_CANNOT_BE_NULL = "ER_INPUT_CANNOT_BE_NULL";
   public static final String ER_URI_CANNOT_BE_NULL = "ER_URI_CANNOT_BE_NULL";
   public static final String ER_FILE_CANNOT_BE_NULL = "ER_FILE_CANNOT_BE_NULL";
   public static final String ER_SOURCE_CANNOT_BE_NULL = "ER_SOURCE_CANNOT_BE_NULL";
   public static final String ER_CANNOT_INIT_BSFMGR = "ER_CANNOT_INIT_BSFMGR";
   public static final String ER_CANNOT_CMPL_EXTENSN = "ER_CANNOT_CMPL_EXTENSN";
   public static final String ER_CANNOT_CREATE_EXTENSN = "ER_CANNOT_CREATE_EXTENSN";
   public static final String ER_INSTANCE_MTHD_CALL_REQUIRES = "ER_INSTANCE_MTHD_CALL_REQUIRES";
   public static final String ER_INVALID_ELEMENT_NAME = "ER_INVALID_ELEMENT_NAME";
   public static final String ER_ELEMENT_NAME_METHOD_STATIC = "ER_ELEMENT_NAME_METHOD_STATIC";
   public static final String ER_EXTENSION_FUNC_UNKNOWN = "ER_EXTENSION_FUNC_UNKNOWN";
   public static final String ER_MORE_MATCH_CONSTRUCTOR = "ER_MORE_MATCH_CONSTRUCTOR";
   public static final String ER_MORE_MATCH_METHOD = "ER_MORE_MATCH_METHOD";
   public static final String ER_MORE_MATCH_ELEMENT = "ER_MORE_MATCH_ELEMENT";
   public static final String ER_INVALID_CONTEXT_PASSED = "ER_INVALID_CONTEXT_PASSED";
   public static final String ER_POOL_EXISTS = "ER_POOL_EXISTS";
   public static final String ER_NO_DRIVER_NAME = "ER_NO_DRIVER_NAME";
   public static final String ER_NO_URL = "ER_NO_URL";
   public static final String ER_POOL_SIZE_LESSTHAN_ONE = "ER_POOL_SIZE_LESSTHAN_ONE";
   public static final String ER_INVALID_DRIVER = "ER_INVALID_DRIVER";
   public static final String ER_NO_STYLESHEETROOT = "ER_NO_STYLESHEETROOT";
   public static final String ER_ILLEGAL_XMLSPACE_VALUE = "ER_ILLEGAL_XMLSPACE_VALUE";
   public static final String ER_PROCESSFROMNODE_FAILED = "ER_PROCESSFROMNODE_FAILED";
   public static final String ER_RESOURCE_COULD_NOT_LOAD = "ER_RESOURCE_COULD_NOT_LOAD";
   public static final String ER_BUFFER_SIZE_LESSTHAN_ZERO = "ER_BUFFER_SIZE_LESSTHAN_ZERO";
   public static final String ER_UNKNOWN_ERROR_CALLING_EXTENSION = "ER_UNKNOWN_ERROR_CALLING_EXTENSION";
   public static final String ER_NO_NAMESPACE_DECL = "ER_NO_NAMESPACE_DECL";
   public static final String ER_ELEM_CONTENT_NOT_ALLOWED = "ER_ELEM_CONTENT_NOT_ALLOWED";
   public static final String ER_STYLESHEET_DIRECTED_TERMINATION = "ER_STYLESHEET_DIRECTED_TERMINATION";
   public static final String ER_ONE_OR_TWO = "ER_ONE_OR_TWO";
   public static final String ER_TWO_OR_THREE = "ER_TWO_OR_THREE";
   public static final String ER_COULD_NOT_LOAD_RESOURCE = "ER_COULD_NOT_LOAD_RESOURCE";
   public static final String ER_CANNOT_INIT_DEFAULT_TEMPLATES = "ER_CANNOT_INIT_DEFAULT_TEMPLATES";
   public static final String ER_RESULT_NULL = "ER_RESULT_NULL";
   public static final String ER_RESULT_COULD_NOT_BE_SET = "ER_RESULT_COULD_NOT_BE_SET";
   public static final String ER_NO_OUTPUT_SPECIFIED = "ER_NO_OUTPUT_SPECIFIED";
   public static final String ER_CANNOT_TRANSFORM_TO_RESULT_TYPE = "ER_CANNOT_TRANSFORM_TO_RESULT_TYPE";
   public static final String ER_CANNOT_TRANSFORM_SOURCE_TYPE = "ER_CANNOT_TRANSFORM_SOURCE_TYPE";
   public static final String ER_NULL_CONTENT_HANDLER = "ER_NULL_CONTENT_HANDLER";
   public static final String ER_NULL_ERROR_HANDLER = "ER_NULL_ERROR_HANDLER";
   public static final String ER_CANNOT_CALL_PARSE = "ER_CANNOT_CALL_PARSE";
   public static final String ER_NO_PARENT_FOR_FILTER = "ER_NO_PARENT_FOR_FILTER";
   public static final String ER_NO_STYLESHEET_IN_MEDIA = "ER_NO_STYLESHEET_IN_MEDIA";
   public static final String ER_NO_STYLESHEET_PI = "ER_NO_STYLESHEET_PI";
   public static final String ER_NOT_SUPPORTED = "ER_NOT_SUPPORTED";
   public static final String ER_PROPERTY_VALUE_BOOLEAN = "ER_PROPERTY_VALUE_BOOLEAN";
   public static final String ER_COULD_NOT_FIND_EXTERN_SCRIPT = "ER_COULD_NOT_FIND_EXTERN_SCRIPT";
   public static final String ER_RESOURCE_COULD_NOT_FIND = "ER_RESOURCE_COULD_NOT_FIND";
   public static final String ER_OUTPUT_PROPERTY_NOT_RECOGNIZED = "ER_OUTPUT_PROPERTY_NOT_RECOGNIZED";
   public static final String ER_FAILED_CREATING_ELEMLITRSLT = "ER_FAILED_CREATING_ELEMLITRSLT";
   public static final String ER_VALUE_SHOULD_BE_NUMBER = "ER_VALUE_SHOULD_BE_NUMBER";
   public static final String ER_VALUE_SHOULD_EQUAL = "ER_VALUE_SHOULD_EQUAL";
   public static final String ER_FAILED_CALLING_METHOD = "ER_FAILED_CALLING_METHOD";
   public static final String ER_FAILED_CREATING_ELEMTMPL = "ER_FAILED_CREATING_ELEMTMPL";
   public static final String ER_CHARS_NOT_ALLOWED = "ER_CHARS_NOT_ALLOWED";
   public static final String ER_ATTR_NOT_ALLOWED = "ER_ATTR_NOT_ALLOWED";
   public static final String ER_BAD_VALUE = "ER_BAD_VALUE";
   public static final String ER_ATTRIB_VALUE_NOT_FOUND = "ER_ATTRIB_VALUE_NOT_FOUND";
   public static final String ER_ATTRIB_VALUE_NOT_RECOGNIZED = "ER_ATTRIB_VALUE_NOT_RECOGNIZED";
   public static final String ER_NULL_URI_NAMESPACE = "ER_NULL_URI_NAMESPACE";
   public static final String ER_NUMBER_TOO_BIG = "ER_NUMBER_TOO_BIG";
   public static final String ER_CANNOT_FIND_SAX1_DRIVER = "ER_CANNOT_FIND_SAX1_DRIVER";
   public static final String ER_SAX1_DRIVER_NOT_LOADED = "ER_SAX1_DRIVER_NOT_LOADED";
   public static final String ER_SAX1_DRIVER_NOT_INSTANTIATED = "ER_SAX1_DRIVER_NOT_INSTANTIATED";
   public static final String ER_SAX1_DRIVER_NOT_IMPLEMENT_PARSER = "ER_SAX1_DRIVER_NOT_IMPLEMENT_PARSER";
   public static final String ER_PARSER_PROPERTY_NOT_SPECIFIED = "ER_PARSER_PROPERTY_NOT_SPECIFIED";
   public static final String ER_PARSER_ARG_CANNOT_BE_NULL = "ER_PARSER_ARG_CANNOT_BE_NULL";
   public static final String ER_FEATURE = "ER_FEATURE";
   public static final String ER_PROPERTY = "ER_PROPERTY";
   public static final String ER_NULL_ENTITY_RESOLVER = "ER_NULL_ENTITY_RESOLVER";
   public static final String ER_NULL_DTD_HANDLER = "ER_NULL_DTD_HANDLER";
   public static final String ER_NO_DRIVER_NAME_SPECIFIED = "ER_NO_DRIVER_NAME_SPECIFIED";
   public static final String ER_NO_URL_SPECIFIED = "ER_NO_URL_SPECIFIED";
   public static final String ER_POOLSIZE_LESS_THAN_ONE = "ER_POOLSIZE_LESS_THAN_ONE";
   public static final String ER_INVALID_DRIVER_NAME = "ER_INVALID_DRIVER_NAME";
   public static final String ER_ERRORLISTENER = "ER_ERRORLISTENER";
   public static final String ER_ASSERT_NO_TEMPLATE_PARENT = "ER_ASSERT_NO_TEMPLATE_PARENT";
   public static final String ER_ASSERT_REDUNDENT_EXPR_ELIMINATOR = "ER_ASSERT_REDUNDENT_EXPR_ELIMINATOR";
   public static final String ER_NOT_ALLOWED_IN_POSITION = "ER_NOT_ALLOWED_IN_POSITION";
   public static final String ER_NONWHITESPACE_NOT_ALLOWED_IN_POSITION = "ER_NONWHITESPACE_NOT_ALLOWED_IN_POSITION";
   public static final String INVALID_TCHAR = "INVALID_TCHAR";
   public static final String INVALID_QNAME = "INVALID_QNAME";
   public static final String INVALID_ENUM = "INVALID_ENUM";
   public static final String INVALID_NMTOKEN = "INVALID_NMTOKEN";
   public static final String INVALID_NCNAME = "INVALID_NCNAME";
   public static final String INVALID_BOOLEAN = "INVALID_BOOLEAN";
   public static final String INVALID_NUMBER = "INVALID_NUMBER";
   public static final String ER_ARG_LITERAL = "ER_ARG_LITERAL";
   public static final String ER_DUPLICATE_GLOBAL_VAR = "ER_DUPLICATE_GLOBAL_VAR";
   public static final String ER_DUPLICATE_VAR = "ER_DUPLICATE_VAR";
   public static final String ER_TEMPLATE_NAME_MATCH = "ER_TEMPLATE_NAME_MATCH";
   public static final String ER_INVALID_PREFIX = "ER_INVALID_PREFIX";
   public static final String ER_NO_ATTRIB_SET = "ER_NO_ATTRIB_SET";
   public static final String WG_FOUND_CURLYBRACE = "WG_FOUND_CURLYBRACE";
   public static final String WG_COUNT_ATTRIB_MATCHES_NO_ANCESTOR = "WG_COUNT_ATTRIB_MATCHES_NO_ANCESTOR";
   public static final String WG_EXPR_ATTRIB_CHANGED_TO_SELECT = "WG_EXPR_ATTRIB_CHANGED_TO_SELECT";
   public static final String WG_NO_LOCALE_IN_FORMATNUMBER = "WG_NO_LOCALE_IN_FORMATNUMBER";
   public static final String WG_LOCALE_NOT_FOUND = "WG_LOCALE_NOT_FOUND";
   public static final String WG_CANNOT_MAKE_URL_FROM = "WG_CANNOT_MAKE_URL_FROM";
   public static final String WG_CANNOT_LOAD_REQUESTED_DOC = "WG_CANNOT_LOAD_REQUESTED_DOC";
   public static final String WG_CANNOT_FIND_COLLATOR = "WG_CANNOT_FIND_COLLATOR";
   public static final String WG_FUNCTIONS_SHOULD_USE_URL = "WG_FUNCTIONS_SHOULD_USE_URL";
   public static final String WG_ENCODING_NOT_SUPPORTED_USING_UTF8 = "WG_ENCODING_NOT_SUPPORTED_USING_UTF8";
   public static final String WG_ENCODING_NOT_SUPPORTED_USING_JAVA = "WG_ENCODING_NOT_SUPPORTED_USING_JAVA";
   public static final String WG_SPECIFICITY_CONFLICTS = "WG_SPECIFICITY_CONFLICTS";
   public static final String WG_PARSING_AND_PREPARING = "WG_PARSING_AND_PREPARING";
   public static final String WG_ATTR_TEMPLATE = "WG_ATTR_TEMPLATE";
   public static final String WG_CONFLICT_BETWEEN_XSLSTRIPSPACE_AND_XSLPRESERVESPACE = "WG_CONFLICT_BETWEEN_XSLSTRIPSPACE_AND_XSLPRESERVESP";
   public static final String WG_ATTRIB_NOT_HANDLED = "WG_ATTRIB_NOT_HANDLED";
   public static final String WG_NO_DECIMALFORMAT_DECLARATION = "WG_NO_DECIMALFORMAT_DECLARATION";
   public static final String WG_OLD_XSLT_NS = "WG_OLD_XSLT_NS";
   public static final String WG_ONE_DEFAULT_XSLDECIMALFORMAT_ALLOWED = "WG_ONE_DEFAULT_XSLDECIMALFORMAT_ALLOWED";
   public static final String WG_XSLDECIMALFORMAT_NAMES_MUST_BE_UNIQUE = "WG_XSLDECIMALFORMAT_NAMES_MUST_BE_UNIQUE";
   public static final String WG_ILLEGAL_ATTRIBUTE = "WG_ILLEGAL_ATTRIBUTE";
   public static final String WG_COULD_NOT_RESOLVE_PREFIX = "WG_COULD_NOT_RESOLVE_PREFIX";
   public static final String WG_STYLESHEET_REQUIRES_VERSION_ATTRIB = "WG_STYLESHEET_REQUIRES_VERSION_ATTRIB";
   public static final String WG_ILLEGAL_ATTRIBUTE_NAME = "WG_ILLEGAL_ATTRIBUTE_NAME";
   public static final String WG_ILLEGAL_ATTRIBUTE_VALUE = "WG_ILLEGAL_ATTRIBUTE_VALUE";
   public static final String WG_EMPTY_SECOND_ARG = "WG_EMPTY_SECOND_ARG";
   public static final String WG_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML = "WG_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML";
   public static final String WG_PROCESSINGINSTRUCTION_NOTVALID_NCNAME = "WG_PROCESSINGINSTRUCTION_NOTVALID_NCNAME";
   public static final String WG_ILLEGAL_ATTRIBUTE_POSITION = "WG_ILLEGAL_ATTRIBUTE_POSITION";
   public static final String BAD_CODE = "HATALI_KOD";
   public static final String FORMAT_FAILED = "BİÇİMLEME_BAŞARISIZ";
   public static final String ERROR_STRING = "#hata";
   public static final String ERROR_HEADER = "Hata: ";
   public static final String WARNING_HEADER = "Uyarı: ";
   public static final String XSL_HEADER = "XSLT ";
   public static final String XML_HEADER = "XML ";
   /** @deprecated */
   public static final String QUERY_HEADER = "ÖRÜNTÜ ";

   public Object[][] getContents() {
      return new Object[][]{{"ER0000", "{0}"}, {"ER_NO_CURLYBRACE", "Hata: İfade içinde '{' olamaz"}, {"ER_ILLEGAL_ATTRIBUTE", "{0} geçersiz {1} özniteliğini içeriyor"}, {"ER_NULL_SOURCENODE_APPLYIMPORTS", "xsl:apply-imports içinde sourceNode boş değerli!"}, {"ER_CANNOT_ADD", "{0}, {1} içine eklenemiyor"}, {"ER_NULL_SOURCENODE_HANDLEAPPLYTEMPLATES", "handleApplyTemplatesInstruction içinde sourceNode boş değerli!"}, {"ER_NO_NAME_ATTRIB", "{0} için öznitelik belirtilmeli."}, {"ER_TEMPLATE_NOT_FOUND", "Adı {0} olan şablon bulunamadı"}, {"ER_CANT_RESOLVE_NAME_AVT", "xsl:call-template içinde AVT adı çözülemedi."}, {"ER_REQUIRES_ATTRIB", "{0} için {1} özniteliği gerekiyor."}, {"ER_MUST_HAVE_TEST_ATTRIB", "{0} için ''test'' özniteliği gerekiyor."}, {"ER_BAD_VAL_ON_LEVEL_ATTRIB", "{0} düzey özniteliğinde hatalı değer."}, {"ER_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML", "processing-instruction adı 'xml' olamaz"}, {"ER_PROCESSINGINSTRUCTION_NOTVALID_NCNAME", "processing-instruction adı geçerli bir NCName olmalıdır: {0}"}, {"ER_NEED_MATCH_ATTRIB", "{0} kip içeriyorsa match özniteliği olması gerekir."}, {"ER_NEED_NAME_OR_MATCH_ATTRIB", "{0} için name ya da match özniteliği gerekiyor."}, {"ER_CANT_RESOLVE_NSPREFIX", "Ad alanı öneki {0} çözülemiyor."}, {"ER_ILLEGAL_VALUE", "xml:space geçersiz {0} değerini içeriyor."}, {"ER_NO_OWNERDOC", "Alt düğümün iye belgesi yok!"}, {"ER_ELEMTEMPLATEELEM_ERR", "ElemTemplateElement hatası: {0}"}, {"ER_NULL_CHILD", "Boş değerli (null) alt öğe ekleme girişimi!"}, {"ER_NEED_SELECT_ATTRIB", "{0} için select özniteliği gerekiyor."}, {"ER_NEED_TEST_ATTRIB", "xsl:when için 'test' özniteliği gereklidir."}, {"ER_NEED_NAME_ATTRIB", "xsl:with-param için 'name' özniteliği gereklidir."}, {"ER_NO_CONTEXT_OWNERDOC", "Bağlamın iye belgesi yok!"}, {"ER_COULD_NOT_CREATE_XML_PROC_LIAISON", "XML TransformerFactory ilişkisi {0} yaratılamadı"}, {"ER_PROCESS_NOT_SUCCESSFUL", "Xalan: Process başarılı olmadı."}, {"ER_NOT_SUCCESSFUL", "Xalan: başarılı olmadı."}, {"ER_ENCODING_NOT_SUPPORTED", "{0} kodlaması desteklenmiyor."}, {"ER_COULD_NOT_CREATE_TRACELISTENER", "TraceListener {0} yaratılamadı."}, {"ER_KEY_REQUIRES_NAME_ATTRIB", "xsl:key için 'name' özniteliği gerekiyor!"}, {"ER_KEY_REQUIRES_MATCH_ATTRIB", "xsl:key için 'match' özniteliği gerekiyor!"}, {"ER_KEY_REQUIRES_USE_ATTRIB", "xsl:key için 'use' özniteliği gerekiyor!"}, {"ER_REQUIRES_ELEMENTS_ATTRIB", "(StylesheetHandler) {0} için ''elements'' özniteliği gerekiyor!"}, {"ER_MISSING_PREFIX_ATTRIB", "(StylesheetHandler) {0} özniteliği ''prefix'' eksik"}, {"ER_BAD_STYLESHEET_URL", "Biçem yaprağı URL adresi {0} geçersiz"}, {"ER_FILE_NOT_FOUND", "Biçem yaprağı dosyası bulunamadı: {0}"}, {"ER_IOEXCEPTION", "Biçem yaprağı dosyası {0} ile GÇ kural dışı durumu oluştu"}, {"ER_NO_HREF_ATTRIB", "(StylesheetHandler) {0} için href özniteliği bulunamadı"}, {"ER_STYLESHEET_INCLUDES_ITSELF", "(StylesheetHandler) {0} doğrudan ya da dolaylı olarak kendisini içeriyor!"}, {"ER_PROCESSINCLUDE_ERROR", "StylesheetHandler.processInclude hatası, {0}"}, {"ER_MISSING_LANG_ATTRIB", "(StylesheetHandler) {0} özniteliği ''lang'' eksik"}, {"ER_MISSING_CONTAINER_ELEMENT_COMPONENT", "(StylesheetHandler) {0} öğesinin yeri yanlış? taşıyıcı öğesi ''component'' eksik"}, {"ER_CAN_ONLY_OUTPUT_TO_ELEMENT", "Çıkış yalnızca şunlara yöneltilebilir: Element, DocumentFragment, Document ya da PrintWriter."}, {"ER_PROCESS_ERROR", "StylesheetRoot.process hatası"}, {"ER_UNIMPLNODE_ERROR", "UnImplNode hatası: {0}"}, {"ER_NO_SELECT_EXPRESSION", "Hata! xpath select ifadesi (-select) bulunamadı."}, {"ER_CANNOT_SERIALIZE_XSLPROCESSOR", "XSLProcessor diziselleştirilemez!"}, {"ER_NO_INPUT_STYLESHEET", "Biçem yaprağı girişi belirtilmedi!"}, {"ER_FAILED_PROCESS_STYLESHEET", "Biçem yaprağı işlenemedi!"}, {"ER_COULDNT_PARSE_DOC", "{0} belgesi ayrıştırılamadı!"}, {"ER_COULDNT_FIND_FRAGMENT", "Parça bulunamadı: {0}"}, {"ER_NODE_NOT_ELEMENT", "Parça tanıtıcısının gösterdiği düğüm bir öğe değildi: {0}"}, {"ER_FOREACH_NEED_MATCH_OR_NAME_ATTRIB", "for-each için eşleşme ya da ad özniteliği gerekir"}, {"ER_TEMPLATES_NEED_MATCH_OR_NAME_ATTRIB", "templates için eşleşme ya da ad özniteliği gerekir"}, {"ER_NO_CLONE_OF_DOCUMENT_FRAG", "Belge parçasının eşkopyası değil!"}, {"ER_CANT_CREATE_ITEM", "Sonuç ağacında öğe yaratılamıyor: {0}"}, {"ER_XMLSPACE_ILLEGAL_VALUE", "Kaynak XML içinde xml:space geçersiz değer içeriyor: {0}"}, {"ER_NO_XSLKEY_DECLARATION", "{0} için xsl:key bildirimi yok!"}, {"ER_CANT_CREATE_URL", "Hata! İlgili url yaratılamıyor: {0}"}, {"ER_XSLFUNCTIONS_UNSUPPORTED", "xsl:functions desteklenmiyor"}, {"ER_PROCESSOR_ERROR", "XSLT TransformerFactory Hatası"}, {"ER_NOT_ALLOWED_INSIDE_STYLESHEET", "(StylesheetHandler) {0} biçem yaprağı içinde olamaz!"}, {"ER_RESULTNS_NOT_SUPPORTED", "result-ns artık desteklenmiyor! Yerine xsl:output kullanın."}, {"ER_DEFAULTSPACE_NOT_SUPPORTED", "default-space artık desteklenmiyor!  Yerine xsl:strip-space ya da xsl:preserve-space kullanın."}, {"ER_INDENTRESULT_NOT_SUPPORTED", "indent-result artık desteklenmiyor!  Yerine xsl:output kullanın."}, {"ER_ILLEGAL_ATTRIB", "(StylesheetHandler) {0} geçersiz {1} özniteliğini içeriyor"}, {"ER_UNKNOWN_XSL_ELEM", "Bilinmeyen XSL öğesi: {0}"}, {"ER_BAD_XSLSORT_USE", "(StylesheetHandler) xsl:sort yalnızca xsl:apply-templates ya da xsl:for-each ile kullanılabilir."}, {"ER_MISPLACED_XSLWHEN", "(StylesheetHandler) xsl:when yeri yanlış!"}, {"ER_XSLWHEN_NOT_PARENTED_BY_XSLCHOOSE", "(StylesheetHandler) xsl:when öğesinin üst öğesi xsl:choose değil!"}, {"ER_MISPLACED_XSLOTHERWISE", "(StylesheetHandler) xsl:otherwise yeri yanlış!"}, {"ER_XSLOTHERWISE_NOT_PARENTED_BY_XSLCHOOSE", "(StylesheetHandler) xsl:otherwise öğesinin üst öğesi xsl:choose değil!"}, {"ER_NOT_ALLOWED_INSIDE_TEMPLATE", "(StylesheetHandler) {0} şablon içinde kullanılamaz!"}, {"ER_UNKNOWN_EXT_NS_PREFIX", "(StylesheetHandler) {0} eklenti ad alanı öneki {1} bilinmiyor"}, {"ER_IMPORTS_AS_FIRST_ELEM", "(StylesheetHandler) Import öğeleri, biçem yaprağının ilk öğeleri olarak geçebilir!"}, {"ER_IMPORTING_ITSELF", "(StylesheetHandler) {0} doğrudan ya da dolaylı olarak kendisini içe aktarıyor!"}, {"ER_XMLSPACE_ILLEGAL_VAL", "(StylesheetHandler) xml:space geçersiz {0} değerini içeriyor"}, {"ER_PROCESSSTYLESHEET_NOT_SUCCESSFUL", "processStylesheet başarısız oldu!"}, {"ER_SAX_EXCEPTION", "SAX kural dışı durumu"}, {"ER_XSLT_ERROR", "XSLT hatası"}, {"ER_CURRENCY_SIGN_ILLEGAL", "Biçim örüntüsü dizgisinde para birimi simgesi olamaz"}, {"ER_DOCUMENT_FUNCTION_INVALID_IN_STYLESHEET_DOM", "Stylesheet DOM belge işlevini desteklemiyor!"}, {"ER_CANT_RESOLVE_PREFIX_OF_NON_PREFIX_RESOLVER", "Önek dışı çözücünün öneki çözülemez."}, {"ER_REDIRECT_COULDNT_GET_FILENAME", "Yeniden yönlendirme eklentisi: Dosya adı alınamadı - file ya da select özniteliği geçerli bir dizgi döndürmelidir."}, {"ER_CANNOT_BUILD_FORMATTERLISTENER_IN_REDIRECT", "Yeniden yönlendirme eklentisinde FormatterListener oluşturulamadı!"}, {"ER_INVALID_PREFIX_IN_EXCLUDERESULTPREFIX", "exclude-result-prefixes içindeki önek geçerli değil: {0}"}, {"ER_MISSING_NS_URI", "Belirtilen önek için ad alanı URI eksik"}, {"ER_MISSING_ARG_FOR_OPTION", "{0} seçeneği için bağımsız değişken eksik"}, {"ER_INVALID_OPTION", "Geçersiz seçenek: {0}"}, {"ER_MALFORMED_FORMAT_STRING", "Bozuk biçimli biçim dizgisi: {0}"}, {"ER_STYLESHEET_REQUIRES_VERSION_ATTRIB", "xsl:stylesheet için 'version' özniteliği gerekiyor!"}, {"ER_ILLEGAL_ATTRIBUTE_VALUE", "{0} özniteliği geçersiz {1} değerini içeriyor"}, {"ER_CHOOSE_REQUIRES_WHEN", "xsl:choose için xsl:when gerekiyor"}, {"ER_NO_APPLY_IMPORT_IN_FOR_EACH", "xsl:apply-imports, xsl:for-each içinde kullanılamaz"}, {"ER_CANT_USE_DTM_FOR_OUTPUT", "Çıkış DOM düğümü için DTMLiaison kullanılamaz... onun yerine org.apache.xpath.DOM2Helper aktarın!"}, {"ER_CANT_USE_DTM_FOR_INPUT", "Giriş DOM düğümü için DTMLiaison kullanılamaz... onun yerine org.apache.xpath.DOM2Helper aktarın!"}, {"ER_CALL_TO_EXT_FAILED", "Eklenti öğesine çağrı başarısız oldu: {0}"}, {"ER_PREFIX_MUST_RESOLVE", "Önek bir ad alanına çözülmelidir: {0}"}, {"ER_INVALID_UTF16_SURROGATE", "UTF-16 yerine kullanılan değer geçersiz: {0} ?"}, {"ER_XSLATTRSET_USED_ITSELF", "xsl:attribute-set {0} kendisini kullandı, sonsuz döngü oluşacak."}, {"ER_CANNOT_MIX_XERCESDOM", "Xerces-DOM dışı giriş Xerces-DOM çıkışla birleştirilemez!"}, {"ER_TOO_MANY_LISTENERS", "addTraceListenersToStylesheet - TooManyListenersException"}, {"ER_IN_ELEMTEMPLATEELEM_READOBJECT", "ElemTemplateElement.readObject içinde: {0}"}, {"ER_DUPLICATE_NAMED_TEMPLATE", "Bu adı taşıyan birden çok şablon saptandı: {0}"}, {"ER_INVALID_KEY_CALL", "Geçersiz işlev çağrısı: Özyineli key() çağrılarına izin verilmez"}, {"ER_REFERENCING_ITSELF", "{0} değişkeni doğrudan ya da dolaylı olarak kendisine başvuruda bulunuyor!"}, {"ER_ILLEGAL_DOMSOURCE_INPUT", "newTemplates ile ilgili DOMSource için giriş düğümü boş değerli olamaz!"}, {"ER_CLASS_NOT_FOUND_FOR_OPTION", "{0} seçeneği için sınıf dosyası bulunamadı"}, {"ER_REQUIRED_ELEM_NOT_FOUND", "Gerekli öğe bulunamadı: {0}"}, {"ER_INPUT_CANNOT_BE_NULL", "InputStream boş değerli olamaz"}, {"ER_URI_CANNOT_BE_NULL", "URI boş değerli olamaz"}, {"ER_FILE_CANNOT_BE_NULL", "Dosya boş değerli olamaz"}, {"ER_SOURCE_CANNOT_BE_NULL", "InputSource boş değerli olamaz"}, {"ER_CANNOT_INIT_BSFMGR", "BSF Manager kullanıma hazırlanamadı"}, {"ER_CANNOT_CMPL_EXTENSN", "Eklenti derlenemedi"}, {"ER_CANNOT_CREATE_EXTENSN", "Eklenti yaratılamadı: {0} nedeni: {1}"}, {"ER_INSTANCE_MTHD_CALL_REQUIRES", "{0} yöntemine yönelik Instance yöntemi, birincil bağımsız değişkenin somutlaşan nesne örneği olmasını gerektirir"}, {"ER_INVALID_ELEMENT_NAME", "Belirtilen öğe adı geçersiz {0}"}, {"ER_ELEMENT_NAME_METHOD_STATIC", "Öğe adı yöntemi durağan {0} olmalı"}, {"ER_EXTENSION_FUNC_UNKNOWN", "Eklenti işlevi {0} : {1} bilinmiyor"}, {"ER_MORE_MATCH_CONSTRUCTOR", "{0} ile ilgili oluşturucu için en iyi eşleşme sayısı birden çok"}, {"ER_MORE_MATCH_METHOD", "{0} yöntemi için en iyi eşleşme sayısı birden çok"}, {"ER_MORE_MATCH_ELEMENT", "{0} öğe yöntemi için en iyi eşleşme sayısı birden çok"}, {"ER_INVALID_CONTEXT_PASSED", "{0} değerlendirmesi için geçersiz bağlam aktarıldı"}, {"ER_POOL_EXISTS", "Havuz zaten var"}, {"ER_NO_DRIVER_NAME", "Sürücü adı belirtilmedi"}, {"ER_NO_URL", "URL belirtilmedi"}, {"ER_POOL_SIZE_LESSTHAN_ONE", "Havuz büyüklüğü birden az!"}, {"ER_INVALID_DRIVER", "Belirtilen sürücü adı geçersiz!"}, {"ER_NO_STYLESHEETROOT", "Biçem yaprağı kökü bulunamadı!"}, {"ER_ILLEGAL_XMLSPACE_VALUE", "xml:space için geçersiz değer"}, {"ER_PROCESSFROMNODE_FAILED", "processFromNode başarısız oldu"}, {"ER_RESOURCE_COULD_NOT_LOAD", "Kaynak [ {0} ] yükleyemedi: {1} \n {2} \t {3}"}, {"ER_BUFFER_SIZE_LESSTHAN_ZERO", "Arabellek büyüklüğü <=0"}, {"ER_UNKNOWN_ERROR_CALLING_EXTENSION", "Eklenti çağrılırken bilinmeyen hata"}, {"ER_NO_NAMESPACE_DECL", "{0} önekinin ilişkili bir ad alanı bildirimi yok"}, {"ER_ELEM_CONTENT_NOT_ALLOWED", "lang=javaclass {0} için öğe içeriğine izin verilmiyor"}, {"ER_STYLESHEET_DIRECTED_TERMINATION", "Biçem yaprağı yönlendirmeli sonlandırma"}, {"ER_ONE_OR_TWO", "1 ya da 2"}, {"ER_TWO_OR_THREE", "2 ya da 3"}, {"ER_COULD_NOT_LOAD_RESOURCE", "{0} yüklenemedi (CLASSPATH değişkenini inceleyin), yalnızca varsayılanlar kullanılıyor"}, {"ER_CANNOT_INIT_DEFAULT_TEMPLATES", "Varsayılan şablonlar kullanıma hazırlanamıyor"}, {"ER_RESULT_NULL", "Sonuç boş değerli olmamalı"}, {"ER_RESULT_COULD_NOT_BE_SET", "Sonuç tanımlanamadı"}, {"ER_NO_OUTPUT_SPECIFIED", "Çıkış belirtilmedi"}, {"ER_CANNOT_TRANSFORM_TO_RESULT_TYPE", "{0} tipi sonuca dönüştürülemiyor"}, {"ER_CANNOT_TRANSFORM_SOURCE_TYPE", "{0} tipi kaynak dönüştürülemiyor"}, {"ER_NULL_CONTENT_HANDLER", "Boş değerli içerik işleyici"}, {"ER_NULL_ERROR_HANDLER", "Boş değerli hata işleyici"}, {"ER_CANNOT_CALL_PARSE", "ContentHandler tanımlanmadıysa parse çağrılamaz"}, {"ER_NO_PARENT_FOR_FILTER", "Süzgecin üst öğesi yok"}, {"ER_NO_STYLESHEET_IN_MEDIA", "Biçem yaprağı burada bulunamadı: {0}, ortam= {1}"}, {"ER_NO_STYLESHEET_PI", "xml-stylesheet PI burada bulunamadı: {0}"}, {"ER_NOT_SUPPORTED", "Desteklenmiyor: {0}"}, {"ER_PROPERTY_VALUE_BOOLEAN", "{0} özelliğinin değeri Boole somut örneği olmalı"}, {"ER_COULD_NOT_FIND_EXTERN_SCRIPT", "{0} içinde dış komut dosyasına ulaşılamadı"}, {"ER_RESOURCE_COULD_NOT_FIND", "Kaynak [ {0} ] bulunamadı.\n{1}"}, {"ER_OUTPUT_PROPERTY_NOT_RECOGNIZED", "Çıkış özelliği tanınmıyor: {0}"}, {"ER_FAILED_CREATING_ELEMLITRSLT", "ElemLiteralResult somut örneği yaratılması başarısız oldu"}, {"ER_VALUE_SHOULD_BE_NUMBER", "{0} değeri ayrıştırılabilir bir sayı içermelidir"}, {"ER_VALUE_SHOULD_EQUAL", "{0} değeri yes ya da no olmalı"}, {"ER_FAILED_CALLING_METHOD", "{0} yöntemi çağrısı başarısız oldu"}, {"ER_FAILED_CREATING_ELEMTMPL", "ElemTemplateElement somut örneği yaratılması başarısız oldu"}, {"ER_CHARS_NOT_ALLOWED", "Belgenin bu noktasında karakterlere izin verilmez"}, {"ER_ATTR_NOT_ALLOWED", "\"{0}\" özniteliği {1} öğesinde kullanılamaz!"}, {"ER_BAD_VALUE", "{0} hatalı değer {1}"}, {"ER_ATTRIB_VALUE_NOT_FOUND", "{0} öznitelik değeri bulunamadı"}, {"ER_ATTRIB_VALUE_NOT_RECOGNIZED", "{0} öznitelik değeri tanınmıyor"}, {"ER_NULL_URI_NAMESPACE", "Boş değerli URI ile ad alanı öneki oluşturma girişimi"}, {"ER_NUMBER_TOO_BIG", "En büyük uzun tamsayıdan daha büyük bir sayı biçimleme girişimi"}, {"ER_CANNOT_FIND_SAX1_DRIVER", "SAX1 sürücü sınıfı {0} bulunamıyor"}, {"ER_SAX1_DRIVER_NOT_LOADED", "SAX1 sürücü sınıfı {0} bulundu, ancak yüklenemiyor"}, {"ER_SAX1_DRIVER_NOT_INSTANTIATED", "SAX1 sürücü sınıfı {0} yüklendi, ancak somutlaştırılamıyor"}, {"ER_SAX1_DRIVER_NOT_IMPLEMENT_PARSER", "SAX1 sürücü sınıfı {0} org.xml.sax.Parser özelliğini uygulamıyor"}, {"ER_PARSER_PROPERTY_NOT_SPECIFIED", "Sistem özelliği org.xml.sax.parser belirtilmedi"}, {"ER_PARSER_ARG_CANNOT_BE_NULL", "Ayrıştırıcı (Parser) bağımsız değişkeni boş değerli olmamalı"}, {"ER_FEATURE", "Özellik: {0}"}, {"ER_PROPERTY", "Özellik: {0}"}, {"ER_NULL_ENTITY_RESOLVER", "Boş değerli varlık çözücü"}, {"ER_NULL_DTD_HANDLER", "Boş değerli DTD işleyici"}, {"ER_NO_DRIVER_NAME_SPECIFIED", "Sürücü adı belirtilmedi!"}, {"ER_NO_URL_SPECIFIED", "URL belirtilmedi!"}, {"ER_POOLSIZE_LESS_THAN_ONE", "Havuz büyüklüğü birden az!"}, {"ER_INVALID_DRIVER_NAME", "Belirtilen sürücü adı geçersiz!"}, {"ER_ERRORLISTENER", "ErrorListener"}, {"ER_ASSERT_NO_TEMPLATE_PARENT", "Programcı hatası! expr için ElemTemplateElement üst öğesi yok!"}, {"ER_ASSERT_REDUNDENT_EXPR_ELIMINATOR", "RundundentExprEliminator içinde programcı değerlendirmesi: {0}"}, {"ER_NOT_ALLOWED_IN_POSITION", "{0} biçem yaprağında bu konumda bulunamaz!"}, {"ER_NONWHITESPACE_NOT_ALLOWED_IN_POSITION", "Beyaz alan dışı metin biçem yaprağında bu konumda bulunamaz!"}, {"INVALID_TCHAR", "CHAR özniteliği {0} için geçersiz {1} değeri kullanıldı. CHAR tipinde bir öznitelik yalnızca 1 karakter olmalıdır!"}, {"INVALID_QNAME", "QNAME özniteliği {0} için geçersiz {1} değeri kullanıldı"}, {"INVALID_ENUM", "ENUM özniteliği {0} için geçersiz {1} değeri kullanıldı. Geçerli değerler: {2}."}, {"INVALID_NMTOKEN", "NMTOKEN özniteliği {0} için geçersiz {1} değeri kullanıldı"}, {"INVALID_NCNAME", "NCNAME özniteliği {0} için geçersiz {1} değeri kullanıldı"}, {"INVALID_BOOLEAN", "boolean özniteliği {0} için geçersiz {1} değeri kullanıldı"}, {"INVALID_NUMBER", "number özniteliği {0} için geçersiz {1} değeri kullanıldı"}, {"ER_ARG_LITERAL", "Eşleşme örüntüsünde {0} işlevine ilişkin bağımsız değişken bir hazır bilgi olmalıdır."}, {"ER_DUPLICATE_GLOBAL_VAR", "Yinelenen genel değişken bildirimi."}, {"ER_DUPLICATE_VAR", "Yinelenen değişken bildirimi."}, {"ER_TEMPLATE_NAME_MATCH", "xsl:template bir name ya da match özniteliği (ya da her ikisini) içermelidir"}, {"ER_INVALID_PREFIX", "exclude-result-prefixes içindeki önek geçerli değil: {0}"}, {"ER_NO_ATTRIB_SET", "{0} adlı öznitelik kümesi yok"}, {"WG_FOUND_CURLYBRACE", "'}' bulundu, ancak açık öznitelik şablonu yok!"}, {"WG_COUNT_ATTRIB_MATCHES_NO_ANCESTOR", "Uyarı: count özniteliği xsl:number içindeki bir üst öznitelikle eşleşmiyor! Hedef = {0}"}, {"WG_EXPR_ATTRIB_CHANGED_TO_SELECT", "Eski sözdizimi: 'expr' özniteliğinin adı 'select' olarak değiştirildi."}, {"WG_NO_LOCALE_IN_FORMATNUMBER", "Xalan henüz format-number işlevinde ülke değeri adını işlemiyor."}, {"WG_LOCALE_NOT_FOUND", "Uyarı: xml:lang={0} ile ilgili ülke değeri bulunamadı"}, {"WG_CANNOT_MAKE_URL_FROM", "Dizgiden URL oluşturulamadı: {0}"}, {"WG_CANNOT_LOAD_REQUESTED_DOC", "İstenen belge yüklenemiyor: {0}"}, {"WG_CANNOT_FIND_COLLATOR", "<sort xml:lang={0} için Collator bulunamadı"}, {"WG_FUNCTIONS_SHOULD_USE_URL", "Eski sözdizimi: functions yönergesi {0} url adresini kullanmalıdır"}, {"WG_ENCODING_NOT_SUPPORTED_USING_UTF8", "{0} kodlaması desteklenmiyor, UTF-8 kullanılıyor"}, {"WG_ENCODING_NOT_SUPPORTED_USING_JAVA", "{0} kodlaması desteklenmiyor, Java {1} kullanılıyor"}, {"WG_SPECIFICITY_CONFLICTS", "Belirtim çatışmaları saptandı: {0} Biçem yaprağında son bulunan kullanılacak."}, {"WG_PARSING_AND_PREPARING", "========= {0} ayrıştırılıyor ve hazırlanıyor =========="}, {"WG_ATTR_TEMPLATE", "Öznitelik şablonu, {0}"}, {"WG_CONFLICT_BETWEEN_XSLSTRIPSPACE_AND_XSLPRESERVESP", "xsl:strip-space ile xsl:preserve-space arasında eşleşme çatışması"}, {"WG_ATTRIB_NOT_HANDLED", "Xalan henüz {0} özniteliğini işlemiyor!"}, {"WG_NO_DECIMALFORMAT_DECLARATION", "Onlu biçimi için bildirim bulunamadı: {0}"}, {"WG_OLD_XSLT_NS", "Eksik ya da yanlış XSLT ad alanı."}, {"WG_ONE_DEFAULT_XSLDECIMALFORMAT_ALLOWED", "Varsayılan tek bir xsl:decimal-format bildirimine izin verilir."}, {"WG_XSLDECIMALFORMAT_NAMES_MUST_BE_UNIQUE", "xsl:decimal-format adları benzersiz olmalıdır. \"{0}\" adı yineleniyor."}, {"WG_ILLEGAL_ATTRIBUTE", "{0} geçersiz {1} özniteliğini içeriyor"}, {"WG_COULD_NOT_RESOLVE_PREFIX", "Ad alanı öneki {0} çözülemedi. Düğüm yoksayılacak."}, {"WG_STYLESHEET_REQUIRES_VERSION_ATTRIB", "xsl:stylesheet için 'version' özniteliği gerekiyor!"}, {"WG_ILLEGAL_ATTRIBUTE_NAME", "Geçersiz öznitelik adı: {0}"}, {"WG_ILLEGAL_ATTRIBUTE_VALUE", "{0} özniteliği için geçersiz {1} değeri kullanıldı"}, {"WG_EMPTY_SECOND_ARG", "Belge işlevinin ikinci bağımsız değişkeninden sonuçlanan düğüm kümesi (nodeset) boş. Boş düğüm kümesi döndürür."}, {"WG_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML", "xsl:processing-instruction adının 'name' özniteliği değeri 'xml' olmamalıdır"}, {"WG_PROCESSINGINSTRUCTION_NOTVALID_NCNAME", "xsl:processing-instruction ile ilgili 'name' özniteliği değeri geçerli bir NCName olmalıdır: {0}"}, {"WG_ILLEGAL_ATTRIBUTE_POSITION", "Alt düğümlerden sonra ya da bir öğe üretilmeden önce {0} özniteliği eklenemez. Öznitelik yoksayılacak."}, {"ui_language", "tr"}, {"help_language", "tr"}, {"language", "tr"}, {"BAD_CODE", "createMessage için kullanılan değiştirge sınırların dışında"}, {"FORMAT_FAILED", "messageFormat çağrısı sırasında kural dışı durum yayınlandı"}, {"version", ">>>>>>> Xalan Sürüm "}, {"version2", "<<<<<<<"}, {"yes", "yes"}, {"line", "Satır #"}, {"column", "Kolon #"}, {"xsldone", "XSLProcessor: bitti"}, {"xslProc_option", "Xalan-J komut satırı Process sınıfı seçenekleri: "}, {"xslProc_option", "Xalan-J komut satırı işlem sınıfı seçenekleri:"}, {"xslProc_invalid_xsltc_option", "{0} seçeneği XSLTC kipinde desteklenmez."}, {"xslProc_invalid_xalan_option", "{0} seçeneği yalnızca -XSLTC ile kullanılabilir."}, {"xslProc_no_input", "Hata: Biçem yaprağı ya da giriş xml belirtilmedi. Kullanım yönergeleri için, bu komutu seçenek belirtmeden çalıştırın."}, {"xslProc_common_options", "-Ortak Seçenekler-"}, {"xslProc_xalan_options", "-Xalan Seçenekleri-"}, {"xslProc_xsltc_options", "-XSLTC Seçenekleri-"}, {"xslProc_return_to_continue", "(devam etmek için <Enter> tuşuna basın)"}, {"optionXSLTC", "[-XSLTC (XSLTC dönüştürmede kullanılır)]"}, {"optionIN", "[-IN inputXMLURL]"}, {"optionXSL", "[-XSL XSLTransformationURL]"}, {"optionOUT", "[-OUT outputFileName]"}, {"optionLXCIN", "[-LXCIN compiledStylesheetFileNameIn]"}, {"optionLXCOUT", "[-LXCOUT compiledStylesheetFileNameOutOut]"}, {"optionPARSER", "[-PARSER ayrıştırıcı ilişkisinin tam olarak nitelenmiş sınıf adı]"}, {"optionE", "[-E (Varlık başvuruları genişletilmez)]"}, {"optionV", "[-E (Varlık başvuruları genişletilmez)]"}, {"optionQC", "[-QC (Sessiz örüntü çatışmaları uyarısı)]"}, {"optionQ", "[-Q  (Sessiz kip)]"}, {"optionLF", "   [-LF (satır besleme yalnızca çıkışta kullanılır {varsayılan CR/LF})]"}, {"optionCR", "   [-CR (Satırbaşı yalnızca çıkışta kullanılır {varsayılan CR/LF})]"}, {"optionESCAPE", "   [-ESCAPE (Kaçış karakterleri {varsayılan <>&\"'\\r\\n}]"}, {"optionINDENT", "[-INDENT (Girintili yazarken kullanılacak boşluk sayısı {varsayılan 0})]"}, {"optionTT", "[-TT (Şablonlar çağrılırken izlenir.)]"}, {"optionTG", "[-TG (Her oluşturma olayı izlenir.)]"}, {"optionTS", "[-TS (Her seçim olayı izlenir.)]"}, {"optionTTC", "[-TTC (Şablon alt öğeleri işlenirken izlenir.)]"}, {"optionTCLASS", "[-TCLASS (İzleme eklentileri için TraceListener sınıfı.)]"}, {"optionVALIDATE", "[-VALIDATE (Geçerlilik denetimi yapılıp yapılmayacağını belirler. Varsayılan olarak, geçerlilik denetimi kapalıdır.)]"}, {"optionEDUMP", "[-EDUMP {isteğe bağlı dosya adı} (Hata durumunda yığın dökümü gerçekleştirilir.)]"}, {"optionXML", "[-XML (XML biçimleyici kullanılır ve XML üstbilgisi eklenir.)]"}, {"optionTEXT", "[-TEXT (Yalın metin biçimleyici kullanılır.)]"}, {"optionHTML", "[-HTML (HTML biçimleyici kullanılır.)]"}, {"optionPARAM", "[-PARAM ad ifadesi (Biçem yaprağı değiştirgesi belirlenir.)]"}, {"noParsermsg1", "XSL işlemi başarısız oldu."}, {"noParsermsg2", "** Ayrıştırıcı bulunamadı **"}, {"noParsermsg3", "Lütfen classpath değişkeninizi inceleyin."}, {"noParsermsg4", "Sisteminizde IBM XML Parser for Java aracı yoksa, şu adresten yükleyebilirsiniz:"}, {"noParsermsg5", "IBM's AlphaWorks: http://www.alphaworks.ibm.com/formula/xml"}, {"optionURIRESOLVER", "[-URIRESOLVER tam sınıf adı (URI çözmekte kullanılacak URIResolver)]"}, {"optionENTITYRESOLVER", "[-ENTITYRESOLVER tam sınıf adı (Varlıkları çözmekte kullanılacak EntityResolver)]"}, {"optionCONTENTHANDLER", "[-CONTENTHANDLER tam sınıf adı (Çıkışı diziselleştirmekte kullanılacak ContentHandler)]"}, {"optionLINENUMBERS", "[-L kaynak belge için satır numaraları kullanılır]"}, {"optionMEDIA", "   [-MEDIA mediaType (Ortam özniteliği, bir belgeyle ilişkili biçem yaprağını bulmak için kullanılır.)]"}, {"optionFLAVOR", "   [-FLAVOR flavorName (Dönüştürmeyi gerçekleştirmek için belirtik olarak s2s=SAX ya da d2d=DOM kullanılır.)] "}, {"optionDIAG", "   [-DIAG (Dönüştürmenin kaç milisaniye sürdüğünü yazdırır.)]"}, {"optionINCREMENTAL", "  [-INCREMENTAL (http://xml.apache.org/xalan/features/incremental true tanımlayarak artımsal DTM oluşturulması istenir.)]"}, {"optionNOOPTIMIMIZE", "   [-NOOPTIMIMIZE (http://xml.apache.org/xalan/features/optimize false tanımlayarak biçem yaprağı eniyileme işlemi olmaması istenir.)]"}, {"optionRL", "   [-RL recursionlimit (Biçem yaprağı özyineleme derinliğine sayısal sınır koyar.)]"}, {"optionXO", "[-XO [derleme sonucu sınıf dosyası adı] (Oluşturulan sınıf dosyasına bu adı atar.)]"}, {"optionXD", "[-XD destinationDirectory (Derleme sonucu sınıf dosyası için hedef dizin belirtir.)]"}, {"optionXJ", "[-XJ jardsy (Derleme sonucu üretilen sınıfları <jardsy> adlı jar dosyasında paketler.)]"}, {"optionXP", "[-XP paket (Derleme sonucunda üretilen tüm sınıflar için bir paket adı öneki belirtir.)]"}, {"optionXN", "[-XN (Şablona doğrudan yerleştirmeyi açar.)]"}, {"optionXX", "[-XX (Ek hata ayıklama iletisi çıkışını açar.)]"}, {"optionXT", "[-XT (Yapılabiliyorsa, dönüştürme için derleme sonucu sınıf dosyasını kullanır.)]"}, {"diagTiming", "--------- {1} ile {0} dönüştürme işlemi {2} ms sürdü"}, {"recursionTooDeep", "Şablon içiçe kullanım derinliği çok fazla. İçiçe kullanım = {0}, şablon {1} {2}"}, {"nameIs", "adı"}, {"matchPatternIs", "eşleşme örüntüsü"}};
   }

   public static final XSLTErrorResources loadResourceBundle(String className) throws MissingResourceException {
      Locale locale = Locale.getDefault();
      String suffix = getResourceSuffix(locale);

      try {
         return (XSLTErrorResources)ResourceBundle.getBundle(className + suffix, locale);
      } catch (MissingResourceException var6) {
         try {
            return (XSLTErrorResources)ResourceBundle.getBundle(className, new Locale("tr", "TR"));
         } catch (MissingResourceException var5) {
            throw new MissingResourceException("Could not load any resource bundles.", className, "");
         }
      }
   }

   private static final String getResourceSuffix(Locale locale) {
      String suffix = "_" + locale.getLanguage();
      String country = locale.getCountry();
      if (country.equals("TW")) {
         suffix = suffix + "_" + country;
      }

      return suffix;
   }
}
