package org.apache.xalan.res;

import java.util.ListResourceBundle;
import java.util.Locale;
import java.util.MissingResourceException;
import java.util.ResourceBundle;

public class XSLTErrorResources_cs extends ListResourceBundle {
   public static final int MAX_CODE = 201;
   public static final int MAX_WARNING = 29;
   public static final int MAX_OTHERS = 55;
   public static final int MAX_MESSAGES = 231;
   public static final String ER_NO_CURLYBRACE = "ER_NO_CURLYBRACE";
   public static final String ER_ILLEGAL_ATTRIBUTE = "ER_ILLEGAL_ATTRIBUTE";
   public static final String ER_NULL_SOURCENODE_APPLYIMPORTS = "ER_NULL_SOURCENODE_APPLYIMPORTS";
   public static final String ER_CANNOT_ADD = "ER_CANNOT_ADD";
   public static final String ER_NULL_SOURCENODE_HANDLEAPPLYTEMPLATES = "ER_NULL_SOURCENODE_HANDLEAPPLYTEMPLATES";
   public static final String ER_NO_NAME_ATTRIB = "ER_NO_NAME_ATTRIB";
   public static final String ER_TEMPLATE_NOT_FOUND = "ER_TEMPLATE_NOT_FOUND";
   public static final String ER_CANT_RESOLVE_NAME_AVT = "ER_CANT_RESOLVE_NAME_AVT";
   public static final String ER_REQUIRES_ATTRIB = "ER_REQUIRES_ATTRIB";
   public static final String ER_MUST_HAVE_TEST_ATTRIB = "ER_MUST_HAVE_TEST_ATTRIB";
   public static final String ER_BAD_VAL_ON_LEVEL_ATTRIB = "ER_BAD_VAL_ON_LEVEL_ATTRIB";
   public static final String ER_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML = "ER_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML";
   public static final String ER_PROCESSINGINSTRUCTION_NOTVALID_NCNAME = "ER_PROCESSINGINSTRUCTION_NOTVALID_NCNAME";
   public static final String ER_NEED_MATCH_ATTRIB = "ER_NEED_MATCH_ATTRIB";
   public static final String ER_NEED_NAME_OR_MATCH_ATTRIB = "ER_NEED_NAME_OR_MATCH_ATTRIB";
   public static final String ER_CANT_RESOLVE_NSPREFIX = "ER_CANT_RESOLVE_NSPREFIX";
   public static final String ER_ILLEGAL_VALUE = "ER_ILLEGAL_VALUE";
   public static final String ER_NO_OWNERDOC = "ER_NO_OWNERDOC";
   public static final String ER_ELEMTEMPLATEELEM_ERR = "ER_ELEMTEMPLATEELEM_ERR";
   public static final String ER_NULL_CHILD = "ER_NULL_CHILD";
   public static final String ER_NEED_SELECT_ATTRIB = "ER_NEED_SELECT_ATTRIB";
   public static final String ER_NEED_TEST_ATTRIB = "ER_NEED_TEST_ATTRIB";
   public static final String ER_NEED_NAME_ATTRIB = "ER_NEED_NAME_ATTRIB";
   public static final String ER_NO_CONTEXT_OWNERDOC = "ER_NO_CONTEXT_OWNERDOC";
   public static final String ER_COULD_NOT_CREATE_XML_PROC_LIAISON = "ER_COULD_NOT_CREATE_XML_PROC_LIAISON";
   public static final String ER_PROCESS_NOT_SUCCESSFUL = "ER_PROCESS_NOT_SUCCESSFUL";
   public static final String ER_NOT_SUCCESSFUL = "ER_NOT_SUCCESSFUL";
   public static final String ER_ENCODING_NOT_SUPPORTED = "ER_ENCODING_NOT_SUPPORTED";
   public static final String ER_COULD_NOT_CREATE_TRACELISTENER = "ER_COULD_NOT_CREATE_TRACELISTENER";
   public static final String ER_KEY_REQUIRES_NAME_ATTRIB = "ER_KEY_REQUIRES_NAME_ATTRIB";
   public static final String ER_KEY_REQUIRES_MATCH_ATTRIB = "ER_KEY_REQUIRES_MATCH_ATTRIB";
   public static final String ER_KEY_REQUIRES_USE_ATTRIB = "ER_KEY_REQUIRES_USE_ATTRIB";
   public static final String ER_REQUIRES_ELEMENTS_ATTRIB = "ER_REQUIRES_ELEMENTS_ATTRIB";
   public static final String ER_MISSING_PREFIX_ATTRIB = "ER_MISSING_PREFIX_ATTRIB";
   public static final String ER_BAD_STYLESHEET_URL = "ER_BAD_STYLESHEET_URL";
   public static final String ER_FILE_NOT_FOUND = "ER_FILE_NOT_FOUND";
   public static final String ER_IOEXCEPTION = "ER_IOEXCEPTION";
   public static final String ER_NO_HREF_ATTRIB = "ER_NO_HREF_ATTRIB";
   public static final String ER_STYLESHEET_INCLUDES_ITSELF = "ER_STYLESHEET_INCLUDES_ITSELF";
   public static final String ER_PROCESSINCLUDE_ERROR = "ER_PROCESSINCLUDE_ERROR";
   public static final String ER_MISSING_LANG_ATTRIB = "ER_MISSING_LANG_ATTRIB";
   public static final String ER_MISSING_CONTAINER_ELEMENT_COMPONENT = "ER_MISSING_CONTAINER_ELEMENT_COMPONENT";
   public static final String ER_CAN_ONLY_OUTPUT_TO_ELEMENT = "ER_CAN_ONLY_OUTPUT_TO_ELEMENT";
   public static final String ER_PROCESS_ERROR = "ER_PROCESS_ERROR";
   public static final String ER_UNIMPLNODE_ERROR = "ER_UNIMPLNODE_ERROR";
   public static final String ER_NO_SELECT_EXPRESSION = "ER_NO_SELECT_EXPRESSION";
   public static final String ER_CANNOT_SERIALIZE_XSLPROCESSOR = "ER_CANNOT_SERIALIZE_XSLPROCESSOR";
   public static final String ER_NO_INPUT_STYLESHEET = "ER_NO_INPUT_STYLESHEET";
   public static final String ER_FAILED_PROCESS_STYLESHEET = "ER_FAILED_PROCESS_STYLESHEET";
   public static final String ER_COULDNT_PARSE_DOC = "ER_COULDNT_PARSE_DOC";
   public static final String ER_COULDNT_FIND_FRAGMENT = "ER_COULDNT_FIND_FRAGMENT";
   public static final String ER_NODE_NOT_ELEMENT = "ER_NODE_NOT_ELEMENT";
   public static final String ER_FOREACH_NEED_MATCH_OR_NAME_ATTRIB = "ER_FOREACH_NEED_MATCH_OR_NAME_ATTRIB";
   public static final String ER_TEMPLATES_NEED_MATCH_OR_NAME_ATTRIB = "ER_TEMPLATES_NEED_MATCH_OR_NAME_ATTRIB";
   public static final String ER_NO_CLONE_OF_DOCUMENT_FRAG = "ER_NO_CLONE_OF_DOCUMENT_FRAG";
   public static final String ER_CANT_CREATE_ITEM = "ER_CANT_CREATE_ITEM";
   public static final String ER_XMLSPACE_ILLEGAL_VALUE = "ER_XMLSPACE_ILLEGAL_VALUE";
   public static final String ER_NO_XSLKEY_DECLARATION = "ER_NO_XSLKEY_DECLARATION";
   public static final String ER_CANT_CREATE_URL = "ER_CANT_CREATE_URL";
   public static final String ER_XSLFUNCTIONS_UNSUPPORTED = "ER_XSLFUNCTIONS_UNSUPPORTED";
   public static final String ER_PROCESSOR_ERROR = "ER_PROCESSOR_ERROR";
   public static final String ER_NOT_ALLOWED_INSIDE_STYLESHEET = "ER_NOT_ALLOWED_INSIDE_STYLESHEET";
   public static final String ER_RESULTNS_NOT_SUPPORTED = "ER_RESULTNS_NOT_SUPPORTED";
   public static final String ER_DEFAULTSPACE_NOT_SUPPORTED = "ER_DEFAULTSPACE_NOT_SUPPORTED";
   public static final String ER_INDENTRESULT_NOT_SUPPORTED = "ER_INDENTRESULT_NOT_SUPPORTED";
   public static final String ER_ILLEGAL_ATTRIB = "ER_ILLEGAL_ATTRIB";
   public static final String ER_UNKNOWN_XSL_ELEM = "ER_UNKNOWN_XSL_ELEM";
   public static final String ER_BAD_XSLSORT_USE = "ER_BAD_XSLSORT_USE";
   public static final String ER_MISPLACED_XSLWHEN = "ER_MISPLACED_XSLWHEN";
   public static final String ER_XSLWHEN_NOT_PARENTED_BY_XSLCHOOSE = "ER_XSLWHEN_NOT_PARENTED_BY_XSLCHOOSE";
   public static final String ER_MISPLACED_XSLOTHERWISE = "ER_MISPLACED_XSLOTHERWISE";
   public static final String ER_XSLOTHERWISE_NOT_PARENTED_BY_XSLCHOOSE = "ER_XSLOTHERWISE_NOT_PARENTED_BY_XSLCHOOSE";
   public static final String ER_NOT_ALLOWED_INSIDE_TEMPLATE = "ER_NOT_ALLOWED_INSIDE_TEMPLATE";
   public static final String ER_UNKNOWN_EXT_NS_PREFIX = "ER_UNKNOWN_EXT_NS_PREFIX";
   public static final String ER_IMPORTS_AS_FIRST_ELEM = "ER_IMPORTS_AS_FIRST_ELEM";
   public static final String ER_IMPORTING_ITSELF = "ER_IMPORTING_ITSELF";
   public static final String ER_XMLSPACE_ILLEGAL_VAL = "ER_XMLSPACE_ILLEGAL_VAL";
   public static final String ER_PROCESSSTYLESHEET_NOT_SUCCESSFUL = "ER_PROCESSSTYLESHEET_NOT_SUCCESSFUL";
   public static final String ER_SAX_EXCEPTION = "ER_SAX_EXCEPTION";
   public static final String ER_XSLT_ERROR = "ER_XSLT_ERROR";
   public static final String ER_CURRENCY_SIGN_ILLEGAL = "ER_CURRENCY_SIGN_ILLEGAL";
   public static final String ER_DOCUMENT_FUNCTION_INVALID_IN_STYLESHEET_DOM = "ER_DOCUMENT_FUNCTION_INVALID_IN_STYLESHEET_DOM";
   public static final String ER_CANT_RESOLVE_PREFIX_OF_NON_PREFIX_RESOLVER = "ER_CANT_RESOLVE_PREFIX_OF_NON_PREFIX_RESOLVER";
   public static final String ER_REDIRECT_COULDNT_GET_FILENAME = "ER_REDIRECT_COULDNT_GET_FILENAME";
   public static final String ER_CANNOT_BUILD_FORMATTERLISTENER_IN_REDIRECT = "ER_CANNOT_BUILD_FORMATTERLISTENER_IN_REDIRECT";
   public static final String ER_INVALID_PREFIX_IN_EXCLUDERESULTPREFIX = "ER_INVALID_PREFIX_IN_EXCLUDERESULTPREFIX";
   public static final String ER_MISSING_NS_URI = "ER_MISSING_NS_URI";
   public static final String ER_MISSING_ARG_FOR_OPTION = "ER_MISSING_ARG_FOR_OPTION";
   public static final String ER_INVALID_OPTION = "ER_INVALID_OPTION";
   public static final String ER_MALFORMED_FORMAT_STRING = "ER_MALFORMED_FORMAT_STRING";
   public static final String ER_STYLESHEET_REQUIRES_VERSION_ATTRIB = "ER_STYLESHEET_REQUIRES_VERSION_ATTRIB";
   public static final String ER_ILLEGAL_ATTRIBUTE_VALUE = "ER_ILLEGAL_ATTRIBUTE_VALUE";
   public static final String ER_CHOOSE_REQUIRES_WHEN = "ER_CHOOSE_REQUIRES_WHEN";
   public static final String ER_NO_APPLY_IMPORT_IN_FOR_EACH = "ER_NO_APPLY_IMPORT_IN_FOR_EACH";
   public static final String ER_CANT_USE_DTM_FOR_OUTPUT = "ER_CANT_USE_DTM_FOR_OUTPUT";
   public static final String ER_CANT_USE_DTM_FOR_INPUT = "ER_CANT_USE_DTM_FOR_INPUT";
   public static final String ER_CALL_TO_EXT_FAILED = "ER_CALL_TO_EXT_FAILED";
   public static final String ER_PREFIX_MUST_RESOLVE = "ER_PREFIX_MUST_RESOLVE";
   public static final String ER_INVALID_UTF16_SURROGATE = "ER_INVALID_UTF16_SURROGATE";
   public static final String ER_XSLATTRSET_USED_ITSELF = "ER_XSLATTRSET_USED_ITSELF";
   public static final String ER_CANNOT_MIX_XERCESDOM = "ER_CANNOT_MIX_XERCESDOM";
   public static final String ER_TOO_MANY_LISTENERS = "ER_TOO_MANY_LISTENERS";
   public static final String ER_IN_ELEMTEMPLATEELEM_READOBJECT = "ER_IN_ELEMTEMPLATEELEM_READOBJECT";
   public static final String ER_DUPLICATE_NAMED_TEMPLATE = "ER_DUPLICATE_NAMED_TEMPLATE";
   public static final String ER_INVALID_KEY_CALL = "ER_INVALID_KEY_CALL";
   public static final String ER_REFERENCING_ITSELF = "ER_REFERENCING_ITSELF";
   public static final String ER_ILLEGAL_DOMSOURCE_INPUT = "ER_ILLEGAL_DOMSOURCE_INPUT";
   public static final String ER_CLASS_NOT_FOUND_FOR_OPTION = "ER_CLASS_NOT_FOUND_FOR_OPTION";
   public static final String ER_REQUIRED_ELEM_NOT_FOUND = "ER_REQUIRED_ELEM_NOT_FOUND";
   public static final String ER_INPUT_CANNOT_BE_NULL = "ER_INPUT_CANNOT_BE_NULL";
   public static final String ER_URI_CANNOT_BE_NULL = "ER_URI_CANNOT_BE_NULL";
   public static final String ER_FILE_CANNOT_BE_NULL = "ER_FILE_CANNOT_BE_NULL";
   public static final String ER_SOURCE_CANNOT_BE_NULL = "ER_SOURCE_CANNOT_BE_NULL";
   public static final String ER_CANNOT_INIT_BSFMGR = "ER_CANNOT_INIT_BSFMGR";
   public static final String ER_CANNOT_CMPL_EXTENSN = "ER_CANNOT_CMPL_EXTENSN";
   public static final String ER_CANNOT_CREATE_EXTENSN = "ER_CANNOT_CREATE_EXTENSN";
   public static final String ER_INSTANCE_MTHD_CALL_REQUIRES = "ER_INSTANCE_MTHD_CALL_REQUIRES";
   public static final String ER_INVALID_ELEMENT_NAME = "ER_INVALID_ELEMENT_NAME";
   public static final String ER_ELEMENT_NAME_METHOD_STATIC = "ER_ELEMENT_NAME_METHOD_STATIC";
   public static final String ER_EXTENSION_FUNC_UNKNOWN = "ER_EXTENSION_FUNC_UNKNOWN";
   public static final String ER_MORE_MATCH_CONSTRUCTOR = "ER_MORE_MATCH_CONSTRUCTOR";
   public static final String ER_MORE_MATCH_METHOD = "ER_MORE_MATCH_METHOD";
   public static final String ER_MORE_MATCH_ELEMENT = "ER_MORE_MATCH_ELEMENT";
   public static final String ER_INVALID_CONTEXT_PASSED = "ER_INVALID_CONTEXT_PASSED";
   public static final String ER_POOL_EXISTS = "ER_POOL_EXISTS";
   public static final String ER_NO_DRIVER_NAME = "ER_NO_DRIVER_NAME";
   public static final String ER_NO_URL = "ER_NO_URL";
   public static final String ER_POOL_SIZE_LESSTHAN_ONE = "ER_POOL_SIZE_LESSTHAN_ONE";
   public static final String ER_INVALID_DRIVER = "ER_INVALID_DRIVER";
   public static final String ER_NO_STYLESHEETROOT = "ER_NO_STYLESHEETROOT";
   public static final String ER_ILLEGAL_XMLSPACE_VALUE = "ER_ILLEGAL_XMLSPACE_VALUE";
   public static final String ER_PROCESSFROMNODE_FAILED = "ER_PROCESSFROMNODE_FAILED";
   public static final String ER_RESOURCE_COULD_NOT_LOAD = "ER_RESOURCE_COULD_NOT_LOAD";
   public static final String ER_BUFFER_SIZE_LESSTHAN_ZERO = "ER_BUFFER_SIZE_LESSTHAN_ZERO";
   public static final String ER_UNKNOWN_ERROR_CALLING_EXTENSION = "ER_UNKNOWN_ERROR_CALLING_EXTENSION";
   public static final String ER_NO_NAMESPACE_DECL = "ER_NO_NAMESPACE_DECL";
   public static final String ER_ELEM_CONTENT_NOT_ALLOWED = "ER_ELEM_CONTENT_NOT_ALLOWED";
   public static final String ER_STYLESHEET_DIRECTED_TERMINATION = "ER_STYLESHEET_DIRECTED_TERMINATION";
   public static final String ER_ONE_OR_TWO = "ER_ONE_OR_TWO";
   public static final String ER_TWO_OR_THREE = "ER_TWO_OR_THREE";
   public static final String ER_COULD_NOT_LOAD_RESOURCE = "ER_COULD_NOT_LOAD_RESOURCE";
   public static final String ER_CANNOT_INIT_DEFAULT_TEMPLATES = "ER_CANNOT_INIT_DEFAULT_TEMPLATES";
   public static final String ER_RESULT_NULL = "ER_RESULT_NULL";
   public static final String ER_RESULT_COULD_NOT_BE_SET = "ER_RESULT_COULD_NOT_BE_SET";
   public static final String ER_NO_OUTPUT_SPECIFIED = "ER_NO_OUTPUT_SPECIFIED";
   public static final String ER_CANNOT_TRANSFORM_TO_RESULT_TYPE = "ER_CANNOT_TRANSFORM_TO_RESULT_TYPE";
   public static final String ER_CANNOT_TRANSFORM_SOURCE_TYPE = "ER_CANNOT_TRANSFORM_SOURCE_TYPE";
   public static final String ER_NULL_CONTENT_HANDLER = "ER_NULL_CONTENT_HANDLER";
   public static final String ER_NULL_ERROR_HANDLER = "ER_NULL_ERROR_HANDLER";
   public static final String ER_CANNOT_CALL_PARSE = "ER_CANNOT_CALL_PARSE";
   public static final String ER_NO_PARENT_FOR_FILTER = "ER_NO_PARENT_FOR_FILTER";
   public static final String ER_NO_STYLESHEET_IN_MEDIA = "ER_NO_STYLESHEET_IN_MEDIA";
   public static final String ER_NO_STYLESHEET_PI = "ER_NO_STYLESHEET_PI";
   public static final String ER_NOT_SUPPORTED = "ER_NOT_SUPPORTED";
   public static final String ER_PROPERTY_VALUE_BOOLEAN = "ER_PROPERTY_VALUE_BOOLEAN";
   public static final String ER_COULD_NOT_FIND_EXTERN_SCRIPT = "ER_COULD_NOT_FIND_EXTERN_SCRIPT";
   public static final String ER_RESOURCE_COULD_NOT_FIND = "ER_RESOURCE_COULD_NOT_FIND";
   public static final String ER_OUTPUT_PROPERTY_NOT_RECOGNIZED = "ER_OUTPUT_PROPERTY_NOT_RECOGNIZED";
   public static final String ER_FAILED_CREATING_ELEMLITRSLT = "ER_FAILED_CREATING_ELEMLITRSLT";
   public static final String ER_VALUE_SHOULD_BE_NUMBER = "ER_VALUE_SHOULD_BE_NUMBER";
   public static final String ER_VALUE_SHOULD_EQUAL = "ER_VALUE_SHOULD_EQUAL";
   public static final String ER_FAILED_CALLING_METHOD = "ER_FAILED_CALLING_METHOD";
   public static final String ER_FAILED_CREATING_ELEMTMPL = "ER_FAILED_CREATING_ELEMTMPL";
   public static final String ER_CHARS_NOT_ALLOWED = "ER_CHARS_NOT_ALLOWED";
   public static final String ER_ATTR_NOT_ALLOWED = "ER_ATTR_NOT_ALLOWED";
   public static final String ER_BAD_VALUE = "ER_BAD_VALUE";
   public static final String ER_ATTRIB_VALUE_NOT_FOUND = "ER_ATTRIB_VALUE_NOT_FOUND";
   public static final String ER_ATTRIB_VALUE_NOT_RECOGNIZED = "ER_ATTRIB_VALUE_NOT_RECOGNIZED";
   public static final String ER_NULL_URI_NAMESPACE = "ER_NULL_URI_NAMESPACE";
   public static final String ER_NUMBER_TOO_BIG = "ER_NUMBER_TOO_BIG";
   public static final String ER_CANNOT_FIND_SAX1_DRIVER = "ER_CANNOT_FIND_SAX1_DRIVER";
   public static final String ER_SAX1_DRIVER_NOT_LOADED = "ER_SAX1_DRIVER_NOT_LOADED";
   public static final String ER_SAX1_DRIVER_NOT_INSTANTIATED = "ER_SAX1_DRIVER_NOT_INSTANTIATED";
   public static final String ER_SAX1_DRIVER_NOT_IMPLEMENT_PARSER = "ER_SAX1_DRIVER_NOT_IMPLEMENT_PARSER";
   public static final String ER_PARSER_PROPERTY_NOT_SPECIFIED = "ER_PARSER_PROPERTY_NOT_SPECIFIED";
   public static final String ER_PARSER_ARG_CANNOT_BE_NULL = "ER_PARSER_ARG_CANNOT_BE_NULL";
   public static final String ER_FEATURE = "ER_FEATURE";
   public static final String ER_PROPERTY = "ER_PROPERTY";
   public static final String ER_NULL_ENTITY_RESOLVER = "ER_NULL_ENTITY_RESOLVER";
   public static final String ER_NULL_DTD_HANDLER = "ER_NULL_DTD_HANDLER";
   public static final String ER_NO_DRIVER_NAME_SPECIFIED = "ER_NO_DRIVER_NAME_SPECIFIED";
   public static final String ER_NO_URL_SPECIFIED = "ER_NO_URL_SPECIFIED";
   public static final String ER_POOLSIZE_LESS_THAN_ONE = "ER_POOLSIZE_LESS_THAN_ONE";
   public static final String ER_INVALID_DRIVER_NAME = "ER_INVALID_DRIVER_NAME";
   public static final String ER_ERRORLISTENER = "ER_ERRORLISTENER";
   public static final String ER_ASSERT_NO_TEMPLATE_PARENT = "ER_ASSERT_NO_TEMPLATE_PARENT";
   public static final String ER_ASSERT_REDUNDENT_EXPR_ELIMINATOR = "ER_ASSERT_REDUNDENT_EXPR_ELIMINATOR";
   public static final String ER_NOT_ALLOWED_IN_POSITION = "ER_NOT_ALLOWED_IN_POSITION";
   public static final String ER_NONWHITESPACE_NOT_ALLOWED_IN_POSITION = "ER_NONWHITESPACE_NOT_ALLOWED_IN_POSITION";
   public static final String INVALID_TCHAR = "INVALID_TCHAR";
   public static final String INVALID_QNAME = "INVALID_QNAME";
   public static final String INVALID_ENUM = "INVALID_ENUM";
   public static final String INVALID_NMTOKEN = "INVALID_NMTOKEN";
   public static final String INVALID_NCNAME = "INVALID_NCNAME";
   public static final String INVALID_BOOLEAN = "INVALID_BOOLEAN";
   public static final String INVALID_NUMBER = "INVALID_NUMBER";
   public static final String ER_ARG_LITERAL = "ER_ARG_LITERAL";
   public static final String ER_DUPLICATE_GLOBAL_VAR = "ER_DUPLICATE_GLOBAL_VAR";
   public static final String ER_DUPLICATE_VAR = "ER_DUPLICATE_VAR";
   public static final String ER_TEMPLATE_NAME_MATCH = "ER_TEMPLATE_NAME_MATCH";
   public static final String ER_INVALID_PREFIX = "ER_INVALID_PREFIX";
   public static final String ER_NO_ATTRIB_SET = "ER_NO_ATTRIB_SET";
   public static final String WG_FOUND_CURLYBRACE = "WG_FOUND_CURLYBRACE";
   public static final String WG_COUNT_ATTRIB_MATCHES_NO_ANCESTOR = "WG_COUNT_ATTRIB_MATCHES_NO_ANCESTOR";
   public static final String WG_EXPR_ATTRIB_CHANGED_TO_SELECT = "WG_EXPR_ATTRIB_CHANGED_TO_SELECT";
   public static final String WG_NO_LOCALE_IN_FORMATNUMBER = "WG_NO_LOCALE_IN_FORMATNUMBER";
   public static final String WG_LOCALE_NOT_FOUND = "WG_LOCALE_NOT_FOUND";
   public static final String WG_CANNOT_MAKE_URL_FROM = "WG_CANNOT_MAKE_URL_FROM";
   public static final String WG_CANNOT_LOAD_REQUESTED_DOC = "WG_CANNOT_LOAD_REQUESTED_DOC";
   public static final String WG_CANNOT_FIND_COLLATOR = "WG_CANNOT_FIND_COLLATOR";
   public static final String WG_FUNCTIONS_SHOULD_USE_URL = "WG_FUNCTIONS_SHOULD_USE_URL";
   public static final String WG_ENCODING_NOT_SUPPORTED_USING_UTF8 = "WG_ENCODING_NOT_SUPPORTED_USING_UTF8";
   public static final String WG_ENCODING_NOT_SUPPORTED_USING_JAVA = "WG_ENCODING_NOT_SUPPORTED_USING_JAVA";
   public static final String WG_SPECIFICITY_CONFLICTS = "WG_SPECIFICITY_CONFLICTS";
   public static final String WG_PARSING_AND_PREPARING = "WG_PARSING_AND_PREPARING";
   public static final String WG_ATTR_TEMPLATE = "WG_ATTR_TEMPLATE";
   public static final String WG_CONFLICT_BETWEEN_XSLSTRIPSPACE_AND_XSLPRESERVESPACE = "WG_CONFLICT_BETWEEN_XSLSTRIPSPACE_AND_XSLPRESERVESP";
   public static final String WG_ATTRIB_NOT_HANDLED = "WG_ATTRIB_NOT_HANDLED";
   public static final String WG_NO_DECIMALFORMAT_DECLARATION = "WG_NO_DECIMALFORMAT_DECLARATION";
   public static final String WG_OLD_XSLT_NS = "WG_OLD_XSLT_NS";
   public static final String WG_ONE_DEFAULT_XSLDECIMALFORMAT_ALLOWED = "WG_ONE_DEFAULT_XSLDECIMALFORMAT_ALLOWED";
   public static final String WG_XSLDECIMALFORMAT_NAMES_MUST_BE_UNIQUE = "WG_XSLDECIMALFORMAT_NAMES_MUST_BE_UNIQUE";
   public static final String WG_ILLEGAL_ATTRIBUTE = "WG_ILLEGAL_ATTRIBUTE";
   public static final String WG_COULD_NOT_RESOLVE_PREFIX = "WG_COULD_NOT_RESOLVE_PREFIX";
   public static final String WG_STYLESHEET_REQUIRES_VERSION_ATTRIB = "WG_STYLESHEET_REQUIRES_VERSION_ATTRIB";
   public static final String WG_ILLEGAL_ATTRIBUTE_NAME = "WG_ILLEGAL_ATTRIBUTE_NAME";
   public static final String WG_ILLEGAL_ATTRIBUTE_VALUE = "WG_ILLEGAL_ATTRIBUTE_VALUE";
   public static final String WG_EMPTY_SECOND_ARG = "WG_EMPTY_SECOND_ARG";
   public static final String WG_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML = "WG_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML";
   public static final String WG_PROCESSINGINSTRUCTION_NOTVALID_NCNAME = "WG_PROCESSINGINSTRUCTION_NOTVALID_NCNAME";
   public static final String WG_ILLEGAL_ATTRIBUTE_POSITION = "WG_ILLEGAL_ATTRIBUTE_POSITION";
   public static final String BAD_CODE = "BAD_CODE";
   public static final String FORMAT_FAILED = "FORMAT_FAILED";
   public static final String ERROR_STRING = "#chyba";
   public static final String ERROR_HEADER = "Chyba: ";
   public static final String WARNING_HEADER = "Varování: ";
   public static final String XSL_HEADER = "XSLT ";
   public static final String XML_HEADER = "XML ";
   /** @deprecated */
   public static final String QUERY_HEADER = "PATTERN ";

   public Object[][] getContents() {
      return new Object[][]{{"ER0000", "{0}"}, {"ER_NO_CURLYBRACE", "Chyba: Ve výrazu nelze použít znak '{'"}, {"ER_ILLEGAL_ATTRIBUTE", "{0} má neplatný atribut: {1}"}, {"ER_NULL_SOURCENODE_APPLYIMPORTS", "Funkce sourceNode má v prvku xsl:apply-imports hodnotu null!"}, {"ER_CANNOT_ADD", "Nelze přidat {0} do {1}"}, {"ER_NULL_SOURCENODE_HANDLEAPPLYTEMPLATES", "Funkce sourceNode má v instrukci handleApplyTemplatesInstruction hodnotu null!"}, {"ER_NO_NAME_ATTRIB", "{0} musí mít jmenný atribut"}, {"ER_TEMPLATE_NOT_FOUND", "Nelze nalézt šablonu s názvem: {0}"}, {"ER_CANT_RESOLVE_NAME_AVT", "Nelze nalézt název AVT v šabloně xsl:call-template."}, {"ER_REQUIRES_ATTRIB", "{0} musí mít atribut: {1}"}, {"ER_MUST_HAVE_TEST_ATTRIB", "{0} musí obsahovat atribut ''test''."}, {"ER_BAD_VAL_ON_LEVEL_ATTRIB", "Nesprávná hodnota atributu úrovně: {0}"}, {"ER_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML", "název instrukce processing-instruction nemůže být 'xml'"}, {"ER_PROCESSINGINSTRUCTION_NOTVALID_NCNAME", "název instrukce processing-instruction musí být platný název NCName: {0}"}, {"ER_NEED_MATCH_ATTRIB", "Má-li {0} režim, musí mít vyhovující atribut."}, {"ER_NEED_NAME_OR_MATCH_ATTRIB", "{0} vyžaduje buď název, nebo vyhovující atribut."}, {"ER_CANT_RESOLVE_NSPREFIX", "Nelze přeložit předponu oboru názvů: {0}"}, {"ER_ILLEGAL_VALUE", "Nepovolená hodnota prvku xml:space: {0}"}, {"ER_NO_OWNERDOC", "Uzel potomka nemá dokument vlastníka!"}, {"ER_ELEMTEMPLATEELEM_ERR", "Chyba funkce ElemTemplateElement: {0}"}, {"ER_NULL_CHILD", "Pokus o přidání potomka s hodnotou null!"}, {"ER_NEED_SELECT_ATTRIB", "{0} vyžaduje atribut select."}, {"ER_NEED_TEST_ATTRIB", "Prvek xsl:when musí obsahovat atribut 'test'."}, {"ER_NEED_NAME_ATTRIB", "Prvek xsl:with-param musí obsahovat atribut 'name'."}, {"ER_NO_CONTEXT_OWNERDOC", "Parametr context nemá dokument vlastníka!"}, {"ER_COULD_NOT_CREATE_XML_PROC_LIAISON", "Nelze vytvořit prvek XML TransformerFactory Liaison: {0}"}, {"ER_PROCESS_NOT_SUCCESSFUL", "Xalan: Proces nebyl úspěšný."}, {"ER_NOT_SUCCESSFUL", "Xalan: nebylo úspěšné."}, {"ER_ENCODING_NOT_SUPPORTED", "Kódování není podporováno: {0}"}, {"ER_COULD_NOT_CREATE_TRACELISTENER", "Nelze vytvořit TraceListener: {0}"}, {"ER_KEY_REQUIRES_NAME_ATTRIB", "Prvek xsl:key vyžaduje atribut 'name'!"}, {"ER_KEY_REQUIRES_MATCH_ATTRIB", "Prvek xsl:key vyžaduje atribut 'match'!"}, {"ER_KEY_REQUIRES_USE_ATTRIB", "Prvek xsl:key vyžaduje atribut 'use'!"}, {"ER_REQUIRES_ELEMENTS_ATTRIB", "(StylesheetHandler) {0} vyžaduje atribut ''elements''!"}, {"ER_MISSING_PREFIX_ATTRIB", "(StylesheetHandler) {0} - chybí atribut ''prefix''"}, {"ER_BAD_STYLESHEET_URL", "Nesprávná adresa URL předlohy se styly: {0}"}, {"ER_FILE_NOT_FOUND", "Soubor předlohy se styly nebyl nalezen: {0}"}, {"ER_IOEXCEPTION", "Soubor předlohy se styly má výjimku vstupu/výstupu: {0}"}, {"ER_NO_HREF_ATTRIB", "(StylesheetHandler) Pro {0} nelze najít atribut href"}, {"ER_STYLESHEET_INCLUDES_ITSELF", "(StylesheetHandler) {0}: přímo nebo nepřímo zahrnuje sebe sama!"}, {"ER_PROCESSINCLUDE_ERROR", "Chyba: StylesheetHandler.processInclude {0}"}, {"ER_MISSING_LANG_ATTRIB", "(StylesheetHandler) {0} - chybí atribut ''lang''"}, {"ER_MISSING_CONTAINER_ELEMENT_COMPONENT", "(StylesheetHandler) Nesprávně umístěný prvek {0}?? Chybí prvek pořadače ''component''"}, {"ER_CAN_ONLY_OUTPUT_TO_ELEMENT", "U atributů Element, DocumentFragment, Document a PrintWriter lze volat pouze výstup."}, {"ER_PROCESS_ERROR", "Chyba: StylesheetRoot.process"}, {"ER_UNIMPLNODE_ERROR", "Chyba: UnImplNode: {0}"}, {"ER_NO_SELECT_EXPRESSION", "Chyba! Nebyl nalezen výraz výběru xpath (-select)."}, {"ER_CANNOT_SERIALIZE_XSLPROCESSOR", "Nelze serializovat XSLProcessor!"}, {"ER_NO_INPUT_STYLESHEET", "Nebyl zadán vstup předlohy se styly!"}, {"ER_FAILED_PROCESS_STYLESHEET", "Nepodařilo se zpracovat předlohu se styly!"}, {"ER_COULDNT_PARSE_DOC", "Nelze analyzovat dokument {0}!"}, {"ER_COULDNT_FIND_FRAGMENT", "Nelze nalézt fragment: {0}"}, {"ER_NODE_NOT_ELEMENT", "Uzel, na který odkazuje identifikátor fragmentu, není prvek: {0}"}, {"ER_FOREACH_NEED_MATCH_OR_NAME_ATTRIB", "atribut for-each musí mít buď shodu nebo název atributu"}, {"ER_TEMPLATES_NEED_MATCH_OR_NAME_ATTRIB", "atribut templates musí mít buď shodu nebo název atributu"}, {"ER_NO_CLONE_OF_DOCUMENT_FRAG", "Žádný klon fragmentu dokumentu!"}, {"ER_CANT_CREATE_ITEM", "Ve stromu výsledků nelze vytvořit položku: {0}"}, {"ER_XMLSPACE_ILLEGAL_VALUE", "Parametr xml:space ve zdrojovém XML má neplatnou hodnotu: {0}"}, {"ER_NO_XSLKEY_DECLARATION", "{0} nemá deklarován žádný parametr xsl:key!"}, {"ER_CANT_CREATE_URL", "Chyba! Nelze vytvořit url pro: {0}"}, {"ER_XSLFUNCTIONS_UNSUPPORTED", "Nepodporovaná funkce xsl:functions"}, {"ER_PROCESSOR_ERROR", "Chyba: XSLT TransformerFactory"}, {"ER_NOT_ALLOWED_INSIDE_STYLESHEET", "(StylesheetHandler) {0} - není v rámci předlohy se styly povoleno!"}, {"ER_RESULTNS_NOT_SUPPORTED", "Parametr result-ns již není podporován! Místo toho použijte parametr xsl:output."}, {"ER_DEFAULTSPACE_NOT_SUPPORTED", "Parametr default-space již není podporován! Místo toho použijte parametr xsl:strip-space nebo xsl:preserve-space."}, {"ER_INDENTRESULT_NOT_SUPPORTED", "Parametr indent-result již není podporován! Místo toho použijte parametr xsl:output."}, {"ER_ILLEGAL_ATTRIB", "(StylesheetHandler) {0} má neplatný atribut: {1}"}, {"ER_UNKNOWN_XSL_ELEM", "Neznámý prvek XSL: {0}"}, {"ER_BAD_XSLSORT_USE", "(StylesheetHandler) Parametr xsl:sort lze použít pouze s parametrem xsl:apply-templates nebo xsl:for-each."}, {"ER_MISPLACED_XSLWHEN", "(StylesheetHandler) Nesprávně umístěný prvek xsl:when!"}, {"ER_XSLWHEN_NOT_PARENTED_BY_XSLCHOOSE", "(StylesheetHandler) Prvkek xsl:when nemá v parametru xsl:choose žádného rodiče!"}, {"ER_MISPLACED_XSLOTHERWISE", "(StylesheetHandler) Nesprávně umístěný prvek xsl:otherwise!"}, {"ER_XSLOTHERWISE_NOT_PARENTED_BY_XSLCHOOSE", "(StylesheetHandler) Prvek xsl:otherwise nemá v parametru xsl:choose žádného rodiče!"}, {"ER_NOT_ALLOWED_INSIDE_TEMPLATE", "(StylesheetHandler) {0} - není v rámci šablony povoleno!"}, {"ER_UNKNOWN_EXT_NS_PREFIX", "(StylesheetHandler) {0}: neznámá předpona {1} přípony oboru názvů"}, {"ER_IMPORTS_AS_FIRST_ELEM", "(StylesheetHandler) Importy musí být v rámci šablony se styly na prvních místech!"}, {"ER_IMPORTING_ITSELF", "(StylesheetHandler) {0}: přímo nebo nepřímo importuje samo sebe!"}, {"ER_XMLSPACE_ILLEGAL_VAL", "(StylesheetHandler) Parametr xml:space má neplatnou hodnotu: {0}"}, {"ER_PROCESSSTYLESHEET_NOT_SUCCESSFUL", "Neúspěšný proces processStylesheet!"}, {"ER_SAX_EXCEPTION", "Výjimka SAX"}, {"ER_XSLT_ERROR", "Chyba XSLT"}, {"ER_CURRENCY_SIGN_ILLEGAL", "znak měny není v řetězci vzorku formátu povolen"}, {"ER_DOCUMENT_FUNCTION_INVALID_IN_STYLESHEET_DOM", "Funkce Document není v předloze se styly DOM podporována!"}, {"ER_CANT_RESOLVE_PREFIX_OF_NON_PREFIX_RESOLVER", "Nelze přeložit předponu překladače non-Prefix!"}, {"ER_REDIRECT_COULDNT_GET_FILENAME", "Přesměrování přípony: Nelze získat název souboru - atribut file nebo select musí vrátit platný řetězec."}, {"ER_CANNOT_BUILD_FORMATTERLISTENER_IN_REDIRECT", "V příponě Redirect nelze vytvořit FormatterListener!"}, {"ER_INVALID_PREFIX_IN_EXCLUDERESULTPREFIX", "Neplatná předpona ve funkci exclude-result-prefixes: {0}"}, {"ER_MISSING_NS_URI", "U zadané předpony chybí obor názvů URI"}, {"ER_MISSING_ARG_FOR_OPTION", "Chybějící argument volby: {0}"}, {"ER_INVALID_OPTION", "Neplatná volba: {0}"}, {"ER_MALFORMED_FORMAT_STRING", "Vadný formátovací řetězec: {0}"}, {"ER_STYLESHEET_REQUIRES_VERSION_ATTRIB", "Prvek xsl:stylesheet vyžaduje atribut 'version'!"}, {"ER_ILLEGAL_ATTRIBUTE_VALUE", "Parametr Attribute: {0} má neplatnou hodnotu: {1}"}, {"ER_CHOOSE_REQUIRES_WHEN", "Prvek xsl:choose vyžaduje parametr xsl:when"}, {"ER_NO_APPLY_IMPORT_IN_FOR_EACH", "Parametr xsl:for-each není v xsl:apply-imports povolen"}, {"ER_CANT_USE_DTM_FOR_OUTPUT", "Nelze použít DTMLiaison u výstupu uzlu DOM node... Místo toho použijte org.apache.xpath.DOM2Helper!"}, {"ER_CANT_USE_DTM_FOR_INPUT", "Nelze použít DTMLiaison u vstupu uzlu DOM node... Místo toho použijte org.apache.xpath.DOM2Helper!"}, {"ER_CALL_TO_EXT_FAILED", "Neúspěšné volání prvku přípony: {0}"}, {"ER_PREFIX_MUST_RESOLVE", "Předponu musí být možno přeložit do oboru názvů: {0}"}, {"ER_INVALID_UTF16_SURROGATE", "Byla zjištěna neplatná náhrada UTF-16: {0} ?"}, {"ER_XSLATTRSET_USED_ITSELF", "Prvek xsl:attribute-set {0} používá sám sebe, což způsobí nekonečnou smyčku."}, {"ER_CANNOT_MIX_XERCESDOM", "Vstup Xerces-DOM nelze směšovat s výstupem Xerces-DOM!"}, {"ER_TOO_MANY_LISTENERS", "addTraceListenersToStylesheet - TooManyListenersException"}, {"ER_IN_ELEMTEMPLATEELEM_READOBJECT", "V ElemTemplateElement.readObject: {0}"}, {"ER_DUPLICATE_NAMED_TEMPLATE", "Nalezena více než jedna šablona s názvem: {0}"}, {"ER_INVALID_KEY_CALL", "Neplatné volání funkce: rekurzivní volání funkce key() není povoleno"}, {"ER_REFERENCING_ITSELF", "Proměnná {0} odkazuje přímo či nepřímo sama na sebe!"}, {"ER_ILLEGAL_DOMSOURCE_INPUT", "Vstupní uzel DOMSource pro newTemplates nesmí mít hodnotu null!"}, {"ER_CLASS_NOT_FOUND_FOR_OPTION", "Nebyl nalezen soubor třídy pro volbu {0}"}, {"ER_REQUIRED_ELEM_NOT_FOUND", "Nebyl nalezen požadovaný prvek: {0}"}, {"ER_INPUT_CANNOT_BE_NULL", "Parametr InputStream nesmí mít hodnotu null"}, {"ER_URI_CANNOT_BE_NULL", "Parametr URI nesmí mít hodnotu null"}, {"ER_FILE_CANNOT_BE_NULL", "Parametr File nesmí mít hodnotu null"}, {"ER_SOURCE_CANNOT_BE_NULL", "Parametr InputSource nesmí mít hodnotu null"}, {"ER_CANNOT_INIT_BSFMGR", "Nelze inicializovat BSF Manager"}, {"ER_CANNOT_CMPL_EXTENSN", "Příponu nelze kompilovat"}, {"ER_CANNOT_CREATE_EXTENSN", "Nelze vytvořit příponu: {0}, protože: {1}"}, {"ER_INSTANCE_MTHD_CALL_REQUIRES", "Volání metody {0} metodou Instance vyžaduje jako první argument instanci Object"}, {"ER_INVALID_ELEMENT_NAME", "Byl zadán neplatný název prvku {0}"}, {"ER_ELEMENT_NAME_METHOD_STATIC", "Název metody prvku musí být static {0}"}, {"ER_EXTENSION_FUNC_UNKNOWN", "Funkce výjimky {0} : {1} je neznámá"}, {"ER_MORE_MATCH_CONSTRUCTOR", "Konstruktor {0} má více nejlepších shod."}, {"ER_MORE_MATCH_METHOD", "Metoda {0} má více nejlepších shod."}, {"ER_MORE_MATCH_ELEMENT", "Metoda prvku {0} má více nejlepších shod."}, {"ER_INVALID_CONTEXT_PASSED", "Do vyhodnocení byl předán neplatný kontext {0}."}, {"ER_POOL_EXISTS", "Společná oblast již existuje."}, {"ER_NO_DRIVER_NAME", "Nebylo zadáno žádné jméno ovladače."}, {"ER_NO_URL", "Nebyla specifikována žádná adresa URL."}, {"ER_POOL_SIZE_LESSTHAN_ONE", "Velikost společné oblasti je menší než jedna!"}, {"ER_INVALID_DRIVER", "Byl zadán neplatný název ovladače!"}, {"ER_NO_STYLESHEETROOT", "Nebyl nalezen kořen předlohy se styly!"}, {"ER_ILLEGAL_XMLSPACE_VALUE", "Neplatná hodnota parametru xml:space"}, {"ER_PROCESSFROMNODE_FAILED", "Selhání procesu processFromNode"}, {"ER_RESOURCE_COULD_NOT_LOAD", "Nelze zavést zdroj [ {0} ]: {1} \n {2} \t {3}"}, {"ER_BUFFER_SIZE_LESSTHAN_ZERO", "Velikost vyrovnávací paměti <=0"}, {"ER_UNKNOWN_ERROR_CALLING_EXTENSION", "Při volání přípony došlo k neznámé chybě"}, {"ER_NO_NAMESPACE_DECL", "Předpona {0} nemá deklarován odpovídající obor názvů"}, {"ER_ELEM_CONTENT_NOT_ALLOWED", "Obsah prvku není povolen pro lang=javaclass {0}"}, {"ER_STYLESHEET_DIRECTED_TERMINATION", "Ukončení směrované na předlohu se styly."}, {"ER_ONE_OR_TWO", "1 nebo 2"}, {"ER_TWO_OR_THREE", "2 nebo 3"}, {"ER_COULD_NOT_LOAD_RESOURCE", "Nelze zavést {0} (zkontrolujte proměnnou CLASSPATH) - proto se používají pouze výchozí hodnoty"}, {"ER_CANNOT_INIT_DEFAULT_TEMPLATES", "Nelze aktualizovat výchozí šablony."}, {"ER_RESULT_NULL", "Výsledek by neměl mít hodnotu null"}, {"ER_RESULT_COULD_NOT_BE_SET", "Nelze nastavit výsledek"}, {"ER_NO_OUTPUT_SPECIFIED", "Nebyl určen žádný výstup"}, {"ER_CANNOT_TRANSFORM_TO_RESULT_TYPE", "Nelze převést na výsledek typu {0}"}, {"ER_CANNOT_TRANSFORM_SOURCE_TYPE", "Nelze převést na zdroj typu {0}"}, {"ER_NULL_CONTENT_HANDLER", "Obslužný program obsahu hodnoty null"}, {"ER_NULL_ERROR_HANDLER", "Obslužný program pro zpracování chyb hodnoty null"}, {"ER_CANNOT_CALL_PARSE", "Není-li nastaven obslužný program ContentHandler, nelze volat analyzátor."}, {"ER_NO_PARENT_FOR_FILTER", "Filtr nemá rodiče."}, {"ER_NO_STYLESHEET_IN_MEDIA", "Nebyla nalezena předloha se styly v: {0}, médium= {1}"}, {"ER_NO_STYLESHEET_PI", "Nebyla nalezena předloha se styly xml-stylesheet PI v: {0}"}, {"ER_NOT_SUPPORTED", "Nepodporováno: {0}"}, {"ER_PROPERTY_VALUE_BOOLEAN", "Hodnota vlastnosti {0} by měla být booleovská instance"}, {"ER_COULD_NOT_FIND_EXTERN_SCRIPT", "Z {0} nelze získat externí skript."}, {"ER_RESOURCE_COULD_NOT_FIND", "Nelze najít zdroj [ {0} ].\n {1}"}, {"ER_OUTPUT_PROPERTY_NOT_RECOGNIZED", "Neznámá vlastnost výstupu: {0}"}, {"ER_FAILED_CREATING_ELEMLITRSLT", "Nepodařilo se vytvořit instanci ElemLiteralResult"}, {"ER_VALUE_SHOULD_BE_NUMBER", "Hodnota pro {0} by měla obsahovat analyzovatelné číslo"}, {"ER_VALUE_SHOULD_EQUAL", "Hodnota {0} musí být yes nebo no."}, {"ER_FAILED_CALLING_METHOD", "Volání metody {0} selhalo."}, {"ER_FAILED_CREATING_ELEMTMPL", "Nepodařilo se vytvořit instanci ElemTemplateElement."}, {"ER_CHARS_NOT_ALLOWED", "V této části dokumentu nejsou znaky povoleny."}, {"ER_ATTR_NOT_ALLOWED", "Atribut \"{0}\" není u prvku {1} povolen!"}, {"ER_BAD_VALUE", "{0}: nesprávná hodnota {1} "}, {"ER_ATTRIB_VALUE_NOT_FOUND", "Atribut hodnoty ({0}) nebyl nalezen "}, {"ER_ATTRIB_VALUE_NOT_RECOGNIZED", "Atribut hodnoty ({0}) nebyl rozpoznán "}, {"ER_NULL_URI_NAMESPACE", "Pokus o generování oboru názvů s URI s hodnotou null."}, {"ER_NUMBER_TOO_BIG", "Pokus o formátování většího čísla, než je největší dlouhé celé číslo."}, {"ER_CANNOT_FIND_SAX1_DRIVER", "Nelze najít třídu ovladače SAX1  {0}"}, {"ER_SAX1_DRIVER_NOT_LOADED", "Třída ovladače SAX1 {0} byla nalezena, ale nebylo možno ji zavést."}, {"ER_SAX1_DRIVER_NOT_INSTANTIATED", "Třída ovladače SAX1 {0} byla nalezena, ale nebylo možno s ní založit instanci."}, {"ER_SAX1_DRIVER_NOT_IMPLEMENT_PARSER", "Třída ovladače SAX1 {0} neimplementuje org.xml.sax.Parser."}, {"ER_PARSER_PROPERTY_NOT_SPECIFIED", "Nebyla určena vlastnost systému org.xml.sax.parser."}, {"ER_PARSER_ARG_CANNOT_BE_NULL", "Argument analyzátoru nesmí mít hodnotu null."}, {"ER_FEATURE", "Funkce: {0}"}, {"ER_PROPERTY", "Vlastnost: {0}"}, {"ER_NULL_ENTITY_RESOLVER", "Řešitel s hodnotou entity null"}, {"ER_NULL_DTD_HANDLER", "Obslužný program DTD s hodnotou null"}, {"ER_NO_DRIVER_NAME_SPECIFIED", "Nebyl zadán název ovladače!"}, {"ER_NO_URL_SPECIFIED", "Nebyla specifikována adresa URL!"}, {"ER_POOLSIZE_LESS_THAN_ONE", "Velikost společné oblasti je menší než 1!"}, {"ER_INVALID_DRIVER_NAME", "Zadán neplatný název ovladače!"}, {"ER_ERRORLISTENER", "ErrorListener"}, {"ER_ASSERT_NO_TEMPLATE_PARENT", "Chyba programátora! Výraz nemá rodiče ElemTemplateElement!"}, {"ER_ASSERT_REDUNDENT_EXPR_ELIMINATOR", "Tvrzení programátora v RundundentExprEliminator: {0}"}, {"ER_NOT_ALLOWED_IN_POSITION", "{0} - není povoleno v tomto stylu na daném místě!"}, {"ER_NONWHITESPACE_NOT_ALLOWED_IN_POSITION", "Neprázdný text není povolen v tomto stylu na daném místě!"}, {"INVALID_TCHAR", "Neplatná hodnota: {1} použito pro atribut CHAR: {0}. Atribut typu CHAR smí mít pouze jeden znak."}, {"INVALID_QNAME", "Neplatná hodnota: {1} použito pro atribut QNAME: {0}"}, {"INVALID_ENUM", "Neplatná hodnota: {1} použito pro atribut ENUM {0}. Platné hodnoty jsou: {2}."}, {"INVALID_NMTOKEN", "Neplatná hodnota: {1} použito pro atribut NMTOKEN: {0} "}, {"INVALID_NCNAME", "Neplatná hodnota: {1} použito pro atribut NCNAME: {0} "}, {"INVALID_BOOLEAN", "Neplatná hodnota: {1} použito pro booleovský atribut: {0} "}, {"INVALID_NUMBER", "Neplatná hodnota: {1} použito pro atribut čísla: {0} "}, {"ER_ARG_LITERAL", "Argument pro {0} ve vyhovujícím vzorku musí být typu literal."}, {"ER_DUPLICATE_GLOBAL_VAR", "Duplicitní deklarace globální proměnné."}, {"ER_DUPLICATE_VAR", "Duplicitní deklarace proměnné."}, {"ER_TEMPLATE_NAME_MATCH", "Prvek xsl:template musí mít název nebo odpovídající atribut (nebo obojí)"}, {"ER_INVALID_PREFIX", "Neplatná předpona ve funkci exclude-result-prefixes: {0}"}, {"ER_NO_ATTRIB_SET", "sada atributů pojmenovaná {0} neexistuje"}, {"WG_FOUND_CURLYBRACE", "Byl nalezen znak '}', ale není otevřena žádná šablona atributu!"}, {"WG_COUNT_ATTRIB_MATCHES_NO_ANCESTOR", "Varování: čítač atributu se neshoduje s předchůdcem v xsl:number! Cíl = {0}"}, {"WG_EXPR_ATTRIB_CHANGED_TO_SELECT", "Stará syntaxe: Název atributu 'expr' byl změněn na 'select'."}, {"WG_NO_LOCALE_IN_FORMATNUMBER", "Xalan ještě neobsluhuje název národního prostředí ve funkci format-number."}, {"WG_LOCALE_NOT_FOUND", "Varování: Nebylo nalezeno národní prostředí pro parametr xml:lang={0}"}, {"WG_CANNOT_MAKE_URL_FROM", "Nelze vytvořit adresu URL z: {0}"}, {"WG_CANNOT_LOAD_REQUESTED_DOC", "Požadovaný dokument nelze načíst: {0}"}, {"WG_CANNOT_FIND_COLLATOR", "Nelze najít funkci Collator pro <sort xml:lang={0}"}, {"WG_FUNCTIONS_SHOULD_USE_URL", "Stará syntaxe: instrukce funkcí by měla používat adresu url {0}"}, {"WG_ENCODING_NOT_SUPPORTED_USING_UTF8", "nepodporované kódování: {0}, použito kódování UTF-8"}, {"WG_ENCODING_NOT_SUPPORTED_USING_JAVA", "nepodporované kódování: {0}, použita Java {1}"}, {"WG_SPECIFICITY_CONFLICTS", "Byl nalezen konflikt specifičnosti: {0} Bude použit naposledy nalezený výskyt z předlohy se styly."}, {"WG_PARSING_AND_PREPARING", "========= Analýza a příprava {0} =========="}, {"WG_ATTR_TEMPLATE", "Šablona atributů, {0}"}, {"WG_CONFLICT_BETWEEN_XSLSTRIPSPACE_AND_XSLPRESERVESP", "Konflikt souladu funkcí xsl:strip-space a xsl:preserve-space"}, {"WG_ATTRIB_NOT_HANDLED", "Xalan prozatím neobsluhuje atribut {0}!"}, {"WG_NO_DECIMALFORMAT_DECLARATION", "U desetinného formátu nebyla nalezena žádná deklarace: {0}"}, {"WG_OLD_XSLT_NS", "Chybějící nebo nesprávný obor názvů XSLT. "}, {"WG_ONE_DEFAULT_XSLDECIMALFORMAT_ALLOWED", "Povolena je pouze výchozí deklarace prvku xsl:decimal-format."}, {"WG_XSLDECIMALFORMAT_NAMES_MUST_BE_UNIQUE", "Názvy prvků xsl:decimal-format musí být jedinečné. Byla vytvořena kopie názvu \"{0}\"."}, {"WG_ILLEGAL_ATTRIBUTE", "{0} má neplatný atribut: {1}"}, {"WG_COULD_NOT_RESOLVE_PREFIX", "Nelze přeložit předponu oboru názvů: {0}. Uzel bude ignorován."}, {"WG_STYLESHEET_REQUIRES_VERSION_ATTRIB", "Prvek xsl:stylesheet vyžaduje atribut 'version'!"}, {"WG_ILLEGAL_ATTRIBUTE_NAME", "Neplatný název atributu: {0}"}, {"WG_ILLEGAL_ATTRIBUTE_VALUE", "V atributu {0} byla použita neplatná hodnota: {1}"}, {"WG_EMPTY_SECOND_ARG", "Výsledné nastavení uzlu z druhého argumentu dokumentu je prázdné. Vrátí se prázdná sada uzlů."}, {"WG_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML", "Hodnota atributu 'name' názvu prvku xsl:processing-instruction nesmí být 'xml'"}, {"WG_PROCESSINGINSTRUCTION_NOTVALID_NCNAME", "Hodnota atributu 'name' instrukce xsl:processing-instruction musí být platným názvem NCName: {0}"}, {"WG_ILLEGAL_ATTRIBUTE_POSITION", "Nelze přidat atribut {0} po uzlech potomků ani před tím, než je vytvořen prvek. Atribut bude ignorován."}, {"ui_language", "cs"}, {"help_language", "cs"}, {"language", "cs"}, {"BAD_CODE", "Parametr funkce createMessage je mimo limit"}, {"FORMAT_FAILED", "Při volání funkce messageFormat došlo k výjimce"}, {"version", ">>>>>>> Verze Xalan "}, {"version2", "<<<<<<<"}, {"yes", "ano"}, {"line", "Řádek #"}, {"column", "Sloupec #"}, {"xsldone", "XSLProcessor: hotovo"}, {"xslProc_option", "Příkazový řádek Xalan-J: Zpracování voleb třídy:"}, {"xslProc_option", "Příkazový řádek Xalan-J: Zpracování voleb třídy:"}, {"xslProc_invalid_xsltc_option", "Volba {0} není v režimu XSLTC podporovaná."}, {"xslProc_invalid_xalan_option", "Volba {0} může být použita pouze s -XSLTC."}, {"xslProc_no_input", "Chyba: Žádná předloha stylu ani vstup xml nejsou určeny. K zobrazení pokynů spusťte tento příkaz bez jakékoliv volby."}, {"xslProc_common_options", "-Obecné volby-"}, {"xslProc_xalan_options", "-Volby pro Xalan-"}, {"xslProc_xsltc_options", "-Volby pro XSLTC-"}, {"xslProc_return_to_continue", "(pokračujte stisknutím klávesy <Enter>)"}, {"optionXSLTC", "   [-XSLTC (použije XSLTC pro transformaci)]"}, {"optionIN", "   [-IN inputXMLURL]"}, {"optionXSL", "   [-XSL XSLTransformationURL]"}, {"optionOUT", "   [-OUT outputFileName]"}, {"optionLXCIN", "   [-LXCIN compiledStylesheetFileNameIn]"}, {"optionLXCOUT", "   [-LXCOUT compiledStylesheetFileNameOutOut]"}, {"optionPARSER", "   [-PARSER plně kvalifikovaný název třídy spojení analyzátoru]"}, {"optionE", "   [-E (nerozšiřovat odkazy entity)]"}, {"optionV", "   [-E (nerozšiřovat odkazy entity)]"}, {"optionQC", "   [-QC (varování před konflikty vzorkování v tichém režimu)]"}, {"optionQ", "   [-Q  (tichý režim)]"}, {"optionLF", "   [-LF (ve výstupu použít pouze řádkování - LF {výchozí nastavení je CR/LF})]"}, {"optionCR", "   [-CR (ve výstupu použít pouze znak nový řádek - CR {výchozí nastavení je CR/LF})]"}, {"optionESCAPE", "   [-ESCAPE (nastavení znaků escape sekvence {výchozí nastavení je <>&\"'\\r\\n}]"}, {"optionINDENT", "   [-INDENT (ovlivňuje počet znaků odsazení {výchozí nastavení je 0})]"}, {"optionTT", "   [-TT (trasuje šablony při volání)]"}, {"optionTG", "   [-TG (trasuje všechny události generování)]"}, {"optionTS", "   [-TS (trasuje všechny události výběru)]"}, {"optionTTC", "   [-TTC (trasuje potomky šablony v průběhu jejich zpracování)]"}, {"optionTCLASS", "   [-TCLASS (třída TraceListener přípon trasování)]"}, {"optionVALIDATE", "   [-VALIDATE (zapíná/vypíná validaci;  výchozí nastavení je vypnuto)]"}, {"optionEDUMP", "   [-EDUMP {volitelný název souboru} (při chybě vypíše obsah zásobníku)]"}, {"optionXML", "   [-XML (použije program pro formátování XML a přidá záhlaví XML)]"}, {"optionTEXT", "   [-TEXT (použije jednoduchý program pro formátování textu)]"}, {"optionHTML", "   [-HTML (použije program pro formátování HTML)]"}, {"optionPARAM", "   [-PARAM název výrazu (nastaví parametr předlohy se styly)]"}, {"noParsermsg1", "Proces XSL nebyl úspěšný."}, {"noParsermsg2", "** Nelze najít analyzátor **"}, {"noParsermsg3", "Zkontrolujte cestu classpath."}, {"noParsermsg4", "Nemáte-li analyzátor XML jazyka Java společnosti IBM, můžete si jej stáhnout z adresy:"}, {"noParsermsg5", "AlphaWorks: http://www.alphaworks.ibm.com/formula/xml"}, {"optionURIRESOLVER", "   [-URIRESOLVER celé jméno třídy (pro překlad URI použije funkci URIResolver)]"}, {"optionENTITYRESOLVER", "   [-ENTITYRESOLVER celé jméno třídy (pro překlad entit použije funkci EntityResolver)]"}, {"optionCONTENTHANDLER", "   [-CONTENTHANDLER celé jméno třídy (pro serializaci výstupu použije funkci ContentHandler)]"}, {"optionLINENUMBERS", "   [-L ve zdrojovém dokumentu použije čísla řádků]"}, {"optionMEDIA", "   [-MEDIA mediaType (k vyhledání předlohy se styly přiřazené dokumentu použije atribut média)]"}, {"optionFLAVOR", "   [-FLAVOR flavorName (při transformaci se explicitně použije s2s=SAX nebo d2d=DOM)] "}, {"optionDIAG", "   [-DIAG (vytiskne čas transformace v milisekundách)]"}, {"optionINCREMENTAL", "   [-INCREMENTAL (vyžaduje inkrementální konstrukci DTM nastavením hodnoty http://xml.apache.org/xalan/features/incremental na true)]"}, {"optionNOOPTIMIMIZE", "   [-NOOPTIMIMIZE (vyžaduje optimalizaci předlohy se styly nastavením hodnoty http://xml.apache.org/xalan/features/optimize na false)]"}, {"optionRL", "   [-RL recursionlimit (potvrdí číselný limit hloubky předlohy se styly)]"}, {"optionXO", "   [-XO [transletName] (přiřadí název k generovanému transletu)]"}, {"optionXD", "   [-XD destinationDirectory (určuje cílový adresář pro translet)]"}, {"optionXJ", "   [-XJ jarfile (zabalí třídy transletu do souboru jar s názvem <jarfile>)]"}, {"optionXP", "   [-XP package (určí předponu názvu sady pro všechny generované třídy transletu)]"}, {"optionXN", "   [-XN (povolí zarovnání šablon)]"}, {"optionXX", "   [-XX (zapne další výstup zpráv ladění)]"}, {"optionXT", "   [-XT (Použije translet k transformaci, je-li to možné)]"}, {"diagTiming", " --------- Transformace {0} pomocí {1} trvala {2} ms."}, {"recursionTooDeep", "Vnoření šablon je příliš hluboké. Vnoření = {0}, šablona {1} {2}"}, {"nameIs", "název je"}, {"matchPatternIs", "vzorek shody je"}};
   }

   public static final XSLTErrorResources loadResourceBundle(String className) throws MissingResourceException {
      Locale locale = Locale.getDefault();
      String suffix = getResourceSuffix(locale);

      try {
         return (XSLTErrorResources)ResourceBundle.getBundle(className + suffix, locale);
      } catch (MissingResourceException var6) {
         try {
            return (XSLTErrorResources)ResourceBundle.getBundle(className, new Locale("cs", "CZ"));
         } catch (MissingResourceException var5) {
            throw new MissingResourceException("Could not load any resource bundles.", className, "");
         }
      }
   }

   private static final String getResourceSuffix(Locale locale) {
      String suffix = "_" + locale.getLanguage();
      String country = locale.getCountry();
      if (country.equals("TW")) {
         suffix = suffix + "_" + country;
      }

      return suffix;
   }
}
