package org.apache.xalan.res;

import java.util.ListResourceBundle;
import java.util.Locale;
import java.util.MissingResourceException;
import java.util.ResourceBundle;

public class XSLTErrorResources_es extends ListResourceBundle {
   public static final int MAX_CODE = 201;
   public static final int MAX_WARNING = 29;
   public static final int MAX_OTHERS = 55;
   public static final int MAX_MESSAGES = 231;
   public static final String ER_NO_CURLYBRACE = "ER_NO_CURLYBRACE";
   public static final String ER_ILLEGAL_ATTRIBUTE = "ER_ILLEGAL_ATTRIBUTE";
   public static final String ER_NULL_SOURCENODE_APPLYIMPORTS = "ER_NULL_SOURCENODE_APPLYIMPORTS";
   public static final String ER_CANNOT_ADD = "ER_CANNOT_ADD";
   public static final String ER_NULL_SOURCENODE_HANDLEAPPLYTEMPLATES = "ER_NULL_SOURCENODE_HANDLEAPPLYTEMPLATES";
   public static final String ER_NO_NAME_ATTRIB = "ER_NO_NAME_ATTRIB";
   public static final String ER_TEMPLATE_NOT_FOUND = "ER_TEMPLATE_NOT_FOUND";
   public static final String ER_CANT_RESOLVE_NAME_AVT = "ER_CANT_RESOLVE_NAME_AVT";
   public static final String ER_REQUIRES_ATTRIB = "ER_REQUIRES_ATTRIB";
   public static final String ER_MUST_HAVE_TEST_ATTRIB = "ER_MUST_HAVE_TEST_ATTRIB";
   public static final String ER_BAD_VAL_ON_LEVEL_ATTRIB = "ER_BAD_VAL_ON_LEVEL_ATTRIB";
   public static final String ER_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML = "ER_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML";
   public static final String ER_PROCESSINGINSTRUCTION_NOTVALID_NCNAME = "ER_PROCESSINGINSTRUCTION_NOTVALID_NCNAME";
   public static final String ER_NEED_MATCH_ATTRIB = "ER_NEED_MATCH_ATTRIB";
   public static final String ER_NEED_NAME_OR_MATCH_ATTRIB = "ER_NEED_NAME_OR_MATCH_ATTRIB";
   public static final String ER_CANT_RESOLVE_NSPREFIX = "ER_CANT_RESOLVE_NSPREFIX";
   public static final String ER_ILLEGAL_VALUE = "ER_ILLEGAL_VALUE";
   public static final String ER_NO_OWNERDOC = "ER_NO_OWNERDOC";
   public static final String ER_ELEMTEMPLATEELEM_ERR = "ER_ELEMTEMPLATEELEM_ERR";
   public static final String ER_NULL_CHILD = "ER_NULL_CHILD";
   public static final String ER_NEED_SELECT_ATTRIB = "ER_NEED_SELECT_ATTRIB";
   public static final String ER_NEED_TEST_ATTRIB = "ER_NEED_TEST_ATTRIB";
   public static final String ER_NEED_NAME_ATTRIB = "ER_NEED_NAME_ATTRIB";
   public static final String ER_NO_CONTEXT_OWNERDOC = "ER_NO_CONTEXT_OWNERDOC";
   public static final String ER_COULD_NOT_CREATE_XML_PROC_LIAISON = "ER_COULD_NOT_CREATE_XML_PROC_LIAISON";
   public static final String ER_PROCESS_NOT_SUCCESSFUL = "ER_PROCESS_NOT_SUCCESSFUL";
   public static final String ER_NOT_SUCCESSFUL = "ER_NOT_SUCCESSFUL";
   public static final String ER_ENCODING_NOT_SUPPORTED = "ER_ENCODING_NOT_SUPPORTED";
   public static final String ER_COULD_NOT_CREATE_TRACELISTENER = "ER_COULD_NOT_CREATE_TRACELISTENER";
   public static final String ER_KEY_REQUIRES_NAME_ATTRIB = "ER_KEY_REQUIRES_NAME_ATTRIB";
   public static final String ER_KEY_REQUIRES_MATCH_ATTRIB = "ER_KEY_REQUIRES_MATCH_ATTRIB";
   public static final String ER_KEY_REQUIRES_USE_ATTRIB = "ER_KEY_REQUIRES_USE_ATTRIB";
   public static final String ER_REQUIRES_ELEMENTS_ATTRIB = "ER_REQUIRES_ELEMENTS_ATTRIB";
   public static final String ER_MISSING_PREFIX_ATTRIB = "ER_MISSING_PREFIX_ATTRIB";
   public static final String ER_BAD_STYLESHEET_URL = "ER_BAD_STYLESHEET_URL";
   public static final String ER_FILE_NOT_FOUND = "ER_FILE_NOT_FOUND";
   public static final String ER_IOEXCEPTION = "ER_IOEXCEPTION";
   public static final String ER_NO_HREF_ATTRIB = "ER_NO_HREF_ATTRIB";
   public static final String ER_STYLESHEET_INCLUDES_ITSELF = "ER_STYLESHEET_INCLUDES_ITSELF";
   public static final String ER_PROCESSINCLUDE_ERROR = "ER_PROCESSINCLUDE_ERROR";
   public static final String ER_MISSING_LANG_ATTRIB = "ER_MISSING_LANG_ATTRIB";
   public static final String ER_MISSING_CONTAINER_ELEMENT_COMPONENT = "ER_MISSING_CONTAINER_ELEMENT_COMPONENT";
   public static final String ER_CAN_ONLY_OUTPUT_TO_ELEMENT = "ER_CAN_ONLY_OUTPUT_TO_ELEMENT";
   public static final String ER_PROCESS_ERROR = "ER_PROCESS_ERROR";
   public static final String ER_UNIMPLNODE_ERROR = "ER_UNIMPLNODE_ERROR";
   public static final String ER_NO_SELECT_EXPRESSION = "ER_NO_SELECT_EXPRESSION";
   public static final String ER_CANNOT_SERIALIZE_XSLPROCESSOR = "ER_CANNOT_SERIALIZE_XSLPROCESSOR";
   public static final String ER_NO_INPUT_STYLESHEET = "ER_NO_INPUT_STYLESHEET";
   public static final String ER_FAILED_PROCESS_STYLESHEET = "ER_FAILED_PROCESS_STYLESHEET";
   public static final String ER_COULDNT_PARSE_DOC = "ER_COULDNT_PARSE_DOC";
   public static final String ER_COULDNT_FIND_FRAGMENT = "ER_COULDNT_FIND_FRAGMENT";
   public static final String ER_NODE_NOT_ELEMENT = "ER_NODE_NOT_ELEMENT";
   public static final String ER_FOREACH_NEED_MATCH_OR_NAME_ATTRIB = "ER_FOREACH_NEED_MATCH_OR_NAME_ATTRIB";
   public static final String ER_TEMPLATES_NEED_MATCH_OR_NAME_ATTRIB = "ER_TEMPLATES_NEED_MATCH_OR_NAME_ATTRIB";
   public static final String ER_NO_CLONE_OF_DOCUMENT_FRAG = "ER_NO_CLONE_OF_DOCUMENT_FRAG";
   public static final String ER_CANT_CREATE_ITEM = "ER_CANT_CREATE_ITEM";
   public static final String ER_XMLSPACE_ILLEGAL_VALUE = "ER_XMLSPACE_ILLEGAL_VALUE";
   public static final String ER_NO_XSLKEY_DECLARATION = "ER_NO_XSLKEY_DECLARATION";
   public static final String ER_CANT_CREATE_URL = "ER_CANT_CREATE_URL";
   public static final String ER_XSLFUNCTIONS_UNSUPPORTED = "ER_XSLFUNCTIONS_UNSUPPORTED";
   public static final String ER_PROCESSOR_ERROR = "ER_PROCESSOR_ERROR";
   public static final String ER_NOT_ALLOWED_INSIDE_STYLESHEET = "ER_NOT_ALLOWED_INSIDE_STYLESHEET";
   public static final String ER_RESULTNS_NOT_SUPPORTED = "ER_RESULTNS_NOT_SUPPORTED";
   public static final String ER_DEFAULTSPACE_NOT_SUPPORTED = "ER_DEFAULTSPACE_NOT_SUPPORTED";
   public static final String ER_INDENTRESULT_NOT_SUPPORTED = "ER_INDENTRESULT_NOT_SUPPORTED";
   public static final String ER_ILLEGAL_ATTRIB = "ER_ILLEGAL_ATTRIB";
   public static final String ER_UNKNOWN_XSL_ELEM = "ER_UNKNOWN_XSL_ELEM";
   public static final String ER_BAD_XSLSORT_USE = "ER_BAD_XSLSORT_USE";
   public static final String ER_MISPLACED_XSLWHEN = "ER_MISPLACED_XSLWHEN";
   public static final String ER_XSLWHEN_NOT_PARENTED_BY_XSLCHOOSE = "ER_XSLWHEN_NOT_PARENTED_BY_XSLCHOOSE";
   public static final String ER_MISPLACED_XSLOTHERWISE = "ER_MISPLACED_XSLOTHERWISE";
   public static final String ER_XSLOTHERWISE_NOT_PARENTED_BY_XSLCHOOSE = "ER_XSLOTHERWISE_NOT_PARENTED_BY_XSLCHOOSE";
   public static final String ER_NOT_ALLOWED_INSIDE_TEMPLATE = "ER_NOT_ALLOWED_INSIDE_TEMPLATE";
   public static final String ER_UNKNOWN_EXT_NS_PREFIX = "ER_UNKNOWN_EXT_NS_PREFIX";
   public static final String ER_IMPORTS_AS_FIRST_ELEM = "ER_IMPORTS_AS_FIRST_ELEM";
   public static final String ER_IMPORTING_ITSELF = "ER_IMPORTING_ITSELF";
   public static final String ER_XMLSPACE_ILLEGAL_VAL = "ER_XMLSPACE_ILLEGAL_VAL";
   public static final String ER_PROCESSSTYLESHEET_NOT_SUCCESSFUL = "ER_PROCESSSTYLESHEET_NOT_SUCCESSFUL";
   public static final String ER_SAX_EXCEPTION = "ER_SAX_EXCEPTION";
   public static final String ER_XSLT_ERROR = "ER_XSLT_ERROR";
   public static final String ER_CURRENCY_SIGN_ILLEGAL = "ER_CURRENCY_SIGN_ILLEGAL";
   public static final String ER_DOCUMENT_FUNCTION_INVALID_IN_STYLESHEET_DOM = "ER_DOCUMENT_FUNCTION_INVALID_IN_STYLESHEET_DOM";
   public static final String ER_CANT_RESOLVE_PREFIX_OF_NON_PREFIX_RESOLVER = "ER_CANT_RESOLVE_PREFIX_OF_NON_PREFIX_RESOLVER";
   public static final String ER_REDIRECT_COULDNT_GET_FILENAME = "ER_REDIRECT_COULDNT_GET_FILENAME";
   public static final String ER_CANNOT_BUILD_FORMATTERLISTENER_IN_REDIRECT = "ER_CANNOT_BUILD_FORMATTERLISTENER_IN_REDIRECT";
   public static final String ER_INVALID_PREFIX_IN_EXCLUDERESULTPREFIX = "ER_INVALID_PREFIX_IN_EXCLUDERESULTPREFIX";
   public static final String ER_MISSING_NS_URI = "ER_MISSING_NS_URI";
   public static final String ER_MISSING_ARG_FOR_OPTION = "ER_MISSING_ARG_FOR_OPTION";
   public static final String ER_INVALID_OPTION = "ER_INVALID_OPTION";
   public static final String ER_MALFORMED_FORMAT_STRING = "ER_MALFORMED_FORMAT_STRING";
   public static final String ER_STYLESHEET_REQUIRES_VERSION_ATTRIB = "ER_STYLESHEET_REQUIRES_VERSION_ATTRIB";
   public static final String ER_ILLEGAL_ATTRIBUTE_VALUE = "ER_ILLEGAL_ATTRIBUTE_VALUE";
   public static final String ER_CHOOSE_REQUIRES_WHEN = "ER_CHOOSE_REQUIRES_WHEN";
   public static final String ER_NO_APPLY_IMPORT_IN_FOR_EACH = "ER_NO_APPLY_IMPORT_IN_FOR_EACH";
   public static final String ER_CANT_USE_DTM_FOR_OUTPUT = "ER_CANT_USE_DTM_FOR_OUTPUT";
   public static final String ER_CANT_USE_DTM_FOR_INPUT = "ER_CANT_USE_DTM_FOR_INPUT";
   public static final String ER_CALL_TO_EXT_FAILED = "ER_CALL_TO_EXT_FAILED";
   public static final String ER_PREFIX_MUST_RESOLVE = "ER_PREFIX_MUST_RESOLVE";
   public static final String ER_INVALID_UTF16_SURROGATE = "ER_INVALID_UTF16_SURROGATE";
   public static final String ER_XSLATTRSET_USED_ITSELF = "ER_XSLATTRSET_USED_ITSELF";
   public static final String ER_CANNOT_MIX_XERCESDOM = "ER_CANNOT_MIX_XERCESDOM";
   public static final String ER_TOO_MANY_LISTENERS = "ER_TOO_MANY_LISTENERS";
   public static final String ER_IN_ELEMTEMPLATEELEM_READOBJECT = "ER_IN_ELEMTEMPLATEELEM_READOBJECT";
   public static final String ER_DUPLICATE_NAMED_TEMPLATE = "ER_DUPLICATE_NAMED_TEMPLATE";
   public static final String ER_INVALID_KEY_CALL = "ER_INVALID_KEY_CALL";
   public static final String ER_REFERENCING_ITSELF = "ER_REFERENCING_ITSELF";
   public static final String ER_ILLEGAL_DOMSOURCE_INPUT = "ER_ILLEGAL_DOMSOURCE_INPUT";
   public static final String ER_CLASS_NOT_FOUND_FOR_OPTION = "ER_CLASS_NOT_FOUND_FOR_OPTION";
   public static final String ER_REQUIRED_ELEM_NOT_FOUND = "ER_REQUIRED_ELEM_NOT_FOUND";
   public static final String ER_INPUT_CANNOT_BE_NULL = "ER_INPUT_CANNOT_BE_NULL";
   public static final String ER_URI_CANNOT_BE_NULL = "ER_URI_CANNOT_BE_NULL";
   public static final String ER_FILE_CANNOT_BE_NULL = "ER_FILE_CANNOT_BE_NULL";
   public static final String ER_SOURCE_CANNOT_BE_NULL = "ER_SOURCE_CANNOT_BE_NULL";
   public static final String ER_CANNOT_INIT_BSFMGR = "ER_CANNOT_INIT_BSFMGR";
   public static final String ER_CANNOT_CMPL_EXTENSN = "ER_CANNOT_CMPL_EXTENSN";
   public static final String ER_CANNOT_CREATE_EXTENSN = "ER_CANNOT_CREATE_EXTENSN";
   public static final String ER_INSTANCE_MTHD_CALL_REQUIRES = "ER_INSTANCE_MTHD_CALL_REQUIRES";
   public static final String ER_INVALID_ELEMENT_NAME = "ER_INVALID_ELEMENT_NAME";
   public static final String ER_ELEMENT_NAME_METHOD_STATIC = "ER_ELEMENT_NAME_METHOD_STATIC";
   public static final String ER_EXTENSION_FUNC_UNKNOWN = "ER_EXTENSION_FUNC_UNKNOWN";
   public static final String ER_MORE_MATCH_CONSTRUCTOR = "ER_MORE_MATCH_CONSTRUCTOR";
   public static final String ER_MORE_MATCH_METHOD = "ER_MORE_MATCH_METHOD";
   public static final String ER_MORE_MATCH_ELEMENT = "ER_MORE_MATCH_ELEMENT";
   public static final String ER_INVALID_CONTEXT_PASSED = "ER_INVALID_CONTEXT_PASSED";
   public static final String ER_POOL_EXISTS = "ER_POOL_EXISTS";
   public static final String ER_NO_DRIVER_NAME = "ER_NO_DRIVER_NAME";
   public static final String ER_NO_URL = "ER_NO_URL";
   public static final String ER_POOL_SIZE_LESSTHAN_ONE = "ER_POOL_SIZE_LESSTHAN_ONE";
   public static final String ER_INVALID_DRIVER = "ER_INVALID_DRIVER";
   public static final String ER_NO_STYLESHEETROOT = "ER_NO_STYLESHEETROOT";
   public static final String ER_ILLEGAL_XMLSPACE_VALUE = "ER_ILLEGAL_XMLSPACE_VALUE";
   public static final String ER_PROCESSFROMNODE_FAILED = "ER_PROCESSFROMNODE_FAILED";
   public static final String ER_RESOURCE_COULD_NOT_LOAD = "ER_RESOURCE_COULD_NOT_LOAD";
   public static final String ER_BUFFER_SIZE_LESSTHAN_ZERO = "ER_BUFFER_SIZE_LESSTHAN_ZERO";
   public static final String ER_UNKNOWN_ERROR_CALLING_EXTENSION = "ER_UNKNOWN_ERROR_CALLING_EXTENSION";
   public static final String ER_NO_NAMESPACE_DECL = "ER_NO_NAMESPACE_DECL";
   public static final String ER_ELEM_CONTENT_NOT_ALLOWED = "ER_ELEM_CONTENT_NOT_ALLOWED";
   public static final String ER_STYLESHEET_DIRECTED_TERMINATION = "ER_STYLESHEET_DIRECTED_TERMINATION";
   public static final String ER_ONE_OR_TWO = "ER_ONE_OR_TWO";
   public static final String ER_TWO_OR_THREE = "ER_TWO_OR_THREE";
   public static final String ER_COULD_NOT_LOAD_RESOURCE = "ER_COULD_NOT_LOAD_RESOURCE";
   public static final String ER_CANNOT_INIT_DEFAULT_TEMPLATES = "ER_CANNOT_INIT_DEFAULT_TEMPLATES";
   public static final String ER_RESULT_NULL = "ER_RESULT_NULL";
   public static final String ER_RESULT_COULD_NOT_BE_SET = "ER_RESULT_COULD_NOT_BE_SET";
   public static final String ER_NO_OUTPUT_SPECIFIED = "ER_NO_OUTPUT_SPECIFIED";
   public static final String ER_CANNOT_TRANSFORM_TO_RESULT_TYPE = "ER_CANNOT_TRANSFORM_TO_RESULT_TYPE";
   public static final String ER_CANNOT_TRANSFORM_SOURCE_TYPE = "ER_CANNOT_TRANSFORM_SOURCE_TYPE";
   public static final String ER_NULL_CONTENT_HANDLER = "ER_NULL_CONTENT_HANDLER";
   public static final String ER_NULL_ERROR_HANDLER = "ER_NULL_ERROR_HANDLER";
   public static final String ER_CANNOT_CALL_PARSE = "ER_CANNOT_CALL_PARSE";
   public static final String ER_NO_PARENT_FOR_FILTER = "ER_NO_PARENT_FOR_FILTER";
   public static final String ER_NO_STYLESHEET_IN_MEDIA = "ER_NO_STYLESHEET_IN_MEDIA";
   public static final String ER_NO_STYLESHEET_PI = "ER_NO_STYLESHEET_PI";
   public static final String ER_NOT_SUPPORTED = "ER_NOT_SUPPORTED";
   public static final String ER_PROPERTY_VALUE_BOOLEAN = "ER_PROPERTY_VALUE_BOOLEAN";
   public static final String ER_COULD_NOT_FIND_EXTERN_SCRIPT = "ER_COULD_NOT_FIND_EXTERN_SCRIPT";
   public static final String ER_RESOURCE_COULD_NOT_FIND = "ER_RESOURCE_COULD_NOT_FIND";
   public static final String ER_OUTPUT_PROPERTY_NOT_RECOGNIZED = "ER_OUTPUT_PROPERTY_NOT_RECOGNIZED";
   public static final String ER_FAILED_CREATING_ELEMLITRSLT = "ER_FAILED_CREATING_ELEMLITRSLT";
   public static final String ER_VALUE_SHOULD_BE_NUMBER = "ER_VALUE_SHOULD_BE_NUMBER";
   public static final String ER_VALUE_SHOULD_EQUAL = "ER_VALUE_SHOULD_EQUAL";
   public static final String ER_FAILED_CALLING_METHOD = "ER_FAILED_CALLING_METHOD";
   public static final String ER_FAILED_CREATING_ELEMTMPL = "ER_FAILED_CREATING_ELEMTMPL";
   public static final String ER_CHARS_NOT_ALLOWED = "ER_CHARS_NOT_ALLOWED";
   public static final String ER_ATTR_NOT_ALLOWED = "ER_ATTR_NOT_ALLOWED";
   public static final String ER_BAD_VALUE = "ER_BAD_VALUE";
   public static final String ER_ATTRIB_VALUE_NOT_FOUND = "ER_ATTRIB_VALUE_NOT_FOUND";
   public static final String ER_ATTRIB_VALUE_NOT_RECOGNIZED = "ER_ATTRIB_VALUE_NOT_RECOGNIZED";
   public static final String ER_NULL_URI_NAMESPACE = "ER_NULL_URI_NAMESPACE";
   public static final String ER_NUMBER_TOO_BIG = "ER_NUMBER_TOO_BIG";
   public static final String ER_CANNOT_FIND_SAX1_DRIVER = "ER_CANNOT_FIND_SAX1_DRIVER";
   public static final String ER_SAX1_DRIVER_NOT_LOADED = "ER_SAX1_DRIVER_NOT_LOADED";
   public static final String ER_SAX1_DRIVER_NOT_INSTANTIATED = "ER_SAX1_DRIVER_NOT_INSTANTIATED";
   public static final String ER_SAX1_DRIVER_NOT_IMPLEMENT_PARSER = "ER_SAX1_DRIVER_NOT_IMPLEMENT_PARSER";
   public static final String ER_PARSER_PROPERTY_NOT_SPECIFIED = "ER_PARSER_PROPERTY_NOT_SPECIFIED";
   public static final String ER_PARSER_ARG_CANNOT_BE_NULL = "ER_PARSER_ARG_CANNOT_BE_NULL";
   public static final String ER_FEATURE = "ER_FEATURE";
   public static final String ER_PROPERTY = "ER_PROPERTY";
   public static final String ER_NULL_ENTITY_RESOLVER = "ER_NULL_ENTITY_RESOLVER";
   public static final String ER_NULL_DTD_HANDLER = "ER_NULL_DTD_HANDLER";
   public static final String ER_NO_DRIVER_NAME_SPECIFIED = "ER_NO_DRIVER_NAME_SPECIFIED";
   public static final String ER_NO_URL_SPECIFIED = "ER_NO_URL_SPECIFIED";
   public static final String ER_POOLSIZE_LESS_THAN_ONE = "ER_POOLSIZE_LESS_THAN_ONE";
   public static final String ER_INVALID_DRIVER_NAME = "ER_INVALID_DRIVER_NAME";
   public static final String ER_ERRORLISTENER = "ER_ERRORLISTENER";
   public static final String ER_ASSERT_NO_TEMPLATE_PARENT = "ER_ASSERT_NO_TEMPLATE_PARENT";
   public static final String ER_ASSERT_REDUNDENT_EXPR_ELIMINATOR = "ER_ASSERT_REDUNDENT_EXPR_ELIMINATOR";
   public static final String ER_NOT_ALLOWED_IN_POSITION = "ER_NOT_ALLOWED_IN_POSITION";
   public static final String ER_NONWHITESPACE_NOT_ALLOWED_IN_POSITION = "ER_NONWHITESPACE_NOT_ALLOWED_IN_POSITION";
   public static final String INVALID_TCHAR = "INVALID_TCHAR";
   public static final String INVALID_QNAME = "INVALID_QNAME";
   public static final String INVALID_ENUM = "INVALID_ENUM";
   public static final String INVALID_NMTOKEN = "INVALID_NMTOKEN";
   public static final String INVALID_NCNAME = "INVALID_NCNAME";
   public static final String INVALID_BOOLEAN = "INVALID_BOOLEAN";
   public static final String INVALID_NUMBER = "INVALID_NUMBER";
   public static final String ER_ARG_LITERAL = "ER_ARG_LITERAL";
   public static final String ER_DUPLICATE_GLOBAL_VAR = "ER_DUPLICATE_GLOBAL_VAR";
   public static final String ER_DUPLICATE_VAR = "ER_DUPLICATE_VAR";
   public static final String ER_TEMPLATE_NAME_MATCH = "ER_TEMPLATE_NAME_MATCH";
   public static final String ER_INVALID_PREFIX = "ER_INVALID_PREFIX";
   public static final String ER_NO_ATTRIB_SET = "ER_NO_ATTRIB_SET";
   public static final String WG_FOUND_CURLYBRACE = "WG_FOUND_CURLYBRACE";
   public static final String WG_COUNT_ATTRIB_MATCHES_NO_ANCESTOR = "WG_COUNT_ATTRIB_MATCHES_NO_ANCESTOR";
   public static final String WG_EXPR_ATTRIB_CHANGED_TO_SELECT = "WG_EXPR_ATTRIB_CHANGED_TO_SELECT";
   public static final String WG_NO_LOCALE_IN_FORMATNUMBER = "WG_NO_LOCALE_IN_FORMATNUMBER";
   public static final String WG_LOCALE_NOT_FOUND = "WG_LOCALE_NOT_FOUND";
   public static final String WG_CANNOT_MAKE_URL_FROM = "WG_CANNOT_MAKE_URL_FROM";
   public static final String WG_CANNOT_LOAD_REQUESTED_DOC = "WG_CANNOT_LOAD_REQUESTED_DOC";
   public static final String WG_CANNOT_FIND_COLLATOR = "WG_CANNOT_FIND_COLLATOR";
   public static final String WG_FUNCTIONS_SHOULD_USE_URL = "WG_FUNCTIONS_SHOULD_USE_URL";
   public static final String WG_ENCODING_NOT_SUPPORTED_USING_UTF8 = "WG_ENCODING_NOT_SUPPORTED_USING_UTF8";
   public static final String WG_ENCODING_NOT_SUPPORTED_USING_JAVA = "WG_ENCODING_NOT_SUPPORTED_USING_JAVA";
   public static final String WG_SPECIFICITY_CONFLICTS = "WG_SPECIFICITY_CONFLICTS";
   public static final String WG_PARSING_AND_PREPARING = "WG_PARSING_AND_PREPARING";
   public static final String WG_ATTR_TEMPLATE = "WG_ATTR_TEMPLATE";
   public static final String WG_CONFLICT_BETWEEN_XSLSTRIPSPACE_AND_XSLPRESERVESPACE = "WG_CONFLICT_BETWEEN_XSLSTRIPSPACE_AND_XSLPRESERVESP";
   public static final String WG_ATTRIB_NOT_HANDLED = "WG_ATTRIB_NOT_HANDLED";
   public static final String WG_NO_DECIMALFORMAT_DECLARATION = "WG_NO_DECIMALFORMAT_DECLARATION";
   public static final String WG_OLD_XSLT_NS = "WG_OLD_XSLT_NS";
   public static final String WG_ONE_DEFAULT_XSLDECIMALFORMAT_ALLOWED = "WG_ONE_DEFAULT_XSLDECIMALFORMAT_ALLOWED";
   public static final String WG_XSLDECIMALFORMAT_NAMES_MUST_BE_UNIQUE = "WG_XSLDECIMALFORMAT_NAMES_MUST_BE_UNIQUE";
   public static final String WG_ILLEGAL_ATTRIBUTE = "WG_ILLEGAL_ATTRIBUTE";
   public static final String WG_COULD_NOT_RESOLVE_PREFIX = "WG_COULD_NOT_RESOLVE_PREFIX";
   public static final String WG_STYLESHEET_REQUIRES_VERSION_ATTRIB = "WG_STYLESHEET_REQUIRES_VERSION_ATTRIB";
   public static final String WG_ILLEGAL_ATTRIBUTE_NAME = "WG_ILLEGAL_ATTRIBUTE_NAME";
   public static final String WG_ILLEGAL_ATTRIBUTE_VALUE = "WG_ILLEGAL_ATTRIBUTE_VALUE";
   public static final String WG_EMPTY_SECOND_ARG = "WG_EMPTY_SECOND_ARG";
   public static final String WG_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML = "WG_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML";
   public static final String WG_PROCESSINGINSTRUCTION_NOTVALID_NCNAME = "WG_PROCESSINGINSTRUCTION_NOTVALID_NCNAME";
   public static final String WG_ILLEGAL_ATTRIBUTE_POSITION = "WG_ILLEGAL_ATTRIBUTE_POSITION";
   public static final String BAD_CODE = "BAD_CODE";
   public static final String FORMAT_FAILED = "FORMAT_FAILED";
   public static final String ERROR_STRING = "#error";
   public static final String ERROR_HEADER = "Error: ";
   public static final String WARNING_HEADER = "Aviso: ";
   public static final String XSL_HEADER = "XSLT ";
   public static final String XML_HEADER = "XML ";
   /** @deprecated */
   public static final String QUERY_HEADER = "PATTERN ";

   public Object[][] getContents() {
      return new Object[][]{{"ER0000", "{0}"}, {"ER_NO_CURLYBRACE", "Error: No puede haber '{' dentro de la expresión"}, {"ER_ILLEGAL_ATTRIBUTE", "{0} tiene un atributo no permitido: {1}"}, {"ER_NULL_SOURCENODE_APPLYIMPORTS", "¡sourceNode es nulo en xsl:apply-imports!"}, {"ER_CANNOT_ADD", "No se puede añadir {0} a {1}"}, {"ER_NULL_SOURCENODE_HANDLEAPPLYTEMPLATES", "¡sourceNode es nulo en handleApplyTemplatesInstruction!"}, {"ER_NO_NAME_ATTRIB", "{0} debe tener un atributo de nombre."}, {"ER_TEMPLATE_NOT_FOUND", "No se ha podido encontrar la plantilla: {0}"}, {"ER_CANT_RESOLVE_NAME_AVT", "No se ha podido resolver AVT de nombre en xsl:call-template."}, {"ER_REQUIRES_ATTRIB", "{0} necesita un atributo: {1}"}, {"ER_MUST_HAVE_TEST_ATTRIB", "{0} debe tener un atributo ''test''."}, {"ER_BAD_VAL_ON_LEVEL_ATTRIB", "Valor incorrecto en atributo de nivel: {0}"}, {"ER_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML", "Nombre de processing-instruction no puede ser 'xml'"}, {"ER_PROCESSINGINSTRUCTION_NOTVALID_NCNAME", "Nombre de processing-instruction debe ser un NCName válido: {0}"}, {"ER_NEED_MATCH_ATTRIB", "{0} debe tener un atributo de coincidencia si tiene una modalidad."}, {"ER_NEED_NAME_OR_MATCH_ATTRIB", "{0} necesita un atributo de nombre o de coincidencia."}, {"ER_CANT_RESOLVE_NSPREFIX", "No se puede resolver el prefijo del espacio de nombres: {0}"}, {"ER_ILLEGAL_VALUE", "xml:space tiene un valor no permitido: {0}"}, {"ER_NO_OWNERDOC", "¡El nodo hijo no tiene un documento propietario!"}, {"ER_ELEMTEMPLATEELEM_ERR", "Error de ElemTemplateElement: {0}"}, {"ER_NULL_CHILD", "¡Intentando añadir un hijo nulo!"}, {"ER_NEED_SELECT_ATTRIB", "{0} necesita un atributo de selección."}, {"ER_NEED_TEST_ATTRIB", "xsl:when debe tener un atributo 'test'."}, {"ER_NEED_NAME_ATTRIB", "xsl:with-param debe tener un atributo 'name'."}, {"ER_NO_CONTEXT_OWNERDOC", "¡El contexto no tiene un documento propietario!"}, {"ER_COULD_NOT_CREATE_XML_PROC_LIAISON", "No se ha podido crear Liaison TransformerFactory XML: {0}"}, {"ER_PROCESS_NOT_SUCCESSFUL", "El proceso Xalan no ha sido satisfactorio."}, {"ER_NOT_SUCCESSFUL", "Xalan no ha sido satisfactorio."}, {"ER_ENCODING_NOT_SUPPORTED", "Codificación no soportada: {0}"}, {"ER_COULD_NOT_CREATE_TRACELISTENER", "No se ha podido crear TraceListener: {0}"}, {"ER_KEY_REQUIRES_NAME_ATTRIB", "¡xsl:key necesita un atributo 'name'!"}, {"ER_KEY_REQUIRES_MATCH_ATTRIB", "¡xsl:key necesita un atributo 'match'!"}, {"ER_KEY_REQUIRES_USE_ATTRIB", "¡xsl:key necesita un atributo 'use'!"}, {"ER_REQUIRES_ELEMENTS_ATTRIB", "¡(StylesheetHandler) ¡{0} necesita un atributo ''elements''!"}, {"ER_MISSING_PREFIX_ATTRIB", "(StylesheetHandler) Falta el atributo ''prefix'' de {0}"}, {"ER_BAD_STYLESHEET_URL", "El URL de la hoja de estilos es incorrecto: {0}"}, {"ER_FILE_NOT_FOUND", "No se ha encontrado el archivo de hoja de estilos: {0}"}, {"ER_IOEXCEPTION", "Se ha producido una excepción de ES con el archivo de hoja de estilos: {0}"}, {"ER_NO_HREF_ATTRIB", "(StylesheetHandler) No se ha podido encontrar el atributo href para {0}"}, {"ER_STYLESHEET_INCLUDES_ITSELF", "(StylesheetHandler) ¡Inclusión propia de {0} directa o indirectamente!"}, {"ER_PROCESSINCLUDE_ERROR", "Error de StylesheetHandler.processInclude, {0}"}, {"ER_MISSING_LANG_ATTRIB", "(StylesheetHandler) Falta el atributo ''lang'' de {0}"}, {"ER_MISSING_CONTAINER_ELEMENT_COMPONENT", "(StylesheetHandler) Elemento {0} incorrecto. Falta el elemento de contenedor ''component''"}, {"ER_CAN_ONLY_OUTPUT_TO_ELEMENT", "Sólo se puede dar salida hacia Element, DocumentFragment, Document o PrintWriter."}, {"ER_PROCESS_ERROR", "Error de StylesheetRoot.process"}, {"ER_UNIMPLNODE_ERROR", "Error de UnImplNode: {0}"}, {"ER_NO_SELECT_EXPRESSION", "¡Error! No se ha encontrado la expresión de selección (-select) de xpath."}, {"ER_CANNOT_SERIALIZE_XSLPROCESSOR", "¡No se puede serializar un XSLProcessor!"}, {"ER_NO_INPUT_STYLESHEET", "¡No se ha especificado la entrada de hoja de estilos!"}, {"ER_FAILED_PROCESS_STYLESHEET", "¡No se ha podido procesar la hoja de estilos!"}, {"ER_COULDNT_PARSE_DOC", "¡No se ha podido analizar el documento {0}!"}, {"ER_COULDNT_FIND_FRAGMENT", "No se ha podido encontrar el fragmento: {0}"}, {"ER_NODE_NOT_ELEMENT", "El nodo señalado por un identificador de fragmento no es un elemento: {0}"}, {"ER_FOREACH_NEED_MATCH_OR_NAME_ATTRIB", "for-each debe tener un atributo de coincidencia o de nombre"}, {"ER_TEMPLATES_NEED_MATCH_OR_NAME_ATTRIB", "templates debe tener un atributo de coincidencia o de nombre"}, {"ER_NO_CLONE_OF_DOCUMENT_FRAG", "¡No es réplica de un fragmento de documento!"}, {"ER_CANT_CREATE_ITEM", "No se puede crear el elemento en el árbol de resultados: {0}"}, {"ER_XMLSPACE_ILLEGAL_VALUE", "xml:space en el XML fuente tiene un valor no permitido: {0}"}, {"ER_NO_XSLKEY_DECLARATION", "¡No hay declaración xsl:key para {0}!"}, {"ER_CANT_CREATE_URL", "¡Error! No se puede crear url para: {0}"}, {"ER_XSLFUNCTIONS_UNSUPPORTED", "xsl:functions no está soportado"}, {"ER_PROCESSOR_ERROR", "Error de XSLT TransformerFactory"}, {"ER_NOT_ALLOWED_INSIDE_STYLESHEET", "(StylesheetHandler) ¡{0} no permitido dentro de una hoja de estilos!"}, {"ER_RESULTNS_NOT_SUPPORTED", "¡Ya no se soporta result-ns! Utilice xsl:output en su lugar."}, {"ER_DEFAULTSPACE_NOT_SUPPORTED", "¡Ya no se soporta default-space! Utilice xsl:strip-space o xsl:preserve-space en su lugar."}, {"ER_INDENTRESULT_NOT_SUPPORTED", "¡Ya no se soporta indent-result! Utilice xsl:output en su lugar."}, {"ER_ILLEGAL_ATTRIB", "(StylesheetHandler) {0} tiene un atributo no permitido: {1}"}, {"ER_UNKNOWN_XSL_ELEM", "Elemento XSL desconocido: {0}"}, {"ER_BAD_XSLSORT_USE", "(StylesheetHandler) xsl:sort sólo puede utilizarse con xsl:apply-templates o xsl:for-each."}, {"ER_MISPLACED_XSLWHEN", "(StylesheetHandler) ¡xsl:when equivocado!"}, {"ER_XSLWHEN_NOT_PARENTED_BY_XSLCHOOSE", "(StylesheetHandler) ¡xsl:when no emparentado por xsl:choose!"}, {"ER_MISPLACED_XSLOTHERWISE", "(StylesheetHandler) ¡xsl:otherwise equivocado!"}, {"ER_XSLOTHERWISE_NOT_PARENTED_BY_XSLCHOOSE", "(StylesheetHandler) ¡xsl:otherwise no emparentado por xsl:choose!"}, {"ER_NOT_ALLOWED_INSIDE_TEMPLATE", "(StylesheetHandler) ¡{0} no permitido dentro de una plantilla!"}, {"ER_UNKNOWN_EXT_NS_PREFIX", "(StylesheetHandler) Prefijo {1} de espacio de nombres de extensión {0} desconocido"}, {"ER_IMPORTS_AS_FIRST_ELEM", "(StylesheetHandler) ¡Las importaciones sólo pueden aparecer como primeros elementos de la hoja de estilos!"}, {"ER_IMPORTING_ITSELF", "(StylesheetHandler) ¡Importación propia de {0} directa o indirectamente!"}, {"ER_XMLSPACE_ILLEGAL_VAL", "(StylesheetHandler) xml:space tiene un valor no permitido: {0}"}, {"ER_PROCESSSTYLESHEET_NOT_SUCCESSFUL", "¡processStylesheet no satisfactorio!"}, {"ER_SAX_EXCEPTION", "Excepción SAX"}, {"ER_XSLT_ERROR", "Error de XSLT"}, {"ER_CURRENCY_SIGN_ILLEGAL", "El signo monetario no está permitido en la serie del patrón de formato"}, {"ER_DOCUMENT_FUNCTION_INVALID_IN_STYLESHEET_DOM", "¡La función de documento no está soportada en DOM de hoja de estilos!"}, {"ER_CANT_RESOLVE_PREFIX_OF_NON_PREFIX_RESOLVER", "¡No se puede resolver el prefijo de un resolucionador sin prefijo!"}, {"ER_REDIRECT_COULDNT_GET_FILENAME", "Extensión Redirect: No se ha podido obtener el nombre de archivo - el atributo de archivo o de selección debe devolver una serie válida."}, {"ER_CANNOT_BUILD_FORMATTERLISTENER_IN_REDIRECT", "¡No se puede crear FormatterListener en extensión Redirect!"}, {"ER_INVALID_PREFIX_IN_EXCLUDERESULTPREFIX", "El prefijo en exclude-result-prefixes no es válido: {0}"}, {"ER_MISSING_NS_URI", "Falta el URI del espacio de nombres para el prefijo especificado"}, {"ER_MISSING_ARG_FOR_OPTION", "Falta un argumento para la opción: {0}"}, {"ER_INVALID_OPTION", "Opción no válida: {0}"}, {"ER_MALFORMED_FORMAT_STRING", "Serie de formato mal formada: {0}"}, {"ER_STYLESHEET_REQUIRES_VERSION_ATTRIB", "¡xsl:stylesheet necesita un atributo 'version'!"}, {"ER_ILLEGAL_ATTRIBUTE_VALUE", "Atributo: {0} tiene un valor no permitido: {1}"}, {"ER_CHOOSE_REQUIRES_WHEN", "xsl:choose necesita un xsl:when"}, {"ER_NO_APPLY_IMPORT_IN_FOR_EACH", "xsl:apply-imports no permitido en xsl:for-each"}, {"ER_CANT_USE_DTM_FOR_OUTPUT", "No se puede utilizar DTMLiaison para un nodo DOM de salida... ¡Pase org.apache.xpath.DOM2Helper en su lugar!"}, {"ER_CANT_USE_DTM_FOR_INPUT", "No se puede utilizar DTMLiaison para un nodo DOM de entrada... ¡Pase org.apache.xpath.DOM2Helper en su lugar!"}, {"ER_CALL_TO_EXT_FAILED", "Anomalía al llamar al elemento de extensión: {0}"}, {"ER_PREFIX_MUST_RESOLVE", "El prefijo debe resolverse como un espacio de nombres: {0}"}, {"ER_INVALID_UTF16_SURROGATE", "¿Se ha detectado un sustituto UTF-16 no válido: {0}?"}, {"ER_XSLATTRSET_USED_ITSELF", "xsl:attribute-set {0} se ha utilizado a sí mismo lo que puede provocar un bucle infinito."}, {"ER_CANNOT_MIX_XERCESDOM", "¡No se puede mezclar la entrada Xerces-DOM con la salida Xerces-DOM!"}, {"ER_TOO_MANY_LISTENERS", "addTraceListenersToStylesheet - TooManyListenersException"}, {"ER_IN_ELEMTEMPLATEELEM_READOBJECT", "En ElemTemplateElement.readObject: {0}"}, {"ER_DUPLICATE_NAMED_TEMPLATE", "Se ha encontrado más de una plantilla con el nombre: {0}"}, {"ER_INVALID_KEY_CALL", "Llamada de función no válida: no están permitidas las llamadas key() recursivas"}, {"ER_REFERENCING_ITSELF", "¡La variable {0} se está referenciando a sí misma directa o indirectamente!"}, {"ER_ILLEGAL_DOMSOURCE_INPUT", "¡El nodo de entrada no puede ser nulo para DOMSource de newTemplates!"}, {"ER_CLASS_NOT_FOUND_FOR_OPTION", "No se ha encontrado el archivo de clase para la opción {0}"}, {"ER_REQUIRED_ELEM_NOT_FOUND", "No se ha encontrado un elemento necesario: {0}"}, {"ER_INPUT_CANNOT_BE_NULL", "InputStream no puede ser nulo"}, {"ER_URI_CANNOT_BE_NULL", "URI no puede ser nulo"}, {"ER_FILE_CANNOT_BE_NULL", "Archivo no puede ser nulo"}, {"ER_SOURCE_CANNOT_BE_NULL", "InputSource no puede ser nulo"}, {"ER_CANNOT_INIT_BSFMGR", "No se ha podido inicializar el Gestor BSF"}, {"ER_CANNOT_CMPL_EXTENSN", "No se ha podido compilar la extensión"}, {"ER_CANNOT_CREATE_EXTENSN", "No se ha podido crear la extensión: {0} como consecuencia de: {1}"}, {"ER_INSTANCE_MTHD_CALL_REQUIRES", "La llamada del método de instancia al método {0} necesita una instancia Object como primer argumento"}, {"ER_INVALID_ELEMENT_NAME", "Se ha especificado un nombre de elemento no válido {0}"}, {"ER_ELEMENT_NAME_METHOD_STATIC", "El método del nombre de elemento debe ser estático {0}"}, {"ER_EXTENSION_FUNC_UNKNOWN", "Función de extensión {0} : {1} desconocida"}, {"ER_MORE_MATCH_CONSTRUCTOR", "Hay más de una coincidencia máxima para el constructor de {0}"}, {"ER_MORE_MATCH_METHOD", "Hay más de una coincidencia máxima para el método {0}"}, {"ER_MORE_MATCH_ELEMENT", "Hay más de una coincidencia máxima para el método de elemento {0}"}, {"ER_INVALID_CONTEXT_PASSED", "Se ha pasado un contexto no válido para evaluar {0}"}, {"ER_POOL_EXISTS", "La agrupación ya existe"}, {"ER_NO_DRIVER_NAME", "No se ha especificado un nombre de controlador"}, {"ER_NO_URL", "No se ha especificado un URL"}, {"ER_POOL_SIZE_LESSTHAN_ONE", "¡El tamaño de la agrupación es menor que uno!"}, {"ER_INVALID_DRIVER", "¡Se ha especificado un nombre de controlador no válido!"}, {"ER_NO_STYLESHEETROOT", "¡No se ha encontrado la raíz de la hoja de estilos!"}, {"ER_ILLEGAL_XMLSPACE_VALUE", "Valor no permitido para xml:space"}, {"ER_PROCESSFROMNODE_FAILED", "Anomalía de processFromNode"}, {"ER_RESOURCE_COULD_NOT_LOAD", "No se ha podido cargar el recurso [ {0} ]: {1} \n {2} \t {3}"}, {"ER_BUFFER_SIZE_LESSTHAN_ZERO", "Tamaño de almacenamiento intermedio <=0"}, {"ER_UNKNOWN_ERROR_CALLING_EXTENSION", "Error desconocido al llamar a la extensión"}, {"ER_NO_NAMESPACE_DECL", "El prefijo {0} no tiene una declaración de espacio de nombres correspondiente"}, {"ER_ELEM_CONTENT_NOT_ALLOWED", "No se permite el contenido del elemento para lang=javaclass {0}"}, {"ER_STYLESHEET_DIRECTED_TERMINATION", "Terminación de hoja de estilos dirigida"}, {"ER_ONE_OR_TWO", "1 ó 2"}, {"ER_TWO_OR_THREE", "2 ó 3"}, {"ER_COULD_NOT_LOAD_RESOURCE", "No se ha podido cargar {0} (compruebe la CLASSPATH), ahora sólo se están utilizando los valores por omisión"}, {"ER_CANNOT_INIT_DEFAULT_TEMPLATES", "No se han podido inicializar las plantillas por omisión"}, {"ER_RESULT_NULL", "El resultado no debería ser nulo"}, {"ER_RESULT_COULD_NOT_BE_SET", "No se ha podido establecer el resultado"}, {"ER_NO_OUTPUT_SPECIFIED", "No se ha especificado salida"}, {"ER_CANNOT_TRANSFORM_TO_RESULT_TYPE", "No se puede transformar un resultado de tipo {0}"}, {"ER_CANNOT_TRANSFORM_SOURCE_TYPE", "No se puede transformar un fuente de tipo {0}"}, {"ER_NULL_CONTENT_HANDLER", "Manejador de contenido nulo"}, {"ER_NULL_ERROR_HANDLER", "Manejador de error nulo"}, {"ER_CANNOT_CALL_PARSE", "No se puede llamar a parse si no se ha establecido ContentHandler"}, {"ER_NO_PARENT_FOR_FILTER", "No hay padre para el filtro"}, {"ER_NO_STYLESHEET_IN_MEDIA", "No se han encontrado hojas de estilos en: {0}, soporte= {1}"}, {"ER_NO_STYLESHEET_PI", "No se ha encontrado xml-stylesheet PI en: {0}"}, {"ER_NOT_SUPPORTED", "No soportado: {0}"}, {"ER_PROPERTY_VALUE_BOOLEAN", "El valor de la propiedad {0} debería ser una instancia Boolean"}, {"ER_COULD_NOT_FIND_EXTERN_SCRIPT", "No se ha podido encontrar el script externo en {0}"}, {"ER_RESOURCE_COULD_NOT_FIND", "No se ha podido cargar el recurso [ {0} ].\n{1}"}, {"ER_OUTPUT_PROPERTY_NOT_RECOGNIZED", "No se reconoce la propiedad de salida: {0}"}, {"ER_FAILED_CREATING_ELEMLITRSLT", "Anomalía al crear la instancia ElemLiteralResult"}, {"ER_VALUE_SHOULD_BE_NUMBER", "El valor para {0} debería contener un número analizable"}, {"ER_VALUE_SHOULD_EQUAL", "El valor de {0} debería ser sí o no"}, {"ER_FAILED_CALLING_METHOD", "Anomalía al llamar al método {0}"}, {"ER_FAILED_CREATING_ELEMTMPL", "Anomalía al crear la instancia ElemTemplateElement"}, {"ER_CHARS_NOT_ALLOWED", "No se permiten caracteres en este punto del documento"}, {"ER_ATTR_NOT_ALLOWED", "¡El atributo \"{0}\" no está permitido en el elemento {1}!"}, {"ER_BAD_VALUE", "{0} valor incorrecto {1}"}, {"ER_ATTRIB_VALUE_NOT_FOUND", "No se ha encontrado el valor del atributo {0}"}, {"ER_ATTRIB_VALUE_NOT_RECOGNIZED", "No se ha reconocido el valor del atributo {0}"}, {"ER_NULL_URI_NAMESPACE", "Se ha intentado generar un prefijo de espacio de nombres con un URI nulo"}, {"ER_NUMBER_TOO_BIG", "Se ha intentado formatear un número mayor que el entero largo más grande"}, {"ER_CANNOT_FIND_SAX1_DRIVER", "No se ha podido encontrar la clase de controlador SAX1 {0}"}, {"ER_SAX1_DRIVER_NOT_LOADED", "Se ha encontrado la clase de controlador SAX1 {0} pero no se ha podido cargar"}, {"ER_SAX1_DRIVER_NOT_INSTANTIATED", "Se ha cargado la clase de controlador SAX1 {0} pero no se ha podido crear una instancia"}, {"ER_SAX1_DRIVER_NOT_IMPLEMENT_PARSER", "La clase de controlador SAX1 {0} no implementa org.xml.sax.Parser"}, {"ER_PARSER_PROPERTY_NOT_SPECIFIED", "No se ha especificado la propiedad del sistema org.xml.sax.parser"}, {"ER_PARSER_ARG_CANNOT_BE_NULL", "El argumento del analizador no debe ser nulo"}, {"ER_FEATURE", "Característica: {0}"}, {"ER_PROPERTY", "Propiedad: {0}"}, {"ER_NULL_ENTITY_RESOLVER", "Resolucionador de entidad nulo"}, {"ER_NULL_DTD_HANDLER", "Manejador DTD nulo"}, {"ER_NO_DRIVER_NAME_SPECIFIED", "¡No se ha especificado un nombre de controlador!"}, {"ER_NO_URL_SPECIFIED", "¡No se ha especificado un URL!"}, {"ER_POOLSIZE_LESS_THAN_ONE", "¡El tamaño de la agrupación es menor que 1!"}, {"ER_INVALID_DRIVER_NAME", "¡Se ha especificado un nombre de controlador no válido!"}, {"ER_ERRORLISTENER", "ErrorListener"}, {"ER_ASSERT_NO_TEMPLATE_PARENT", "¡Error del programador! ¡La expresión no tiene un padre ElemTemplateElement!"}, {"ER_ASSERT_REDUNDENT_EXPR_ELIMINATOR", "Aserción del programador en RundundentExprEliminator: {0}"}, {"ER_NOT_ALLOWED_IN_POSITION", "¡{0} no está permitido en esta posición de la hoja de estilos!"}, {"ER_NONWHITESPACE_NOT_ALLOWED_IN_POSITION", "¡No está permitido texto sin espacios en blanco en esta posición de la hoja de estilos!"}, {"INVALID_TCHAR", "Valor no permitido: se ha utilizado {1} para el atributo CHAR: {0}. ¡Un atributo de tipo CHAR debe ser de un solo carácter!"}, {"INVALID_QNAME", "Valor no permitido: se ha utilizado {1} para el atributo QNAME: {0}"}, {"INVALID_ENUM", "Valor no permitido: se ha utilizado {1} para el atributo ENUM: {0}. Los valores válidos son: {2}."}, {"INVALID_NMTOKEN", "Valor no permitido: se ha utilizado {1} para el atributo NMTOKEN: {0}"}, {"INVALID_NCNAME", "Valor no permitido: se ha utilizado {1} para el atributo NCNAME: {0}"}, {"INVALID_BOOLEAN", "Valor no permitido: se ha utilizado {1} para el atributo boolean: {0}"}, {"INVALID_NUMBER", "Valor no permitido: se ha utilizado {1} para el atributo number: {0}"}, {"ER_ARG_LITERAL", "El argumento para {0} en el patrón de coincidencia debe ser un literal."}, {"ER_DUPLICATE_GLOBAL_VAR", "Declaración de variable global duplicada."}, {"ER_DUPLICATE_VAR", "Declaración de variable duplicada."}, {"ER_TEMPLATE_NAME_MATCH", "xsl:template debe tener un atributo name o match (o ambos)"}, {"ER_INVALID_PREFIX", "El prefijo en exclude-result-prefixes no es válido: {0}"}, {"ER_NO_ATTRIB_SET", "attribute-set de nombre {0} no existe"}, {"WG_FOUND_CURLYBRACE", "¡Se ha encontrado '}' pero no se ha abierto una plantilla de atributos!"}, {"WG_COUNT_ATTRIB_MATCHES_NO_ANCESTOR", "Aviso: ¡El atributo count no coincide con un antecesor en xsl:number! Destino = {0}"}, {"WG_EXPR_ATTRIB_CHANGED_TO_SELECT", "Sintaxis antigua: El nombre del atributo 'expr' se ha cambiado por 'select'."}, {"WG_NO_LOCALE_IN_FORMATNUMBER", "Xalan no maneja aún el nombre de entorno local en la función format-number."}, {"WG_LOCALE_NOT_FOUND", "Aviso: No se ha podido encontrar el entorno local para xml:lang={0}"}, {"WG_CANNOT_MAKE_URL_FROM", "No se puede crear URL desde: {0}"}, {"WG_CANNOT_LOAD_REQUESTED_DOC", "No se puede cargar el doc solicitado: {0}"}, {"WG_CANNOT_FIND_COLLATOR", "No se ha podido encontrar clasificador para <sort xml:lang={0}"}, {"WG_FUNCTIONS_SHOULD_USE_URL", "Sintaxis antigua: La instrucción functions debería utilizar un url de {0}"}, {"WG_ENCODING_NOT_SUPPORTED_USING_UTF8", "Codificación no soportada: {0}, se utiliza UTF-8"}, {"WG_ENCODING_NOT_SUPPORTED_USING_JAVA", "Codificación no soportada: {0}, se utiliza Java {1}"}, {"WG_SPECIFICITY_CONFLICTS", "Se han encontrado conflictos de especificación: {0} Se utilizará lo último encontrado en la hoja de estilos."}, {"WG_PARSING_AND_PREPARING", "========= Analizando y preparando {0} =========="}, {"WG_ATTR_TEMPLATE", "Plantilla de atributos, {0}"}, {"WG_CONFLICT_BETWEEN_XSLSTRIPSPACE_AND_XSLPRESERVESP", "Conflicto de coincidencia entre xsl:strip-space y xsl:preserve-space"}, {"WG_ATTRIB_NOT_HANDLED", "¡Xalan no maneja aún el atributo {0}!"}, {"WG_NO_DECIMALFORMAT_DECLARATION", "No se ha encontrado declaración para el formato decimal: {0}"}, {"WG_OLD_XSLT_NS", "Falta el espacio de nombres XSLT o es incorrecto."}, {"WG_ONE_DEFAULT_XSLDECIMALFORMAT_ALLOWED", "Sólo se permite una declaración xsl:decimal-format por omisión."}, {"WG_XSLDECIMALFORMAT_NAMES_MUST_BE_UNIQUE", "Los nombres de xsl:decimal-format deben ser únicos. El nombre \"{0}\" se ha duplicado."}, {"WG_ILLEGAL_ATTRIBUTE", "{0} tiene un atributo no permitido: {1}"}, {"WG_COULD_NOT_RESOLVE_PREFIX", "No se ha podido resolver el prefijo del espacio de nombres: {0}. Se ignorará el nodo."}, {"WG_STYLESHEET_REQUIRES_VERSION_ATTRIB", "¡xsl:stylesheet necesita un atributo 'version'!"}, {"WG_ILLEGAL_ATTRIBUTE_NAME", "Nombre de atributo no permitido: {0}"}, {"WG_ILLEGAL_ATTRIBUTE_VALUE", "Se ha utilizado un valor no permitido para el atributo {0}: {1}"}, {"WG_EMPTY_SECOND_ARG", "El NodeSet resultante del segundo argumento de la función del documento está vacío. Devuelve un conjunto de nodos vacío."}, {"WG_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML", "El valor del atributo 'name' de nombre xsl:processing-instruction no debe ser 'xml'"}, {"WG_PROCESSINGINSTRUCTION_NOTVALID_NCNAME", "El valor del atributo 'name' de xsl:processing-instruction debe ser un NCName válido: {0}"}, {"WG_ILLEGAL_ATTRIBUTE_POSITION", "No se puede añadir el atributo {0} después de nodos hijo o antes de que se produzca un elemento. Se ignorará el atributo."}, {"ui_language", "es"}, {"help_language", "es"}, {"language", "es"}, {"BAD_CODE", "El parámetro para createMessage estaba fuera de los límites"}, {"FORMAT_FAILED", "Se ha generado una excepción durante la llamada messageFormat"}, {"version", ">>>>>>> Xalan versión"}, {"version2", "<<<<<<<"}, {"yes", "sí"}, {"line", "Línea núm."}, {"column", "Columna núm."}, {"xsldone", "XSLProcessor: terminado"}, {"xslProc_option", "Opciones de la clase Process de la línea de mandatos Xalan-J:"}, {"xslProc_option", "Opciones de la clase Process de la línea de mandatos Xalan-J:"}, {"xslProc_invalid_xsltc_option", "La opción {0} no está soportada en modalidad XSLTC."}, {"xslProc_invalid_xalan_option", "La opción {0} sólo puede utilizarse con -XSLTC."}, {"xslProc_no_input", "Error: No se ha especificado ninguna hoja de estilos ni xml de entrada. Ejecute este mandato sin opciones para ver las instrucciones de uso."}, {"xslProc_common_options", "-Opciones comunes-"}, {"xslProc_xalan_options", "-Opciones para Xalan-"}, {"xslProc_xsltc_options", "-Opciones para XSLTC-"}, {"xslProc_return_to_continue", "(pulse <Intro> para continuar)"}, {"optionXSLTC", "[-XSLTC (Utilizar XSLTC para transformación)]"}, {"optionIN", "[-IN URLXMLentrada]"}, {"optionXSL", "[-XSL URLTransformaciónXSL]"}, {"optionOUT", "[-OUT nombreArchivoSalida]"}, {"optionLXCIN", "[-LXCIN entradaNombreArchivoHojaEstilosCompilada]"}, {"optionLXCOUT", "[-LXCOUT salidaNombreArchivoHojaEstilosCompilada]"}, {"optionPARSER", "[-PARSER nombre de clase completamente cualificado del enlace del analizador]"}, {"optionE", "[-E (No expandir referencias de entidades)]"}, {"optionV", "[-E (No expandir referencias de entidades)]"}, {"optionQC", "[-QC (Avisos silenciosos de conflictos de patrones)]"}, {"optionQ", "[-Q  (Modalidad silenciosa)]"}, {"optionLF", "[-LF (Utilizar sólo avances de línea en la salida {por omisión es CR/LF})]"}, {"optionCR", "[-CR (Utilizar sólo retornos de carro en la salida {por omisión es CR/LF})]"}, {"optionESCAPE", "[-ESCAPE (Caracteres con escape {por omisión es <>&\"'\\r\\n}]"}, {"optionINDENT", "[-INDENT (Controlar el número de espacios de sangrado {por omisión es 0})]"}, {"optionTT", "[-TT (Rastrear las plantillas a medida que se llaman.)]"}, {"optionTG", "[-TG (Rastrear cada suceso de generación.)]"}, {"optionTS", "[-TS (Rastrear cada suceso de selección.)]"}, {"optionTTC", "[-TTC (Rastrear los hijos de plantillas a medida que se procesan.)]"}, {"optionTCLASS", "[-TCLASS (Clase TraceListener para extensiones de rastreo.)]"}, {"optionVALIDATE", "[-VALIDATE (Establecer si se realiza la validación. Por omisión la validación está desactivada.)]"}, {"optionEDUMP", "[-EDUMP {nombre de archivo opcional} (Realizar vuelco de pila si se produce un error.)]"}, {"optionXML", "[-XML (Utilizar el formateador XML y añadir la cabecera XML.)]"}, {"optionTEXT", "[-TEXT (Utilizar el formateador de texto sencillo.)]"}, {"optionHTML", "[-HTML (Utilizar el formateador HTML.)]"}, {"optionPARAM", "[-PARAM expresión de nombre (Establecer un parámetro de hoja de estilos)]"}, {"noParsermsg1", "El proceso XSL no ha sido satisfactorio."}, {"noParsermsg2", "** No se ha podido encontrar el analizador **"}, {"noParsermsg3", "Compruebe la classpath."}, {"noParsermsg4", "Si no dispone del analizador XML para Java de IBM, puede bajarlo de "}, {"noParsermsg5", "IBM AlphaWorks: http://www.alphaworks.ibm.com/formula/xml"}, {"optionURIRESOLVER", "[-URIRESOLVER nombre de clase completo (URIResolver a utilizar para resolver URI)]"}, {"optionENTITYRESOLVER", "[-ENTITYRESOLVER nombre de clase completo (EntityResolver a utilizar para resolver entidades)]"}, {"optionCONTENTHANDLER", "[-CONTENTHANDLER nombre de clase completo (ContentHandler a utilizar para serializar la salida)]"}, {"optionLINENUMBERS", "[-L utilizar números de línea para el documento fuente]"}, {"optionMEDIA", "[-MEDIA tipoSoporte (Utilizar el atributo de soporte para encontrar la hoja de estilos asociada con un documento.)]"}, {"optionFLAVOR", "[-FLAVOR nombreEstilo (Utilizar explícitamente s2s=SAX o d2d=DOM para realizar la transformación.)]"}, {"optionDIAG", "[-DIAG (Imprimir el total de milisegundos que lleva la transformación.)]"}, {"optionINCREMENTAL", "[-INCREMENTAL (Solicitar construcción DTM incremental estableciendo http://xml.apache.org/xalan/features/incremental como verdadero.)]"}, {"optionNOOPTIMIMIZE", "[-NOOPTIMIMIZE (Solicitar proceso de optimización de hoja de estilos estableciendo http://xml.apache.org/xalan/features/optimize como falso.)]"}, {"optionRL", "[-RL límiteRecursión (Límite numérico de aserción sobre profundidad de recursión de hoja de estilos.)]"}, {"optionXO", "[-XO [nombreTranslet] (Asignar el nombre al translet generado)]"}, {"optionXD", "[-XD directorioDestino (Especificar un directorio de destino para translet)]"}, {"optionXJ", "[-XJ archivoJar (Empaqueta las clases translet en un archivo jar de nombre <archivoJar>)]"}, {"optionXP", "[-XP paquete (Especifica un prefijo para el nombre del paquete de todas las clases translet generadas)]"}, {"optionXN", "[-XN (habilita la inclusión en línea de plantillas)]"}, {"optionXX", "[-XX (activa la salida de mensajes de depuración adicionales)]"}, {"optionXT", "[-XT (utilizar translet para transformar si es posible)]"}, {"diagTiming", "--------- La transformación de {0} mediante {1} ha durado {2} ms"}, {"recursionTooDeep", "Anidado de plantilla demasiado profundo. anidado = {0}, plantilla {1} {2}"}, {"nameIs", "el nombre es "}, {"matchPatternIs", "el patrón de coincidencia es "}};
   }

   public static final XSLTErrorResources loadResourceBundle(String className) throws MissingResourceException {
      Locale locale = Locale.getDefault();
      String suffix = getResourceSuffix(locale);

      try {
         return (XSLTErrorResources)ResourceBundle.getBundle(className + suffix, locale);
      } catch (MissingResourceException var6) {
         try {
            return (XSLTErrorResources)ResourceBundle.getBundle(className, new Locale("es", "ES"));
         } catch (MissingResourceException var5) {
            throw new MissingResourceException("Could not load any resource bundles.", className, "");
         }
      }
   }

   private static final String getResourceSuffix(Locale locale) {
      String suffix = "_" + locale.getLanguage();
      String country = locale.getCountry();
      if (country.equals("TW")) {
         suffix = suffix + "_" + country;
      }

      return suffix;
   }
}
