package org.apache.xalan.res;

import java.util.ListResourceBundle;
import java.util.Locale;
import java.util.MissingResourceException;
import java.util.ResourceBundle;

public class XSLTErrorResources_ja extends ListResourceBundle {
   public static final int MAX_CODE = 201;
   public static final int MAX_WARNING = 29;
   public static final int MAX_OTHERS = 55;
   public static final int MAX_MESSAGES = 231;
   public static final String ER_NO_CURLYBRACE = "ER_NO_CURLYBRACE";
   public static final String ER_ILLEGAL_ATTRIBUTE = "ER_ILLEGAL_ATTRIBUTE";
   public static final String ER_NULL_SOURCENODE_APPLYIMPORTS = "ER_NULL_SOURCENODE_APPLYIMPORTS";
   public static final String ER_CANNOT_ADD = "ER_CANNOT_ADD";
   public static final String ER_NULL_SOURCENODE_HANDLEAPPLYTEMPLATES = "ER_NULL_SOURCENODE_HANDLEAPPLYTEMPLATES";
   public static final String ER_NO_NAME_ATTRIB = "ER_NO_NAME_ATTRIB";
   public static final String ER_TEMPLATE_NOT_FOUND = "ER_TEMPLATE_NOT_FOUND";
   public static final String ER_CANT_RESOLVE_NAME_AVT = "ER_CANT_RESOLVE_NAME_AVT";
   public static final String ER_REQUIRES_ATTRIB = "ER_REQUIRES_ATTRIB";
   public static final String ER_MUST_HAVE_TEST_ATTRIB = "ER_MUST_HAVE_TEST_ATTRIB";
   public static final String ER_BAD_VAL_ON_LEVEL_ATTRIB = "ER_BAD_VAL_ON_LEVEL_ATTRIB";
   public static final String ER_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML = "ER_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML";
   public static final String ER_PROCESSINGINSTRUCTION_NOTVALID_NCNAME = "ER_PROCESSINGINSTRUCTION_NOTVALID_NCNAME";
   public static final String ER_NEED_MATCH_ATTRIB = "ER_NEED_MATCH_ATTRIB";
   public static final String ER_NEED_NAME_OR_MATCH_ATTRIB = "ER_NEED_NAME_OR_MATCH_ATTRIB";
   public static final String ER_CANT_RESOLVE_NSPREFIX = "ER_CANT_RESOLVE_NSPREFIX";
   public static final String ER_ILLEGAL_VALUE = "ER_ILLEGAL_VALUE";
   public static final String ER_NO_OWNERDOC = "ER_NO_OWNERDOC";
   public static final String ER_ELEMTEMPLATEELEM_ERR = "ER_ELEMTEMPLATEELEM_ERR";
   public static final String ER_NULL_CHILD = "ER_NULL_CHILD";
   public static final String ER_NEED_SELECT_ATTRIB = "ER_NEED_SELECT_ATTRIB";
   public static final String ER_NEED_TEST_ATTRIB = "ER_NEED_TEST_ATTRIB";
   public static final String ER_NEED_NAME_ATTRIB = "ER_NEED_NAME_ATTRIB";
   public static final String ER_NO_CONTEXT_OWNERDOC = "ER_NO_CONTEXT_OWNERDOC";
   public static final String ER_COULD_NOT_CREATE_XML_PROC_LIAISON = "ER_COULD_NOT_CREATE_XML_PROC_LIAISON";
   public static final String ER_PROCESS_NOT_SUCCESSFUL = "ER_PROCESS_NOT_SUCCESSFUL";
   public static final String ER_NOT_SUCCESSFUL = "ER_NOT_SUCCESSFUL";
   public static final String ER_ENCODING_NOT_SUPPORTED = "ER_ENCODING_NOT_SUPPORTED";
   public static final String ER_COULD_NOT_CREATE_TRACELISTENER = "ER_COULD_NOT_CREATE_TRACELISTENER";
   public static final String ER_KEY_REQUIRES_NAME_ATTRIB = "ER_KEY_REQUIRES_NAME_ATTRIB";
   public static final String ER_KEY_REQUIRES_MATCH_ATTRIB = "ER_KEY_REQUIRES_MATCH_ATTRIB";
   public static final String ER_KEY_REQUIRES_USE_ATTRIB = "ER_KEY_REQUIRES_USE_ATTRIB";
   public static final String ER_REQUIRES_ELEMENTS_ATTRIB = "ER_REQUIRES_ELEMENTS_ATTRIB";
   public static final String ER_MISSING_PREFIX_ATTRIB = "ER_MISSING_PREFIX_ATTRIB";
   public static final String ER_BAD_STYLESHEET_URL = "ER_BAD_STYLESHEET_URL";
   public static final String ER_FILE_NOT_FOUND = "ER_FILE_NOT_FOUND";
   public static final String ER_IOEXCEPTION = "ER_IOEXCEPTION";
   public static final String ER_NO_HREF_ATTRIB = "ER_NO_HREF_ATTRIB";
   public static final String ER_STYLESHEET_INCLUDES_ITSELF = "ER_STYLESHEET_INCLUDES_ITSELF";
   public static final String ER_PROCESSINCLUDE_ERROR = "ER_PROCESSINCLUDE_ERROR";
   public static final String ER_MISSING_LANG_ATTRIB = "ER_MISSING_LANG_ATTRIB";
   public static final String ER_MISSING_CONTAINER_ELEMENT_COMPONENT = "ER_MISSING_CONTAINER_ELEMENT_COMPONENT";
   public static final String ER_CAN_ONLY_OUTPUT_TO_ELEMENT = "ER_CAN_ONLY_OUTPUT_TO_ELEMENT";
   public static final String ER_PROCESS_ERROR = "ER_PROCESS_ERROR";
   public static final String ER_UNIMPLNODE_ERROR = "ER_UNIMPLNODE_ERROR";
   public static final String ER_NO_SELECT_EXPRESSION = "ER_NO_SELECT_EXPRESSION";
   public static final String ER_CANNOT_SERIALIZE_XSLPROCESSOR = "ER_CANNOT_SERIALIZE_XSLPROCESSOR";
   public static final String ER_NO_INPUT_STYLESHEET = "ER_NO_INPUT_STYLESHEET";
   public static final String ER_FAILED_PROCESS_STYLESHEET = "ER_FAILED_PROCESS_STYLESHEET";
   public static final String ER_COULDNT_PARSE_DOC = "ER_COULDNT_PARSE_DOC";
   public static final String ER_COULDNT_FIND_FRAGMENT = "ER_COULDNT_FIND_FRAGMENT";
   public static final String ER_NODE_NOT_ELEMENT = "ER_NODE_NOT_ELEMENT";
   public static final String ER_FOREACH_NEED_MATCH_OR_NAME_ATTRIB = "ER_FOREACH_NEED_MATCH_OR_NAME_ATTRIB";
   public static final String ER_TEMPLATES_NEED_MATCH_OR_NAME_ATTRIB = "ER_TEMPLATES_NEED_MATCH_OR_NAME_ATTRIB";
   public static final String ER_NO_CLONE_OF_DOCUMENT_FRAG = "ER_NO_CLONE_OF_DOCUMENT_FRAG";
   public static final String ER_CANT_CREATE_ITEM = "ER_CANT_CREATE_ITEM";
   public static final String ER_XMLSPACE_ILLEGAL_VALUE = "ER_XMLSPACE_ILLEGAL_VALUE";
   public static final String ER_NO_XSLKEY_DECLARATION = "ER_NO_XSLKEY_DECLARATION";
   public static final String ER_CANT_CREATE_URL = "ER_CANT_CREATE_URL";
   public static final String ER_XSLFUNCTIONS_UNSUPPORTED = "ER_XSLFUNCTIONS_UNSUPPORTED";
   public static final String ER_PROCESSOR_ERROR = "ER_PROCESSOR_ERROR";
   public static final String ER_NOT_ALLOWED_INSIDE_STYLESHEET = "ER_NOT_ALLOWED_INSIDE_STYLESHEET";
   public static final String ER_RESULTNS_NOT_SUPPORTED = "ER_RESULTNS_NOT_SUPPORTED";
   public static final String ER_DEFAULTSPACE_NOT_SUPPORTED = "ER_DEFAULTSPACE_NOT_SUPPORTED";
   public static final String ER_INDENTRESULT_NOT_SUPPORTED = "ER_INDENTRESULT_NOT_SUPPORTED";
   public static final String ER_ILLEGAL_ATTRIB = "ER_ILLEGAL_ATTRIB";
   public static final String ER_UNKNOWN_XSL_ELEM = "ER_UNKNOWN_XSL_ELEM";
   public static final String ER_BAD_XSLSORT_USE = "ER_BAD_XSLSORT_USE";
   public static final String ER_MISPLACED_XSLWHEN = "ER_MISPLACED_XSLWHEN";
   public static final String ER_XSLWHEN_NOT_PARENTED_BY_XSLCHOOSE = "ER_XSLWHEN_NOT_PARENTED_BY_XSLCHOOSE";
   public static final String ER_MISPLACED_XSLOTHERWISE = "ER_MISPLACED_XSLOTHERWISE";
   public static final String ER_XSLOTHERWISE_NOT_PARENTED_BY_XSLCHOOSE = "ER_XSLOTHERWISE_NOT_PARENTED_BY_XSLCHOOSE";
   public static final String ER_NOT_ALLOWED_INSIDE_TEMPLATE = "ER_NOT_ALLOWED_INSIDE_TEMPLATE";
   public static final String ER_UNKNOWN_EXT_NS_PREFIX = "ER_UNKNOWN_EXT_NS_PREFIX";
   public static final String ER_IMPORTS_AS_FIRST_ELEM = "ER_IMPORTS_AS_FIRST_ELEM";
   public static final String ER_IMPORTING_ITSELF = "ER_IMPORTING_ITSELF";
   public static final String ER_XMLSPACE_ILLEGAL_VAL = "ER_XMLSPACE_ILLEGAL_VAL";
   public static final String ER_PROCESSSTYLESHEET_NOT_SUCCESSFUL = "ER_PROCESSSTYLESHEET_NOT_SUCCESSFUL";
   public static final String ER_SAX_EXCEPTION = "ER_SAX_EXCEPTION";
   public static final String ER_XSLT_ERROR = "ER_XSLT_ERROR";
   public static final String ER_CURRENCY_SIGN_ILLEGAL = "ER_CURRENCY_SIGN_ILLEGAL";
   public static final String ER_DOCUMENT_FUNCTION_INVALID_IN_STYLESHEET_DOM = "ER_DOCUMENT_FUNCTION_INVALID_IN_STYLESHEET_DOM";
   public static final String ER_CANT_RESOLVE_PREFIX_OF_NON_PREFIX_RESOLVER = "ER_CANT_RESOLVE_PREFIX_OF_NON_PREFIX_RESOLVER";
   public static final String ER_REDIRECT_COULDNT_GET_FILENAME = "ER_REDIRECT_COULDNT_GET_FILENAME";
   public static final String ER_CANNOT_BUILD_FORMATTERLISTENER_IN_REDIRECT = "ER_CANNOT_BUILD_FORMATTERLISTENER_IN_REDIRECT";
   public static final String ER_INVALID_PREFIX_IN_EXCLUDERESULTPREFIX = "ER_INVALID_PREFIX_IN_EXCLUDERESULTPREFIX";
   public static final String ER_MISSING_NS_URI = "ER_MISSING_NS_URI";
   public static final String ER_MISSING_ARG_FOR_OPTION = "ER_MISSING_ARG_FOR_OPTION";
   public static final String ER_INVALID_OPTION = "ER_INVALID_OPTION";
   public static final String ER_MALFORMED_FORMAT_STRING = "ER_MALFORMED_FORMAT_STRING";
   public static final String ER_STYLESHEET_REQUIRES_VERSION_ATTRIB = "ER_STYLESHEET_REQUIRES_VERSION_ATTRIB";
   public static final String ER_ILLEGAL_ATTRIBUTE_VALUE = "ER_ILLEGAL_ATTRIBUTE_VALUE";
   public static final String ER_CHOOSE_REQUIRES_WHEN = "ER_CHOOSE_REQUIRES_WHEN";
   public static final String ER_NO_APPLY_IMPORT_IN_FOR_EACH = "ER_NO_APPLY_IMPORT_IN_FOR_EACH";
   public static final String ER_CANT_USE_DTM_FOR_OUTPUT = "ER_CANT_USE_DTM_FOR_OUTPUT";
   public static final String ER_CANT_USE_DTM_FOR_INPUT = "ER_CANT_USE_DTM_FOR_INPUT";
   public static final String ER_CALL_TO_EXT_FAILED = "ER_CALL_TO_EXT_FAILED";
   public static final String ER_PREFIX_MUST_RESOLVE = "ER_PREFIX_MUST_RESOLVE";
   public static final String ER_INVALID_UTF16_SURROGATE = "ER_INVALID_UTF16_SURROGATE";
   public static final String ER_XSLATTRSET_USED_ITSELF = "ER_XSLATTRSET_USED_ITSELF";
   public static final String ER_CANNOT_MIX_XERCESDOM = "ER_CANNOT_MIX_XERCESDOM";
   public static final String ER_TOO_MANY_LISTENERS = "ER_TOO_MANY_LISTENERS";
   public static final String ER_IN_ELEMTEMPLATEELEM_READOBJECT = "ER_IN_ELEMTEMPLATEELEM_READOBJECT";
   public static final String ER_DUPLICATE_NAMED_TEMPLATE = "ER_DUPLICATE_NAMED_TEMPLATE";
   public static final String ER_INVALID_KEY_CALL = "ER_INVALID_KEY_CALL";
   public static final String ER_REFERENCING_ITSELF = "ER_REFERENCING_ITSELF";
   public static final String ER_ILLEGAL_DOMSOURCE_INPUT = "ER_ILLEGAL_DOMSOURCE_INPUT";
   public static final String ER_CLASS_NOT_FOUND_FOR_OPTION = "ER_CLASS_NOT_FOUND_FOR_OPTION";
   public static final String ER_REQUIRED_ELEM_NOT_FOUND = "ER_REQUIRED_ELEM_NOT_FOUND";
   public static final String ER_INPUT_CANNOT_BE_NULL = "ER_INPUT_CANNOT_BE_NULL";
   public static final String ER_URI_CANNOT_BE_NULL = "ER_URI_CANNOT_BE_NULL";
   public static final String ER_FILE_CANNOT_BE_NULL = "ER_FILE_CANNOT_BE_NULL";
   public static final String ER_SOURCE_CANNOT_BE_NULL = "ER_SOURCE_CANNOT_BE_NULL";
   public static final String ER_CANNOT_INIT_BSFMGR = "ER_CANNOT_INIT_BSFMGR";
   public static final String ER_CANNOT_CMPL_EXTENSN = "ER_CANNOT_CMPL_EXTENSN";
   public static final String ER_CANNOT_CREATE_EXTENSN = "ER_CANNOT_CREATE_EXTENSN";
   public static final String ER_INSTANCE_MTHD_CALL_REQUIRES = "ER_INSTANCE_MTHD_CALL_REQUIRES";
   public static final String ER_INVALID_ELEMENT_NAME = "ER_INVALID_ELEMENT_NAME";
   public static final String ER_ELEMENT_NAME_METHOD_STATIC = "ER_ELEMENT_NAME_METHOD_STATIC";
   public static final String ER_EXTENSION_FUNC_UNKNOWN = "ER_EXTENSION_FUNC_UNKNOWN";
   public static final String ER_MORE_MATCH_CONSTRUCTOR = "ER_MORE_MATCH_CONSTRUCTOR";
   public static final String ER_MORE_MATCH_METHOD = "ER_MORE_MATCH_METHOD";
   public static final String ER_MORE_MATCH_ELEMENT = "ER_MORE_MATCH_ELEMENT";
   public static final String ER_INVALID_CONTEXT_PASSED = "ER_INVALID_CONTEXT_PASSED";
   public static final String ER_POOL_EXISTS = "ER_POOL_EXISTS";
   public static final String ER_NO_DRIVER_NAME = "ER_NO_DRIVER_NAME";
   public static final String ER_NO_URL = "ER_NO_URL";
   public static final String ER_POOL_SIZE_LESSTHAN_ONE = "ER_POOL_SIZE_LESSTHAN_ONE";
   public static final String ER_INVALID_DRIVER = "ER_INVALID_DRIVER";
   public static final String ER_NO_STYLESHEETROOT = "ER_NO_STYLESHEETROOT";
   public static final String ER_ILLEGAL_XMLSPACE_VALUE = "ER_ILLEGAL_XMLSPACE_VALUE";
   public static final String ER_PROCESSFROMNODE_FAILED = "ER_PROCESSFROMNODE_FAILED";
   public static final String ER_RESOURCE_COULD_NOT_LOAD = "ER_RESOURCE_COULD_NOT_LOAD";
   public static final String ER_BUFFER_SIZE_LESSTHAN_ZERO = "ER_BUFFER_SIZE_LESSTHAN_ZERO";
   public static final String ER_UNKNOWN_ERROR_CALLING_EXTENSION = "ER_UNKNOWN_ERROR_CALLING_EXTENSION";
   public static final String ER_NO_NAMESPACE_DECL = "ER_NO_NAMESPACE_DECL";
   public static final String ER_ELEM_CONTENT_NOT_ALLOWED = "ER_ELEM_CONTENT_NOT_ALLOWED";
   public static final String ER_STYLESHEET_DIRECTED_TERMINATION = "ER_STYLESHEET_DIRECTED_TERMINATION";
   public static final String ER_ONE_OR_TWO = "ER_ONE_OR_TWO";
   public static final String ER_TWO_OR_THREE = "ER_TWO_OR_THREE";
   public static final String ER_COULD_NOT_LOAD_RESOURCE = "ER_COULD_NOT_LOAD_RESOURCE";
   public static final String ER_CANNOT_INIT_DEFAULT_TEMPLATES = "ER_CANNOT_INIT_DEFAULT_TEMPLATES";
   public static final String ER_RESULT_NULL = "ER_RESULT_NULL";
   public static final String ER_RESULT_COULD_NOT_BE_SET = "ER_RESULT_COULD_NOT_BE_SET";
   public static final String ER_NO_OUTPUT_SPECIFIED = "ER_NO_OUTPUT_SPECIFIED";
   public static final String ER_CANNOT_TRANSFORM_TO_RESULT_TYPE = "ER_CANNOT_TRANSFORM_TO_RESULT_TYPE";
   public static final String ER_CANNOT_TRANSFORM_SOURCE_TYPE = "ER_CANNOT_TRANSFORM_SOURCE_TYPE";
   public static final String ER_NULL_CONTENT_HANDLER = "ER_NULL_CONTENT_HANDLER";
   public static final String ER_NULL_ERROR_HANDLER = "ER_NULL_ERROR_HANDLER";
   public static final String ER_CANNOT_CALL_PARSE = "ER_CANNOT_CALL_PARSE";
   public static final String ER_NO_PARENT_FOR_FILTER = "ER_NO_PARENT_FOR_FILTER";
   public static final String ER_NO_STYLESHEET_IN_MEDIA = "ER_NO_STYLESHEET_IN_MEDIA";
   public static final String ER_NO_STYLESHEET_PI = "ER_NO_STYLESHEET_PI";
   public static final String ER_NOT_SUPPORTED = "ER_NOT_SUPPORTED";
   public static final String ER_PROPERTY_VALUE_BOOLEAN = "ER_PROPERTY_VALUE_BOOLEAN";
   public static final String ER_COULD_NOT_FIND_EXTERN_SCRIPT = "ER_COULD_NOT_FIND_EXTERN_SCRIPT";
   public static final String ER_RESOURCE_COULD_NOT_FIND = "ER_RESOURCE_COULD_NOT_FIND";
   public static final String ER_OUTPUT_PROPERTY_NOT_RECOGNIZED = "ER_OUTPUT_PROPERTY_NOT_RECOGNIZED";
   public static final String ER_FAILED_CREATING_ELEMLITRSLT = "ER_FAILED_CREATING_ELEMLITRSLT";
   public static final String ER_VALUE_SHOULD_BE_NUMBER = "ER_VALUE_SHOULD_BE_NUMBER";
   public static final String ER_VALUE_SHOULD_EQUAL = "ER_VALUE_SHOULD_EQUAL";
   public static final String ER_FAILED_CALLING_METHOD = "ER_FAILED_CALLING_METHOD";
   public static final String ER_FAILED_CREATING_ELEMTMPL = "ER_FAILED_CREATING_ELEMTMPL";
   public static final String ER_CHARS_NOT_ALLOWED = "ER_CHARS_NOT_ALLOWED";
   public static final String ER_ATTR_NOT_ALLOWED = "ER_ATTR_NOT_ALLOWED";
   public static final String ER_BAD_VALUE = "ER_BAD_VALUE";
   public static final String ER_ATTRIB_VALUE_NOT_FOUND = "ER_ATTRIB_VALUE_NOT_FOUND";
   public static final String ER_ATTRIB_VALUE_NOT_RECOGNIZED = "ER_ATTRIB_VALUE_NOT_RECOGNIZED";
   public static final String ER_NULL_URI_NAMESPACE = "ER_NULL_URI_NAMESPACE";
   public static final String ER_NUMBER_TOO_BIG = "ER_NUMBER_TOO_BIG";
   public static final String ER_CANNOT_FIND_SAX1_DRIVER = "ER_CANNOT_FIND_SAX1_DRIVER";
   public static final String ER_SAX1_DRIVER_NOT_LOADED = "ER_SAX1_DRIVER_NOT_LOADED";
   public static final String ER_SAX1_DRIVER_NOT_INSTANTIATED = "ER_SAX1_DRIVER_NOT_INSTANTIATED";
   public static final String ER_SAX1_DRIVER_NOT_IMPLEMENT_PARSER = "ER_SAX1_DRIVER_NOT_IMPLEMENT_PARSER";
   public static final String ER_PARSER_PROPERTY_NOT_SPECIFIED = "ER_PARSER_PROPERTY_NOT_SPECIFIED";
   public static final String ER_PARSER_ARG_CANNOT_BE_NULL = "ER_PARSER_ARG_CANNOT_BE_NULL";
   public static final String ER_FEATURE = "ER_FEATURE";
   public static final String ER_PROPERTY = "ER_PROPERTY";
   public static final String ER_NULL_ENTITY_RESOLVER = "ER_NULL_ENTITY_RESOLVER";
   public static final String ER_NULL_DTD_HANDLER = "ER_NULL_DTD_HANDLER";
   public static final String ER_NO_DRIVER_NAME_SPECIFIED = "ER_NO_DRIVER_NAME_SPECIFIED";
   public static final String ER_NO_URL_SPECIFIED = "ER_NO_URL_SPECIFIED";
   public static final String ER_POOLSIZE_LESS_THAN_ONE = "ER_POOLSIZE_LESS_THAN_ONE";
   public static final String ER_INVALID_DRIVER_NAME = "ER_INVALID_DRIVER_NAME";
   public static final String ER_ERRORLISTENER = "ER_ERRORLISTENER";
   public static final String ER_ASSERT_NO_TEMPLATE_PARENT = "ER_ASSERT_NO_TEMPLATE_PARENT";
   public static final String ER_ASSERT_REDUNDENT_EXPR_ELIMINATOR = "ER_ASSERT_REDUNDENT_EXPR_ELIMINATOR";
   public static final String ER_NOT_ALLOWED_IN_POSITION = "ER_NOT_ALLOWED_IN_POSITION";
   public static final String ER_NONWHITESPACE_NOT_ALLOWED_IN_POSITION = "ER_NONWHITESPACE_NOT_ALLOWED_IN_POSITION";
   public static final String INVALID_TCHAR = "INVALID_TCHAR";
   public static final String INVALID_QNAME = "INVALID_QNAME";
   public static final String INVALID_ENUM = "INVALID_ENUM";
   public static final String INVALID_NMTOKEN = "INVALID_NMTOKEN";
   public static final String INVALID_NCNAME = "INVALID_NCNAME";
   public static final String INVALID_BOOLEAN = "INVALID_BOOLEAN";
   public static final String INVALID_NUMBER = "INVALID_NUMBER";
   public static final String ER_ARG_LITERAL = "ER_ARG_LITERAL";
   public static final String ER_DUPLICATE_GLOBAL_VAR = "ER_DUPLICATE_GLOBAL_VAR";
   public static final String ER_DUPLICATE_VAR = "ER_DUPLICATE_VAR";
   public static final String ER_TEMPLATE_NAME_MATCH = "ER_TEMPLATE_NAME_MATCH";
   public static final String ER_INVALID_PREFIX = "ER_INVALID_PREFIX";
   public static final String ER_NO_ATTRIB_SET = "ER_NO_ATTRIB_SET";
   public static final String WG_FOUND_CURLYBRACE = "WG_FOUND_CURLYBRACE";
   public static final String WG_COUNT_ATTRIB_MATCHES_NO_ANCESTOR = "WG_COUNT_ATTRIB_MATCHES_NO_ANCESTOR";
   public static final String WG_EXPR_ATTRIB_CHANGED_TO_SELECT = "WG_EXPR_ATTRIB_CHANGED_TO_SELECT";
   public static final String WG_NO_LOCALE_IN_FORMATNUMBER = "WG_NO_LOCALE_IN_FORMATNUMBER";
   public static final String WG_LOCALE_NOT_FOUND = "WG_LOCALE_NOT_FOUND";
   public static final String WG_CANNOT_MAKE_URL_FROM = "WG_CANNOT_MAKE_URL_FROM";
   public static final String WG_CANNOT_LOAD_REQUESTED_DOC = "WG_CANNOT_LOAD_REQUESTED_DOC";
   public static final String WG_CANNOT_FIND_COLLATOR = "WG_CANNOT_FIND_COLLATOR";
   public static final String WG_FUNCTIONS_SHOULD_USE_URL = "WG_FUNCTIONS_SHOULD_USE_URL";
   public static final String WG_ENCODING_NOT_SUPPORTED_USING_UTF8 = "WG_ENCODING_NOT_SUPPORTED_USING_UTF8";
   public static final String WG_ENCODING_NOT_SUPPORTED_USING_JAVA = "WG_ENCODING_NOT_SUPPORTED_USING_JAVA";
   public static final String WG_SPECIFICITY_CONFLICTS = "WG_SPECIFICITY_CONFLICTS";
   public static final String WG_PARSING_AND_PREPARING = "WG_PARSING_AND_PREPARING";
   public static final String WG_ATTR_TEMPLATE = "WG_ATTR_TEMPLATE";
   public static final String WG_CONFLICT_BETWEEN_XSLSTRIPSPACE_AND_XSLPRESERVESPACE = "WG_CONFLICT_BETWEEN_XSLSTRIPSPACE_AND_XSLPRESERVESP";
   public static final String WG_ATTRIB_NOT_HANDLED = "WG_ATTRIB_NOT_HANDLED";
   public static final String WG_NO_DECIMALFORMAT_DECLARATION = "WG_NO_DECIMALFORMAT_DECLARATION";
   public static final String WG_OLD_XSLT_NS = "WG_OLD_XSLT_NS";
   public static final String WG_ONE_DEFAULT_XSLDECIMALFORMAT_ALLOWED = "WG_ONE_DEFAULT_XSLDECIMALFORMAT_ALLOWED";
   public static final String WG_XSLDECIMALFORMAT_NAMES_MUST_BE_UNIQUE = "WG_XSLDECIMALFORMAT_NAMES_MUST_BE_UNIQUE";
   public static final String WG_ILLEGAL_ATTRIBUTE = "WG_ILLEGAL_ATTRIBUTE";
   public static final String WG_COULD_NOT_RESOLVE_PREFIX = "WG_COULD_NOT_RESOLVE_PREFIX";
   public static final String WG_STYLESHEET_REQUIRES_VERSION_ATTRIB = "WG_STYLESHEET_REQUIRES_VERSION_ATTRIB";
   public static final String WG_ILLEGAL_ATTRIBUTE_NAME = "WG_ILLEGAL_ATTRIBUTE_NAME";
   public static final String WG_ILLEGAL_ATTRIBUTE_VALUE = "WG_ILLEGAL_ATTRIBUTE_VALUE";
   public static final String WG_EMPTY_SECOND_ARG = "WG_EMPTY_SECOND_ARG";
   public static final String WG_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML = "WG_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML";
   public static final String WG_PROCESSINGINSTRUCTION_NOTVALID_NCNAME = "WG_PROCESSINGINSTRUCTION_NOTVALID_NCNAME";
   public static final String WG_ILLEGAL_ATTRIBUTE_POSITION = "WG_ILLEGAL_ATTRIBUTE_POSITION";
   public static final String BAD_CODE = "BAD_CODE";
   public static final String FORMAT_FAILED = "FORMAT_FAILED";
   public static final String ERROR_STRING = "#error";
   public static final String ERROR_HEADER = "エラー: ";
   public static final String WARNING_HEADER = "警告: ";
   public static final String XSL_HEADER = "XSLT ";
   public static final String XML_HEADER = "XML ";
   /** @deprecated */
   public static final String QUERY_HEADER = "PATTERN ";

   public Object[][] getContents() {
      return new Object[][]{{"ER0000", "{0}"}, {"ER_NO_CURLYBRACE", "エラー: 式内では '{' を使用できません。"}, {"ER_ILLEGAL_ATTRIBUTE", "{0} に正しくない属性があります: {1}"}, {"ER_NULL_SOURCENODE_APPLYIMPORTS", "xsl:apply-imports 内の sourceNode がヌルです!"}, {"ER_CANNOT_ADD", "{0} を {1} に追加できません。"}, {"ER_NULL_SOURCENODE_HANDLEAPPLYTEMPLATES", "handleApplyTemplatesInstruction 内の sourceNode がヌルです!"}, {"ER_NO_NAME_ATTRIB", "{0} には name 属性が必要です。"}, {"ER_TEMPLATE_NOT_FOUND", "{0} という名前のテンプレートが見つかりませんでした。"}, {"ER_CANT_RESOLVE_NAME_AVT", "xsl:call-template 内の名前 AVT を解決できませんでした。"}, {"ER_REQUIRES_ATTRIB", "{0} には属性が必要です: {1}"}, {"ER_MUST_HAVE_TEST_ATTRIB", "{0} には ''test'' 属性が必要です。"}, {"ER_BAD_VAL_ON_LEVEL_ATTRIB", "level 属性で値が間違っています: {0}"}, {"ER_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML", "処理命令の名前は 'xml' にはできません。"}, {"ER_PROCESSINGINSTRUCTION_NOTVALID_NCNAME", "処理命令の名前は有効な NCName でなければなりません: {0}"}, {"ER_NEED_MATCH_ATTRIB", "{0} にモードがある場合は、match 属性が必要です。"}, {"ER_NEED_NAME_OR_MATCH_ATTRIB", "{0} には name または match のいずれかの属性が必要です。"}, {"ER_CANT_RESOLVE_NSPREFIX", "ネーム・スペース接頭部を解決できません: {0}"}, {"ER_ILLEGAL_VALUE", "xml:space には正しくない値があります: {0}"}, {"ER_NO_OWNERDOC", "下位ノードに所有者文書がありません!"}, {"ER_ELEMTEMPLATEELEM_ERR", "ElemTemplateElement エラー: {0}"}, {"ER_NULL_CHILD", "ヌルの子を追加しようとしています!"}, {"ER_NEED_SELECT_ATTRIB", "{0} には select 属性が必要です。"}, {"ER_NEED_TEST_ATTRIB", "xsl:when には 'test' 属性が必要です。"}, {"ER_NEED_NAME_ATTRIB", "xsl:with-param には 'name' 属性が必要です。"}, {"ER_NO_CONTEXT_OWNERDOC", "コンテキストに所有者文書がありません!"}, {"ER_COULD_NOT_CREATE_XML_PROC_LIAISON", "XML TransformerFactory Liaison を作成できませんでした: {0}"}, {"ER_PROCESS_NOT_SUCCESSFUL", "Xalan: 処理は成功しませんでした。"}, {"ER_NOT_SUCCESSFUL", "Xalan: は成功しませんでした。"}, {"ER_ENCODING_NOT_SUPPORTED", "エンコードはサポートされていません: {0}"}, {"ER_COULD_NOT_CREATE_TRACELISTENER", "TraceListener を作成できませんでした: {0}"}, {"ER_KEY_REQUIRES_NAME_ATTRIB", "xsl:key には 'name' 属性が必要です!"}, {"ER_KEY_REQUIRES_MATCH_ATTRIB", "xsl:key には 'match' 属性が必要です!"}, {"ER_KEY_REQUIRES_USE_ATTRIB", "xsl:key には 'use' 属性が必要です!"}, {"ER_REQUIRES_ELEMENTS_ATTRIB", "(StylesheetHandler) {0} には ''elements'' 属性が必要です!"}, {"ER_MISSING_PREFIX_ATTRIB", "(StylesheetHandler) {0} 属性の ''prefix'' がありません"}, {"ER_BAD_STYLESHEET_URL", "スタイルシート URL が間違っています: {0}"}, {"ER_FILE_NOT_FOUND", "スタイルシート・ファイルが見つかりませんでした: {0}"}, {"ER_IOEXCEPTION", "スタイルシート・ファイルによる入出力例外が起こりました: {0}"}, {"ER_NO_HREF_ATTRIB", "(StylesheetHandler) {0} の href 属性が見つかりませんでした。"}, {"ER_STYLESHEET_INCLUDES_ITSELF", "(StylesheetHandler) {0} が自分自身を直接的または間接的に組み込もうとしています!"}, {"ER_PROCESSINCLUDE_ERROR", "StylesheetHandler.processInclude エラー、{0}"}, {"ER_MISSING_LANG_ATTRIB", "(StylesheetHandler) {0} 属性の ''lang'' がありません"}, {"ER_MISSING_CONTAINER_ELEMENT_COMPONENT", "(StylesheetHandler) {0} エレメントの場所を間違えた可能性があります。 コンテナー・エレメント ''component'' がありません。"}, {"ER_CAN_ONLY_OUTPUT_TO_ELEMENT", "Element、DocumentFragment、Document、または PrintWriter への出力しかできません。"}, {"ER_PROCESS_ERROR", "StylesheetRoot.処理エラー"}, {"ER_UNIMPLNODE_ERROR", "UnImplNode エラー: {0}"}, {"ER_NO_SELECT_EXPRESSION", "エラー! xpath select 式 (-select) が見つかりませんでした。"}, {"ER_CANNOT_SERIALIZE_XSLPROCESSOR", "XSLProcessor をシリアライズできません!"}, {"ER_NO_INPUT_STYLESHEET", "スタイルシート入力が指定されていませんでした!"}, {"ER_FAILED_PROCESS_STYLESHEET", "スタイルシートを処理することに失敗しました!"}, {"ER_COULDNT_PARSE_DOC", "{0} 文書を構文解析できませんでした!"}, {"ER_COULDNT_FIND_FRAGMENT", "フラグメントが見つかりませんでした: {0}"}, {"ER_NODE_NOT_ELEMENT", "フラグメント ID により指されているノードがエレメントでありませんでした: {0}"}, {"ER_FOREACH_NEED_MATCH_OR_NAME_ATTRIB", "for-each には match または name のいずれかの属性が必要です。"}, {"ER_TEMPLATES_NEED_MATCH_OR_NAME_ATTRIB", "テンプレートには match または name のいずれかの属性が必要です。"}, {"ER_NO_CLONE_OF_DOCUMENT_FRAG", "文書フラグメントの複製がありません!"}, {"ER_CANT_CREATE_ITEM", "項目を結果ツリーに作成できません: {0}"}, {"ER_XMLSPACE_ILLEGAL_VALUE", "ソース XML 内の xml:space には正しくない値があります: {0}"}, {"ER_NO_XSLKEY_DECLARATION", "{0} の xsl:key 宣言がありません!"}, {"ER_CANT_CREATE_URL", "エラー! {0} の URL を作成できません。"}, {"ER_XSLFUNCTIONS_UNSUPPORTED", "xsl:functions はサポートされていません。"}, {"ER_PROCESSOR_ERROR", "XSLT TransformerFactory エラー"}, {"ER_NOT_ALLOWED_INSIDE_STYLESHEET", "(StylesheetHandler) {0} はスタイルシートの内部では許可されていません!"}, {"ER_RESULTNS_NOT_SUPPORTED", "result-ns はもうサポートされていません!  代りに xsl:output を使用してください。"}, {"ER_DEFAULTSPACE_NOT_SUPPORTED", "default-space はもうサポートされていません!  代りに xsl:strip-space または xsl:preserve-space を使用してください。"}, {"ER_INDENTRESULT_NOT_SUPPORTED", "indent-result はもうサポートされていません!  代りに xsl:output を使用してください。"}, {"ER_ILLEGAL_ATTRIB", "(StylesheetHandler) {0} には正しくない属性があります: {1}"}, {"ER_UNKNOWN_XSL_ELEM", "不明の XSL エレメント: {0}"}, {"ER_BAD_XSLSORT_USE", "(StylesheetHandler) xsl:sort は xsl:apply-templates または xsl:for-each としか使用できません。"}, {"ER_MISPLACED_XSLWHEN", "(StylesheetHandler) xsl:when の場所を誤っていました!"}, {"ER_XSLWHEN_NOT_PARENTED_BY_XSLCHOOSE", "(StylesheetHandler) xsl:when が xsl:choose により親になっていませんでした!"}, {"ER_MISPLACED_XSLOTHERWISE", "(StylesheetHandler) xsl:otherwise の場所を誤っていました!"}, {"ER_XSLOTHERWISE_NOT_PARENTED_BY_XSLCHOOSE", "(StylesheetHandler) xsl:otherwise が xsl:choose により親になっていませんでした!"}, {"ER_NOT_ALLOWED_INSIDE_TEMPLATE", "(StylesheetHandler) {0} はテンプレートの内部では許可されていません!"}, {"ER_UNKNOWN_EXT_NS_PREFIX", "(StylesheetHandler) {0} 拡張ネーム・スペース接頭部 {1} が不明です。"}, {"ER_IMPORTS_AS_FIRST_ELEM", "(StylesheetHandler) インポートは、スタイルシート内の先頭エレメントとしてのみ入れることができます!"}, {"ER_IMPORTING_ITSELF", "(StylesheetHandler) {0} が自分自身を直接的または間接的にインポートしようとしています!"}, {"ER_XMLSPACE_ILLEGAL_VAL", "(StylesheetHandler) xml:space に正しくない値があります: {0}"}, {"ER_PROCESSSTYLESHEET_NOT_SUCCESSFUL", "processStylesheet は成功していません!"}, {"ER_SAX_EXCEPTION", "SAX 例外"}, {"ER_XSLT_ERROR", "XSLT エラー"}, {"ER_CURRENCY_SIGN_ILLEGAL", "通貨記号は書式パターン・ストリング内で許可されていません。"}, {"ER_DOCUMENT_FUNCTION_INVALID_IN_STYLESHEET_DOM", "文書機能はスタイル・シート DOM ではサポートされていません!"}, {"ER_CANT_RESOLVE_PREFIX_OF_NON_PREFIX_RESOLVER", "非接頭部リゾルバーの接頭部を解決できません!"}, {"ER_REDIRECT_COULDNT_GET_FILENAME", "リダイレクト拡張: ファイル名を取得できませんでした。file または select 属性は有効なストリングを戻さなければなりません。"}, {"ER_CANNOT_BUILD_FORMATTERLISTENER_IN_REDIRECT", "FormatterListener はリダイレクト拡張内にビルドできません!"}, {"ER_INVALID_PREFIX_IN_EXCLUDERESULTPREFIX", "exclude-result-prefixes 内の接頭部が無効です: {0}"}, {"ER_MISSING_NS_URI", "指定された接頭部のネーム・スペース URI がありません。"}, {"ER_MISSING_ARG_FOR_OPTION", "オプションの引き数がありません: {0}"}, {"ER_INVALID_OPTION", "無効なオプション: {0}"}, {"ER_MALFORMED_FORMAT_STRING", "誤った形式の書式ストリング: {0}"}, {"ER_STYLESHEET_REQUIRES_VERSION_ATTRIB", "xsl:stylesheet には 'version' 属性が必要です!"}, {"ER_ILLEGAL_ATTRIBUTE_VALUE", "属性: {0} には正しくない値: {1} があります。"}, {"ER_CHOOSE_REQUIRES_WHEN", "xsl:choose には xsl:when が必要です。"}, {"ER_NO_APPLY_IMPORT_IN_FOR_EACH", "xsl:apply-imports は xsl:for-each 内では許可されていません。"}, {"ER_CANT_USE_DTM_FOR_OUTPUT", "DTMLiaison は出力 DOM ノードに使用できません... 代りに org.apache.xpath.DOM2Helper を渡してください!"}, {"ER_CANT_USE_DTM_FOR_INPUT", "DTMLiaison は入力 DOM ノードに使用できません... 代りに org.apache.xpath.DOM2Helper を渡してください!"}, {"ER_CALL_TO_EXT_FAILED", "拡張エレメントへの呼び出しが失敗しました: {0}"}, {"ER_PREFIX_MUST_RESOLVE", "接頭部はネーム・スペースに解決されなければなりません: {0}"}, {"ER_INVALID_UTF16_SURROGATE", "無効な UTF-16 サロゲートが検出されました: {0} ?"}, {"ER_XSLATTRSET_USED_ITSELF", "xsl:attribute-set {0} が自身を使用しているため、無限ループの原因となります。"}, {"ER_CANNOT_MIX_XERCESDOM", "非 Xerces-DOM 入力と Xerces-DOM 出力は混用できません!"}, {"ER_TOO_MANY_LISTENERS", "addTraceListenersToStylesheet - TooManyListenersException"}, {"ER_IN_ELEMTEMPLATEELEM_READOBJECT", "ElemTemplateElement.readObject 内: {0}"}, {"ER_DUPLICATE_NAMED_TEMPLATE", "次の名前のテンプレートが複数見つかりました: {0}"}, {"ER_INVALID_KEY_CALL", "無効な関数呼び出し: 再帰的 key() 呼び出しは許可されていません。"}, {"ER_REFERENCING_ITSELF", "変数 {0} が直接的または間接的に自分自身に参照づけています!"}, {"ER_ILLEGAL_DOMSOURCE_INPUT", "newTemplates の DOMSource の入力をヌルにはできません!"}, {"ER_CLASS_NOT_FOUND_FOR_OPTION", "オプション {0} のクラス・ファイルが見つかりません。"}, {"ER_REQUIRED_ELEM_NOT_FOUND", "必要なエレメントが見つかりません: {0}"}, {"ER_INPUT_CANNOT_BE_NULL", "InputStream をヌルにはできません。"}, {"ER_URI_CANNOT_BE_NULL", "URI をヌルにはできません。"}, {"ER_FILE_CANNOT_BE_NULL", "ファイルをヌルにはできません。"}, {"ER_SOURCE_CANNOT_BE_NULL", "InputSource をヌルにはできません。"}, {"ER_CANNOT_INIT_BSFMGR", "BSF マネージャーを初期化できませんでした。"}, {"ER_CANNOT_CMPL_EXTENSN", "拡張機能をコンパイルできませんでした。"}, {"ER_CANNOT_CREATE_EXTENSN", "原因: {1} のために拡張機能: {0} を作成できませんでした。"}, {"ER_INSTANCE_MTHD_CALL_REQUIRES", "メソッド {0} へのインスタンス・メソッド呼び出しにはオブジェクト・インスタンスが最初の引き数として必要です。"}, {"ER_INVALID_ELEMENT_NAME", "無効なエレメント名が指定されました: {0}"}, {"ER_ELEMENT_NAME_METHOD_STATIC", "エレメント名メソッドは静的でなければなりません: {0}"}, {"ER_EXTENSION_FUNC_UNKNOWN", "拡張機能 {0} : {1} が不明です。"}, {"ER_MORE_MATCH_CONSTRUCTOR", "{0} のコンストラクターの最適一致が複数あります。"}, {"ER_MORE_MATCH_METHOD", "メソッド {0} の最適一致が複数あります。"}, {"ER_MORE_MATCH_ELEMENT", "エレメント・メソッド {0} の最適一致が複数あります。"}, {"ER_INVALID_CONTEXT_PASSED", "{0} を評価するために渡されたコンテキストが無効です。"}, {"ER_POOL_EXISTS", "プールはすでに存在しています。"}, {"ER_NO_DRIVER_NAME", "ドライバー名が指定されていません。"}, {"ER_NO_URL", "URL が指定されていません。"}, {"ER_POOL_SIZE_LESSTHAN_ONE", "プール・サイズが 1 より小です!"}, {"ER_INVALID_DRIVER", "無効なドライバー名が指定されました!"}, {"ER_NO_STYLESHEETROOT", "スタイルシートのルートが見つかりませんでした!"}, {"ER_ILLEGAL_XMLSPACE_VALUE", "xml:space の値が正しくありません。"}, {"ER_PROCESSFROMNODE_FAILED", "processFromNode が失敗しました。"}, {"ER_RESOURCE_COULD_NOT_LOAD", "リソース [ {0} ] をロードできませんでした: {1} \n {2} \t {3}"}, {"ER_BUFFER_SIZE_LESSTHAN_ZERO", "バッファー・サイズ <=0"}, {"ER_UNKNOWN_ERROR_CALLING_EXTENSION", "エクステンションを呼び出し時に不明エラー"}, {"ER_NO_NAMESPACE_DECL", "接頭部 {0} には対応しているネーム・スペース宣言がありません。"}, {"ER_ELEM_CONTENT_NOT_ALLOWED", "エレメントのコンテンツは lang=javaclass {0} の場合は許可されていません。"}, {"ER_STYLESHEET_DIRECTED_TERMINATION", "スタイルシートで終了が指図されました。"}, {"ER_ONE_OR_TWO", "1 または 2"}, {"ER_TWO_OR_THREE", "2 または 3"}, {"ER_COULD_NOT_LOAD_RESOURCE", "{0} をロードできませんでした (CLASSPATH を調べてください)。現在はまさにデフォルトを使用中です。"}, {"ER_CANNOT_INIT_DEFAULT_TEMPLATES", "デフォルト・テンプレートを初期化できません。"}, {"ER_RESULT_NULL", "結果はヌルにはならないはずです。"}, {"ER_RESULT_COULD_NOT_BE_SET", "結果を設定できませんでした。"}, {"ER_NO_OUTPUT_SPECIFIED", "出力が指定されていません。"}, {"ER_CANNOT_TRANSFORM_TO_RESULT_TYPE", "タイプ {0} の結果に変換できません"}, {"ER_CANNOT_TRANSFORM_SOURCE_TYPE", "タイプ {0} のソースを変換できません"}, {"ER_NULL_CONTENT_HANDLER", "ヌルのコンテンツ・ハンドラー"}, {"ER_NULL_ERROR_HANDLER", "ヌルのエラー・ハンドラー"}, {"ER_CANNOT_CALL_PARSE", "ContentHandler が未設定の場合は parse の呼び出しはできません。"}, {"ER_NO_PARENT_FOR_FILTER", "フィルターの親がありません。"}, {"ER_NO_STYLESHEET_IN_MEDIA", "スタイルシートが {0}、メディア= {1} に見つかりません。"}, {"ER_NO_STYLESHEET_PI", "XML スタイルシート PI が {0} に見つかりません。"}, {"ER_NOT_SUPPORTED", "サポートされていません: {0}"}, {"ER_PROPERTY_VALUE_BOOLEAN", "プロパティー {0} の値はブール・インスタンスにする必要があります。"}, {"ER_COULD_NOT_FIND_EXTERN_SCRIPT", "{0} の外部スクリプトへ到達できませんでした。"}, {"ER_RESOURCE_COULD_NOT_FIND", "リソース [ {0} ] は見つかりませんでした。\n {1}"}, {"ER_OUTPUT_PROPERTY_NOT_RECOGNIZED", "出力プロパティーは認識されていません: {0}"}, {"ER_FAILED_CREATING_ELEMLITRSLT", "ElemLiteralResult インスタンスの作成が失敗しました。"}, {"ER_VALUE_SHOULD_BE_NUMBER", "{0} の値には構文解析可能番号が含まれているはずです。"}, {"ER_VALUE_SHOULD_EQUAL", "{0} の値は yes または no と等しくなければなりません。"}, {"ER_FAILED_CALLING_METHOD", "{0} メソッドの呼び出しが失敗しました。"}, {"ER_FAILED_CREATING_ELEMTMPL", "ElemTemplateElement インスタンスの作成が失敗しました。"}, {"ER_CHARS_NOT_ALLOWED", "文字は文書内のこのポイントでは許可されていません。"}, {"ER_ATTR_NOT_ALLOWED", "\"{0}\" 属性は {1} エレメントでは許可されていません!"}, {"ER_BAD_VALUE", "{0} の間違った値 {1} "}, {"ER_ATTRIB_VALUE_NOT_FOUND", "{0} 属性値が見つかりません。 "}, {"ER_ATTRIB_VALUE_NOT_RECOGNIZED", "{0} 属性値は認識されません。 "}, {"ER_NULL_URI_NAMESPACE", "ネーム・スペース接頭部をヌルの URI で生成しようとしています。"}, {"ER_NUMBER_TOO_BIG", "最大 Long 整数より大きい数をフォーマットしようとしています。"}, {"ER_CANNOT_FIND_SAX1_DRIVER", "SAX1 ドライバー・クラス {0} が見つかりません。"}, {"ER_SAX1_DRIVER_NOT_LOADED", "SAX1 ドライバー・クラス {0} が見つかりましたがロードできません。"}, {"ER_SAX1_DRIVER_NOT_INSTANTIATED", "SAX1 ドライバー・クラス {0} がロードされましたがインスタンス生成できません。"}, {"ER_SAX1_DRIVER_NOT_IMPLEMENT_PARSER", "SAX1 ドライバー・クラス {0} が org.xml.sax.Parser をインプリメントしていません。"}, {"ER_PARSER_PROPERTY_NOT_SPECIFIED", "システム・プロパティー org.xml.sax.parser は指定されていません。"}, {"ER_PARSER_ARG_CANNOT_BE_NULL", "パーサーの引き数をヌルにしてはなりません。"}, {"ER_FEATURE", "フィーチャー: {0}"}, {"ER_PROPERTY", "プロパティー: {0}"}, {"ER_NULL_ENTITY_RESOLVER", "ヌル・エンティティー・リゾルバー"}, {"ER_NULL_DTD_HANDLER", "ヌル DTD ハンドラー"}, {"ER_NO_DRIVER_NAME_SPECIFIED", "ドライバー名が指定されていません!"}, {"ER_NO_URL_SPECIFIED", "URL が指定されていません!"}, {"ER_POOLSIZE_LESS_THAN_ONE", "プール・サイズが 1 より小です!"}, {"ER_INVALID_DRIVER_NAME", "無効なドライバー名が指定されました!"}, {"ER_ERRORLISTENER", "ErrorListener"}, {"ER_ASSERT_NO_TEMPLATE_PARENT", "プログラマーのエラー! expr には ElemTemplateElement 親がありません!"}, {"ER_ASSERT_REDUNDENT_EXPR_ELIMINATOR", "RedundentExprEliminator 内のプログラマーのアサーション: {0}"}, {"ER_NOT_ALLOWED_IN_POSITION", "{0} はスタイルシートのこの位置では許可されません!"}, {"ER_NONWHITESPACE_NOT_ALLOWED_IN_POSITION", "空白文字以外のテキストはスタイルシートのこの位置では許可されません!"}, {"INVALID_TCHAR", "正しくない値: {1} が CHAR 属性: {0} に使用されました。CHAR タイプの属性は 1 文字でなければなりません!"}, {"INVALID_QNAME", "正しくない値: {1} が QNAME 属性: {0} に使用されました。"}, {"INVALID_ENUM", "正しくない値: {1} が ENUM 属性: {0} に使用されました。  有効値: {2}。"}, {"INVALID_NMTOKEN", "正しくない値: {1} が NMTOKEN 属性: {0} に使用されました。 "}, {"INVALID_NCNAME", "正しくない値: {1} が NCNAME 属性: {0} に使用されました。 "}, {"INVALID_BOOLEAN", "正しくない値: {1} が boolean 属性: {0} に使用されました。 "}, {"INVALID_NUMBER", "正しくない値: {1} が number 属性: {0} に使用されました。 "}, {"ER_ARG_LITERAL", "マッチング・パターンの {0} への引き数はリテラルでなければなりません。"}, {"ER_DUPLICATE_GLOBAL_VAR", "グローバル変数宣言が重複しています。"}, {"ER_DUPLICATE_VAR", "変数宣言が重複しています。"}, {"ER_TEMPLATE_NAME_MATCH", "xsl:template には name または match 属性 (あるいはその両方) が必要です。"}, {"ER_INVALID_PREFIX", "exclude-result-prefixes 内の接頭部が無効です: {0}"}, {"ER_NO_ATTRIB_SET", "{0} という名前の attribute-set が存在していません。"}, {"WG_FOUND_CURLYBRACE", "'}' が見つかりましたが、オープンされた属性テンプレートがありません!"}, {"WG_COUNT_ATTRIB_MATCHES_NO_ANCESTOR", "警告: count 属性が xsl:number 内の上位と一致しません! ターゲット = {0}"}, {"WG_EXPR_ATTRIB_CHANGED_TO_SELECT", "旧構文: 'expr' 属性の名前が 'select' に変更されています。"}, {"WG_NO_LOCALE_IN_FORMATNUMBER", "Xalan はフォーマット番号関数内でまだロケール名を処理しません。"}, {"WG_LOCALE_NOT_FOUND", "警告: xml:lang={0} のロケールが見つかりませんでした。"}, {"WG_CANNOT_MAKE_URL_FROM", "URL を {0} から作成できません。"}, {"WG_CANNOT_LOAD_REQUESTED_DOC", "要求された doc: {0} をロードできません。"}, {"WG_CANNOT_FIND_COLLATOR", "<sort xml:lang={0} のコレーターが見つかりませんでした。"}, {"WG_FUNCTIONS_SHOULD_USE_URL", "旧構文: 関数命令では {0} の URL を使用する必要があります。"}, {"WG_ENCODING_NOT_SUPPORTED_USING_UTF8", "エンコードはサポートされません: {0}、UTF-8 を使用中。"}, {"WG_ENCODING_NOT_SUPPORTED_USING_JAVA", "エンコードはサポートされません: {0}、Java {1} を使用中。"}, {"WG_SPECIFICITY_CONFLICTS", "限定性の矛盾が検出されました: {0} スタイルシート内で最後に検出されたものが使用されます。"}, {"WG_PARSING_AND_PREPARING", "========= {0} を構文解析中および準備中 =========="}, {"WG_ATTR_TEMPLATE", "属性テンプレート {0}"}, {"WG_CONFLICT_BETWEEN_XSLSTRIPSPACE_AND_XSLPRESERVESP", "xsl:strip-space と xsl:preserve-space の間のマッチングの矛盾"}, {"WG_ATTRIB_NOT_HANDLED", "Xalan はまだ {0} 属性を処理しません!"}, {"WG_NO_DECIMALFORMAT_DECLARATION", "10 進数形式の宣言が見つかりません: {0}"}, {"WG_OLD_XSLT_NS", "XSLT ネーム・スペースがないか誤っています。"}, {"WG_ONE_DEFAULT_XSLDECIMALFORMAT_ALLOWED", "デフォルトの xsl:decimal-format 宣言は 1 つしか許可されていません。"}, {"WG_XSLDECIMALFORMAT_NAMES_MUST_BE_UNIQUE", "xsl:decimal-format 名は固有でなければなりません。 名前 \"{0}\" が重複していました。"}, {"WG_ILLEGAL_ATTRIBUTE", "{0} に正しくない属性があります: {1}"}, {"WG_COULD_NOT_RESOLVE_PREFIX", "ネーム・スペース接頭部を解決できませんでした: {0}。 ノードは無視されます。"}, {"WG_STYLESHEET_REQUIRES_VERSION_ATTRIB", "xsl:stylesheet には 'version' 属性が必要です!"}, {"WG_ILLEGAL_ATTRIBUTE_NAME", "正しくない属性名: {0}"}, {"WG_ILLEGAL_ATTRIBUTE_VALUE", "属性 {0}: {1} に使用された値は正しくありません。"}, {"WG_EMPTY_SECOND_ARG", "文書機能の 2 番目の引き数から得られた nodeset が空です。空の node-set を戻します。"}, {"WG_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML", "xsl:processing-instruction 名の 'name' 属性の値は 'xml' であってはなりません。"}, {"WG_PROCESSINGINSTRUCTION_NOTVALID_NCNAME", "xsl:processing-instruction の 'name' 属性の値は有効な NCName でなければなりません: {0}"}, {"WG_ILLEGAL_ATTRIBUTE_POSITION", "下位ノードの後またはエレメントが生成される前に属性 {0} を追加できません。属性は無視されます。"}, {"ui_language", "en"}, {"help_language", "en"}, {"language", "en"}, {"BAD_CODE", "createMessage へのパラメーターが境界外でした。"}, {"FORMAT_FAILED", "messageFormat 呼び出し中に例外がスローされました。"}, {"version", ">>>>>>> Xalan バージョン "}, {"version2", "<<<<<<<"}, {"yes", "はい"}, {"line", "行 #"}, {"column", "桁 #"}, {"xsldone", "XSLProcessor: 完了"}, {"xslProc_option", "Xalan-J コマンド行 Process クラス・オプション"}, {"xslProc_option", "Xalan-J コマンド行 Process クラス・オプション:"}, {"xslProc_invalid_xsltc_option", "オプション {0} は XSLTC モードではサポートされていません。"}, {"xslProc_invalid_xalan_option", "オプション {0} は -XSLTC と一緒にしか使用できません。"}, {"xslProc_no_input", "エラー: スタイルシートがないか入力 xml が指定されていません。 使用法の説明については、オプションなしでこのコマンドを実行してください。"}, {"xslProc_common_options", "-共通オプション-"}, {"xslProc_xalan_options", "-Xalan 用オプション-"}, {"xslProc_xsltc_options", "-XSLTC 用オプション-"}, {"xslProc_return_to_continue", "(続けるには <return> を押してください)"}, {"optionXSLTC", "   [-XSLTC (変換に XSLTC を使用)]"}, {"optionIN", "   [-IN inputXMLURL]"}, {"optionXSL", "   [-XSL XSLTransformationURL]"}, {"optionOUT", "   [-OUT outputFileName]"}, {"optionLXCIN", "   [-LXCIN compiledStylesheetFileNameIn]"}, {"optionLXCOUT", "   [-LXCOUT compiledStylesheetFileNameOutOut]"}, {"optionPARSER", "   [-PARSER parser liaison の完全修飾クラス名]"}, {"optionE", "   [-E (エンティティー ref を拡張しない)]"}, {"optionV", "   [-E (エンティティー ref を拡張しない)]"}, {"optionQC", "   [-QC (静止パターン矛盾警告)]"}, {"optionQ", "   [-Q  (静止モード)]"}, {"optionLF", "[-LF (LF (改行) を出力時のみに使用  {デフォルトは CR/LF})]"}, {"optionCR", "[-CR (CR (復帰) を出力時のみに使用 {デフォルトは CR/LF})]"}, {"optionESCAPE", "[-ESCAPE (エスケープする文字 {デフォルトは <>&\"'\\r\\n}]"}, {"optionINDENT", "[-INDENT (字下げするスペースを制御 {デフォルトは 0})]"}, {"optionTT", "   [-TT (テンプレートを呼び出し中にトレース。)]"}, {"optionTG", "   [-TG (各生成イベントをトレース。)]"}, {"optionTS", "   [-TS (各選択イベントをトレース。)]"}, {"optionTTC", "   [-TTC (テンプレートの子を呼び出し中にトレース。)]"}, {"optionTCLASS", "   [-TCLASS (トレース拡張機能の TraceListener クラス。)]"}, {"optionVALIDATE", "   [-VALIDATE (妥当性検査を実行するかどうかを設定。  デフォルトでは、妥当性検査はオフです。)]"}, {"optionEDUMP", "[-EDUMP {optional filename} (エラー時に stackdump を実行。)]"}, {"optionXML", "   [-XML (XML フォーマッターを使用および XML ヘッダーを追加。)]"}, {"optionTEXT", "   [-TEXT (シンプル・テキスト・フォーマッターを使用。)]"}, {"optionHTML", "   [-HTML (HTML フォーマッターを使用。)]"}, {"optionPARAM", "   [-PARAM 名前式 (stylesheet パラメーターを設定。)]"}, {"noParsermsg1", "XSL 処理は成功しませんでした。"}, {"noParsermsg2", "** パーサーが見つかりませんでした **"}, {"noParsermsg3", "クラスパスを調べてください。"}, {"noParsermsg4", "IBM の XML Parser for Java がない場合は、次のサイトからダウンロードできます:"}, {"noParsermsg5", "IBM AlphaWorks: http://www.alphaworks.ibm.com/formula/xml"}, {"optionURIRESOLVER", "   [-URIRESOLVER 絶対クラス名 (URI を解決するために使用する URIResolver)]"}, {"optionENTITYRESOLVER", "   [-ENTITYRESOLVER 絶対クラス名 (エンティティーを解決するために使用する EntityResolver)]"}, {"optionCONTENTHANDLER", "   [-CONTENTHANDLER 絶対クラス名 (出力をシリアライズするために使用する ContentHandler)]"}, {"optionLINENUMBERS", "   [-L ソース・ドキュメントの行番号を使用]"}, {"optionMEDIA", "   [-MEDIA mediaType (文書と関連したスタイルシートを検索するメディア属性を使用。)]"}, {"optionFLAVOR", "   [-FLAVOR flavorName (変換を実行するために s2s=SAX または d2d=DOM を明示的に使用。)]"}, {"optionDIAG", "   [-DIAG (変換にかかった全ミリ秒を印刷。)]"}, {"optionINCREMENTAL", "   [-INCREMENTAL (http://xml.apache.org/xalan/features/incremental を true に設定することにより増分 DTM 構造を要求。)]"}, {"optionNOOPTIMIMIZE", "   [-NOOPTIMIMIZE (http://xml.apache.org/xalan/features/optimize を false に設定することによりスタイルシート最適化処理なしを要求。)]"}, {"optionRL", "   [-RL recursionlimit (スタイルシートの再帰の深さについての数値限界を主張。)]"}, {"optionXO", "   [-XO [transletName] (名前を生成後の translet に割り当て)]"}, {"optionXD", "   [-XD destinationDirectory (宛先ディレクトリーを translet に指定)]"}, {"optionXJ", "   [-XJ jarfile (translet クラスを名前 <jarfile> の jar ファイルにパッケージします)]"}, {"optionXP", "   [-XP package (パッケージ名接頭部をすべての生成後の translet クラスに指定します)]"}, {"optionXN", "   [-XN (テンプレートをインラインで使用可能にします)]"}, {"optionXX", "   [-XX (追加のデバッグ・メッセージ出力をオンにします)]"}, {"optionXT", "   [-XT (可能な場合は translet を使用して変換)]"}, {"diagTiming", "--------- {0} の {1} による変換には {2} ミリ秒かかりました"}, {"recursionTooDeep", "テンプレートのネストが深すぎます。 ネスト = {0}、テンプレート {1} {2}"}, {"nameIs", "名前は"}, {"matchPatternIs", "マッチング・パターンは"}};
   }

   public static final XSLTErrorResources loadResourceBundle(String className) throws MissingResourceException {
      Locale locale = Locale.getDefault();
      String suffix = getResourceSuffix(locale);

      try {
         return (XSLTErrorResources)ResourceBundle.getBundle(className + suffix, locale);
      } catch (MissingResourceException var6) {
         try {
            return (XSLTErrorResources)ResourceBundle.getBundle(className, new Locale("en", "US"));
         } catch (MissingResourceException var5) {
            throw new MissingResourceException("Could not load any resource bundles.", className, "");
         }
      }
   }

   private static final String getResourceSuffix(Locale locale) {
      String suffix = "_" + locale.getLanguage();
      String country = locale.getCountry();
      if (country.equals("TW")) {
         suffix = suffix + "_" + country;
      }

      return suffix;
   }
}
