package org.w3c.dom.svg;

public interface SVGRenderingIntent {
   short RENDERING_INTENT_UNKNOWN = 0;
   short RENDERING_INTENT_AUTO = 1;
   short RENDERING_INTENT_PERCEPTUAL = 2;
   short RENDERING_INTENT_RELATIVE_COLORIMETRIC = 3;
   short RENDERING_INTENT_SATURATION = 4;
   short RENDERING_INTENT_ABSOLUTE_COLORIMETRIC = 5;
}
