package com.mxgraph.util;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Stroke;
import java.awt.image.BufferedImage;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

public class mxConstants {
   public static double RAD_PER_DEG = 0.0174532;
   public static double DEG_PER_RAD = 57.2957795;
   public static double MIN_SCALE_FOR_ROUNDED_LINES = 0.05;
   public static double DEFAULT_HOTSPOT = 0.3;
   public static int MIN_HOTSPOT_SIZE = 8;
   public static int MAX_HOTSPOT_SIZE = 0;
   public static String NS_SVG = "http://www.w3.org/2000/svg";
   public static String NS_XHTML = "http://www.w3.org/1999/xhtml";
   public static String NS_XLINK = "http://www.w3.org/1999/xlink";
   public static Image EMPTY_IMAGE = new BufferedImage(1, 1, 1);
   public static String DEFAULT_FONTFAMILIES = "Arial,Helvetica";
   public static String DEFAULT_FONTFAMILY = "Dialog";
   public static int DEFAULT_FONTSIZE = 11;
   public static int DEFAULT_STARTSIZE = 40;
   public static int LINESPACING = 0;
   public static int LABEL_INSET = 3;
   public static double LABEL_SCALE_BUFFER = 0.9;
   public static int DEFAULT_MARKERSIZE = 6;
   public static int DEFAULT_IMAGESIZE = 24;
   public static Color SHADOW_COLOR;
   public static int SHADOW_OFFSETX;
   public static int SHADOW_OFFSETY;
   public static String W3C_SHADOWCOLOR;
   public static String SVG_SHADOWTRANSFORM;
   public static Color DEFAULT_VALID_COLOR;
   public static Color DEFAULT_INVALID_COLOR;
   public static float[] DEFAULT_DASHED_PATTERN;
   public static double DEFAULT_LABEL_BUFFER;
   public static Color RUBBERBAND_BORDERCOLOR;
   public static Color RUBBERBAND_FILLCOLOR;
   public static int HANDLE_SIZE;
   public static int LABEL_HANDLE_SIZE;
   public static Color HANDLE_BORDERCOLOR;
   public static Color HANDLE_FILLCOLOR;
   public static Color LABEL_HANDLE_FILLCOLOR;
   public static Color CONNECT_HANDLE_FILLCOLOR;
   public static Color LOCKED_HANDLE_FILLCOLOR;
   public static boolean CONNECT_HANDLE_ENABLED;
   public static int CONNECT_HANDLE_SIZE;
   public static Color EDGE_SELECTION_COLOR;
   public static Color VERTEX_SELECTION_COLOR;
   public static Stroke EDGE_SELECTION_STROKE;
   public static Stroke VERTEX_SELECTION_STROKE;
   public static Stroke PREVIEW_STROKE;
   public static Border PREVIEW_BORDER;
   public static int ENTITY_SEGMENT;
   public static double RECTANGLE_ROUNDING_FACTOR;
   public static double LINE_ARCSIZE;
   public static int ARROW_SPACING;
   public static int ARROW_WIDTH;
   public static int ARROW_SIZE;
   public static String NONE;
   public static String STYLE_PERIMETER;
   public static String STYLE_SOURCE_PORT;
   public static String STYLE_TARGET_PORT;
   public static String STYLE_OPACITY;
   public static String STYLE_TEXT_OPACITY;
   public static String STYLE_OVERFLOW;
   public static String STYLE_ORTHOGONAL;
   public static String STYLE_EXIT_X;
   public static String STYLE_EXIT_Y;
   public static String STYLE_EXIT_PERIMETER;
   public static String STYLE_ENTRY_X;
   public static String STYLE_ENTRY_Y;
   public static String STYLE_ENTRY_PERIMETER;
   public static String STYLE_WHITE_SPACE;
   public static String STYLE_ROTATION;
   public static String STYLE_FILLCOLOR;
   public static String STYLE_GRADIENTCOLOR;
   public static String STYLE_GRADIENT_DIRECTION;
   public static String STYLE_STROKECOLOR;
   public static String STYLE_SEPARATORCOLOR;
   public static String STYLE_STROKEWIDTH;
   public static String STYLE_ALIGN;
   public static String STYLE_VERTICAL_ALIGN;
   public static String STYLE_LABEL_POSITION;
   public static String STYLE_VERTICAL_LABEL_POSITION;
   public static String STYLE_IMAGE_ALIGN;
   public static String STYLE_IMAGE_VERTICAL_ALIGN;
   public static String STYLE_IMAGE;
   public static String STYLE_IMAGE_WIDTH;
   public static String STYLE_IMAGE_HEIGHT;
   public static String STYLE_IMAGE_BACKGROUND;
   public static String STYLE_IMAGE_BORDER;
   public static String STYLE_NOLABEL;
   public static String STYLE_NOEDGESTYLE;
   public static String STYLE_LABEL_BACKGROUNDCOLOR;
   public static String STYLE_LABEL_BORDERCOLOR;
   public static String STYLE_INDICATOR_SHAPE;
   public static String STYLE_INDICATOR_IMAGE;
   public static String STYLE_INDICATOR_COLOR;
   public static String STYLE_INDICATOR_GRADIENTCOLOR;
   public static String STYLE_INDICATOR_SPACING;
   public static String STYLE_INDICATOR_WIDTH;
   public static String STYLE_INDICATOR_HEIGHT;
   public static String STYLE_SHADOW;
   public static String STYLE_SEGMENT;
   public static String STYLE_ENDARROW;
   public static String STYLE_STARTARROW;
   public static String STYLE_ENDSIZE;
   public static String STYLE_STARTSIZE;
   public static String STYLE_DASHED;
   public static String STYLE_DASH_PATTERN;
   public static String STYLE_ROUNDED;
   public static String STYLE_SOURCE_PERIMETER_SPACING;
   public static String STYLE_TARGET_PERIMETER_SPACING;
   public static String STYLE_PERIMETER_SPACING;
   public static String STYLE_SPACING;
   public static String STYLE_SPACING_TOP;
   public static String STYLE_SPACING_LEFT;
   public static String STYLE_SPACING_BOTTOM;
   public static String STYLE_SPACING_RIGHT;
   public static String STYLE_HORIZONTAL;
   public static String STYLE_DIRECTION;
   public static String STYLE_ELBOW;
   public static String STYLE_FONTCOLOR;
   public static String STYLE_FONTFAMILY;
   public static String STYLE_FONTSIZE;
   public static String STYLE_FONTSTYLE;
   public static String STYLE_SHAPE;
   public static String STYLE_EDGE;
   public static String STYLE_LOOP;
   public static String STYLE_ROUTING_CENTER_X;
   public static String STYLE_ROUTING_CENTER_Y;
   public static final int FONT_BOLD = 1;
   public static final int FONT_ITALIC = 2;
   public static final int FONT_UNDERLINE = 4;
   public static final int FONT_SHADOW = 8;
   public static final String SHAPE_RECTANGLE = "rectangle";
   public static final String SHAPE_ELLIPSE = "ellipse";
   public static final String SHAPE_DOUBLE_ELLIPSE = "doubleEllipse";
   public static final String SHAPE_RHOMBUS = "rhombus";
   public static final String SHAPE_LINE = "line";
   public static final String SHAPE_IMAGE = "image";
   public static final String SHAPE_ARROW = "arrow";
   public static final String SHAPE_CURVE = "curve";
   public static final String SHAPE_LABEL = "label";
   public static final String SHAPE_CYLINDER = "cylinder";
   public static final String SHAPE_SWIMLANE = "swimlane";
   public static final String SHAPE_CONNECTOR = "connector";
   public static final String SHAPE_ACTOR = "actor";
   public static final String SHAPE_CLOUD = "cloud";
   public static final String SHAPE_TRIANGLE = "triangle";
   public static final String SHAPE_HEXAGON = "hexagon";
   public static final String ARROW_CLASSIC = "classic";
   public static final String ARROW_BLOCK = "block";
   public static final String ARROW_OPEN = "open";
   public static final String ARROW_OVAL = "oval";
   public static final String ARROW_DIAMOND = "diamond";
   public static final String ALIGN_LEFT = "left";
   public static final String ALIGN_CENTER = "center";
   public static final String ALIGN_RIGHT = "right";
   public static final String ALIGN_TOP = "top";
   public static final String ALIGN_MIDDLE = "middle";
   public static final String ALIGN_BOTTOM = "bottom";
   public static final String DIRECTION_NORTH = "north";
   public static final String DIRECTION_SOUTH = "south";
   public static final String DIRECTION_EAST = "east";
   public static final String DIRECTION_WEST = "west";
   public static final String ELBOW_VERTICAL = "vertical";
   public static final String ELBOW_HORIZONTAL = "horizontal";
   public static final String EDGESTYLE_ELBOW = "elbowEdgeStyle";
   public static final String EDGESTYLE_ENTITY_RELATION = "entityRelationEdgeStyle";
   public static final String EDGESTYLE_LOOP = "loopEdgeStyle";
   public static final String EDGESTYLE_SIDETOSIDE = "sideToSideEdgeStyle";
   public static final String EDGESTYLE_TOPTOBOTTOM = "topToBottomEdgeStyle";
   public static final String PERIMETER_ELLIPSE = "ellipsePerimeter";
   public static final String PERIMETER_RECTANGLE = "rectanglePerimeter";
   public static final String PERIMETER_RHOMBUS = "rhombusPerimeter";
   public static final String PERIMETER_TRIANGLE = "trianglePerimeter";

   static {
      SHADOW_COLOR = Color.gray;
      SHADOW_OFFSETX = 2;
      SHADOW_OFFSETY = 3;
      W3C_SHADOWCOLOR = "gray";
      SVG_SHADOWTRANSFORM = "translate(2 3)";
      DEFAULT_VALID_COLOR = Color.GREEN;
      DEFAULT_INVALID_COLOR = Color.RED;
      DEFAULT_DASHED_PATTERN = new float[]{3.0F, 3.0F};
      DEFAULT_LABEL_BUFFER = 12.0;
      RUBBERBAND_BORDERCOLOR = new Color(51, 153, 255);
      RUBBERBAND_FILLCOLOR = new Color(51, 153, 255, 80);
      HANDLE_SIZE = 7;
      LABEL_HANDLE_SIZE = 4;
      HANDLE_BORDERCOLOR = Color.black;
      HANDLE_FILLCOLOR = Color.green;
      LABEL_HANDLE_FILLCOLOR = Color.yellow;
      CONNECT_HANDLE_FILLCOLOR = Color.blue;
      LOCKED_HANDLE_FILLCOLOR = Color.red;
      CONNECT_HANDLE_ENABLED = false;
      CONNECT_HANDLE_SIZE = 8;
      EDGE_SELECTION_COLOR = Color.green;
      VERTEX_SELECTION_COLOR = Color.green;
      EDGE_SELECTION_STROKE = new BasicStroke(1.0F, 0, 0, 10.0F, new float[]{3.0F, 3.0F}, 0.0F);
      VERTEX_SELECTION_STROKE = new BasicStroke(1.0F, 0, 0, 10.0F, new float[]{3.0F, 3.0F}, 0.0F);
      PREVIEW_STROKE = new BasicStroke(1.0F, 0, 0, 10.0F, new float[]{3.0F, 3.0F}, 0.0F);
      PREVIEW_BORDER = new LineBorder(HANDLE_BORDERCOLOR) {
         private static final long serialVersionUID = 1348016511717964310L;

         public void paintBorder(Component var1, Graphics var2, int var3, int var4, int var5, int var6) {
            ((Graphics2D)var2).setStroke(mxConstants.VERTEX_SELECTION_STROKE);
            super.paintBorder(var1, var2, var3, var4, var5, var6);
         }
      };
      ENTITY_SEGMENT = 30;
      RECTANGLE_ROUNDING_FACTOR = 0.15;
      LINE_ARCSIZE = 10.0;
      ARROW_SPACING = 10;
      ARROW_WIDTH = 30;
      ARROW_SIZE = 30;
      NONE = "none";
      STYLE_PERIMETER = "perimeter";
      STYLE_SOURCE_PORT = "sourcePort";
      STYLE_TARGET_PORT = "targetPort";
      STYLE_OPACITY = "opacity";
      STYLE_TEXT_OPACITY = "textOpacity";
      STYLE_OVERFLOW = "overflow";
      STYLE_ORTHOGONAL = "orthogonal";
      STYLE_EXIT_X = "exitX";
      STYLE_EXIT_Y = "exitY";
      STYLE_EXIT_PERIMETER = "exitPerimeter";
      STYLE_ENTRY_X = "entryX";
      STYLE_ENTRY_Y = "entryY";
      STYLE_ENTRY_PERIMETER = "entryPerimeter";
      STYLE_WHITE_SPACE = "whiteSpace";
      STYLE_ROTATION = "rotation";
      STYLE_FILLCOLOR = "fillColor";
      STYLE_GRADIENTCOLOR = "gradientColor";
      STYLE_GRADIENT_DIRECTION = "gradientDirection";
      STYLE_STROKECOLOR = "strokeColor";
      STYLE_SEPARATORCOLOR = "separatorColor";
      STYLE_STROKEWIDTH = "strokeWidth";
      STYLE_ALIGN = "align";
      STYLE_VERTICAL_ALIGN = "verticalAlign";
      STYLE_LABEL_POSITION = "labelPosition";
      STYLE_VERTICAL_LABEL_POSITION = "verticalLabelPosition";
      STYLE_IMAGE_ALIGN = "imageAlign";
      STYLE_IMAGE_VERTICAL_ALIGN = "imageVerticalAlign";
      STYLE_IMAGE = "image";
      STYLE_IMAGE_WIDTH = "imageWidth";
      STYLE_IMAGE_HEIGHT = "imageHeight";
      STYLE_IMAGE_BACKGROUND = "imageBackground";
      STYLE_IMAGE_BORDER = "imageBorder";
      STYLE_NOLABEL = "noLabel";
      STYLE_NOEDGESTYLE = "noEdgeStyle";
      STYLE_LABEL_BACKGROUNDCOLOR = "labelBackgroundColor";
      STYLE_LABEL_BORDERCOLOR = "labelBorderColor";
      STYLE_INDICATOR_SHAPE = "indicatorShape";
      STYLE_INDICATOR_IMAGE = "indicatorImage";
      STYLE_INDICATOR_COLOR = "indicatorColor";
      STYLE_INDICATOR_GRADIENTCOLOR = "indicatorGradientColor";
      STYLE_INDICATOR_SPACING = "indicatorSpacing";
      STYLE_INDICATOR_WIDTH = "indicatorWidth";
      STYLE_INDICATOR_HEIGHT = "indicatorHeight";
      STYLE_SHADOW = "shadow";
      STYLE_SEGMENT = "segment";
      STYLE_ENDARROW = "endArrow";
      STYLE_STARTARROW = "startArrow";
      STYLE_ENDSIZE = "endSize";
      STYLE_STARTSIZE = "startSize";
      STYLE_DASHED = "dashed";
      STYLE_DASH_PATTERN = "dashPattern";
      STYLE_ROUNDED = "rounded";
      STYLE_SOURCE_PERIMETER_SPACING = "sourcePerimeterSpacing";
      STYLE_TARGET_PERIMETER_SPACING = "targetPerimeterSpacing";
      STYLE_PERIMETER_SPACING = "perimeterSpacing";
      STYLE_SPACING = "spacing";
      STYLE_SPACING_TOP = "spacingTop";
      STYLE_SPACING_LEFT = "spacingLeft";
      STYLE_SPACING_BOTTOM = "spacingBottom";
      STYLE_SPACING_RIGHT = "spacingRight";
      STYLE_HORIZONTAL = "horizontal";
      STYLE_DIRECTION = "direction";
      STYLE_ELBOW = "elbow";
      STYLE_FONTCOLOR = "fontColor";
      STYLE_FONTFAMILY = "fontFamily";
      STYLE_FONTSIZE = "fontSize";
      STYLE_FONTSTYLE = "fontStyle";
      STYLE_SHAPE = "shape";
      STYLE_EDGE = "edgeStyle";
      STYLE_LOOP = "loopStyle";
      STYLE_ROUTING_CENTER_X = "routingCenterX";
      STYLE_ROUTING_CENTER_Y = "routingCenterY";
   }
}
