package net.jsign.pe;

public enum DataDirectoryType {
   EXPORT_TABLE,
   IMPORT_TABLE,
   RESOURCE_TABLE,
   EXCEPTION_TABLE,
   CERTIFICATE_TABLE,
   BASE_RELOCATION_TABLE,
   DEBUG,
   ARCHITECTURE,
   GLOBAL_POINTER,
   THREAD_LOCAL_STORAGE_TABLE,
   LOAD_CONFIG_TABLE,
   BOUND_IMPORT_TABLE,
   IMPORT_ADDRESS_TABLE,
   DELAY_LOAD_IMPORT_TABLE,
   CLR_RUNTIME_HEADER;
}
